// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlcgen

import (
	"context"
)

const countOverwriteAllowAny = `-- name: CountOverwriteAllowAny :one
SELECT COUNT(*) FROM permission_overwrites
WHERE resource_type = ? AND user_id = ? AND instr(allow, ?3) > 0
`

type CountOverwriteAllowAnyParams struct {
	ResourceType string
	UserID       string
	QuotedAction string
}

func (q *Queries) CountOverwriteAllowAny(ctx context.Context, arg CountOverwriteAllowAnyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOverwriteAllowAny, arg.ResourceType, arg.UserID, arg.QuotedAction)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOverwrite = `-- name: DeleteOverwrite :execrows
DELETE FROM permission_overwrites WHERE resource_type = ? AND resource_id = ? AND user_id = ?
`

type DeleteOverwriteParams struct {
	ResourceType string
	ResourceID   string
	UserID       string
}

func (q *Queries) DeleteOverwrite(ctx context.Context, arg DeleteOverwriteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOverwrite, arg.ResourceType, arg.ResourceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOverwritesByResource = `-- name: DeleteOverwritesByResource :exec
DELETE FROM permission_overwrites WHERE resource_type = ? AND resource_id = ?
`

type DeleteOverwritesByResourceParams struct {
	ResourceType string
	ResourceID   string
}

func (q *Queries) DeleteOverwritesByResource(ctx context.Context, arg DeleteOverwritesByResourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteOverwritesByResource, arg.ResourceType, arg.ResourceID)
	return err
}

const getOverwrite = `-- name: GetOverwrite :one
SELECT resource_type, resource_id, user_id, allow, deny, created_at, updated_at FROM permission_overwrites WHERE resource_type = ? AND resource_id = ? AND user_id = ?
`

type GetOverwriteParams struct {
	ResourceType string
	ResourceID   string
	UserID       string
}

func (q *Queries) GetOverwrite(ctx context.Context, arg GetOverwriteParams) (PermissionOverwrite, error) {
	row := q.db.QueryRowContext(ctx, getOverwrite, arg.ResourceType, arg.ResourceID, arg.UserID)
	var i PermissionOverwrite
	err := row.Scan(
		&i.ResourceType,
		&i.ResourceID,
		&i.UserID,
		&i.Allow,
		&i.Deny,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverwritesByResource = `-- name: ListOverwritesByResource :many
SELECT resource_type, resource_id, user_id, allow, deny, created_at, updated_at FROM permission_overwrites WHERE resource_type = ? AND resource_id = ? ORDER BY user_id
`

type ListOverwritesByResourceParams struct {
	ResourceType string
	ResourceID   string
}

func (q *Queries) ListOverwritesByResource(ctx context.Context, arg ListOverwritesByResourceParams) ([]PermissionOverwrite, error) {
	rows, err := q.db.QueryContext(ctx, listOverwritesByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PermissionOverwrite
	for rows.Next() {
		var i PermissionOverwrite
		if err := rows.Scan(
			&i.ResourceType,
			&i.ResourceID,
			&i.UserID,
			&i.Allow,
			&i.Deny,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOverwrite = `-- name: UpsertOverwrite :execrows
INSERT INTO permission_overwrites (resource_type, resource_id, user_id, allow, deny, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?6)
ON CONFLICT(resource_type, resource_id, user_id) DO UPDATE SET
  allow = excluded.allow, deny = excluded.deny, updated_at = excluded.updated_at
`

type UpsertOverwriteParams struct {
	ResourceType string
	ResourceID   string
	UserID       string
	Allow        string
	Deny         string
	Now          int64
}

func (q *Queries) UpsertOverwrite(ctx context.Context, arg UpsertOverwriteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertOverwrite,
		arg.ResourceType,
		arg.ResourceID,
		arg.UserID,
		arg.Allow,
		arg.Deny,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
