// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, doc_id, ticket_id, conversation_id, memory_id, name, content_type, size, uploaded_by, created_at, data)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID             string
	DocID          sql.NullString
	TicketID       sql.NullString
	ConversationID sql.NullString
	MemoryID       sql.NullString
	Name           string
	ContentType    string
	Size           int64
	UploadedBy     string
	CreatedAt      int64
	Data           []byte
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.DocID,
		arg.TicketID,
		arg.ConversationID,
		arg.MemoryID,
		arg.Name,
		arg.ContentType,
		arg.Size,
		arg.UploadedBy,
		arg.CreatedAt,
		arg.Data,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :execrows
DELETE FROM attachments WHERE id = ?
`

func (q *Queries) DeleteAttachment(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAttachment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, doc_id, ticket_id, conversation_id, memory_id, name, content_type, size, data, uploaded_by, created_at FROM attachments WHERE id = ?
`

func (q *Queries) GetAttachment(ctx context.Context, id string) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.TicketID,
		&i.ConversationID,
		&i.MemoryID,
		&i.Name,
		&i.ContentType,
		&i.Size,
		&i.Data,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByOwner = `-- name: ListAttachmentsByOwner :many
SELECT id, doc_id, ticket_id, conversation_id, memory_id, name, content_type, size, uploaded_by, created_at
FROM attachments WHERE doc_id = ? OR ticket_id = ? OR conversation_id = ? OR memory_id = ? ORDER BY created_at, id
`

type ListAttachmentsByOwnerParams struct {
	DocID          sql.NullString
	TicketID       sql.NullString
	ConversationID sql.NullString
	MemoryID       sql.NullString
}

type ListAttachmentsByOwnerRow struct {
	ID             string
	DocID          sql.NullString
	TicketID       sql.NullString
	ConversationID sql.NullString
	MemoryID       sql.NullString
	Name           string
	ContentType    string
	Size           int64
	UploadedBy     string
	CreatedAt      int64
}

func (q *Queries) ListAttachmentsByOwner(ctx context.Context, arg ListAttachmentsByOwnerParams) ([]ListAttachmentsByOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByOwner,
		arg.DocID,
		arg.TicketID,
		arg.ConversationID,
		arg.MemoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsByOwnerRow
	for rows.Next() {
		var i ListAttachmentsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.TicketID,
			&i.ConversationID,
			&i.MemoryID,
			&i.Name,
			&i.ContentType,
			&i.Size,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
