// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addAllowlistMember = `-- name: AddAllowlistMember :exec
INSERT INTO allowlist (login, added_at) VALUES (?, ?)
`

type AddAllowlistMemberParams struct {
	Login   string
	AddedAt int64
}

func (q *Queries) AddAllowlistMember(ctx context.Context, arg AddAllowlistMemberParams) error {
	_, err := q.db.ExecContext(ctx, addAllowlistMember, arg.Login, arg.AddedAt)
	return err
}

const countAllowlistMember = `-- name: CountAllowlistMember :one
SELECT COUNT(*) FROM allowlist WHERE login = ?
`

func (q *Queries) CountAllowlistMember(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllowlistMember, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIdentitiesByUser = `-- name: CountIdentitiesByUser :one
SELECT COUNT(*) FROM user_identities WHERE user_id = ?
`

func (q *Queries) CountIdentitiesByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIdentitiesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountInvitations = `-- name: DeleteAccountInvitations :exec
DELETE FROM invitations WHERE invited_by = ? AND redeemed_at IS NULL
`

func (q *Queries) DeleteAccountInvitations(ctx context.Context, invitedBy string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountInvitations, invitedBy)
	return err
}

const deleteAccountMemberships = `-- name: DeleteAccountMemberships :exec
DELETE FROM workspace_members WHERE user_id = ?
`

func (q *Queries) DeleteAccountMemberships(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountMemberships, userID)
	return err
}

const deleteAccountOverwrites = `-- name: DeleteAccountOverwrites :exec
DELETE FROM permission_overwrites WHERE user_id = ?
`

func (q *Queries) DeleteAccountOverwrites(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountOverwrites, userID)
	return err
}

const deleteAccountPairingComputers = `-- name: DeleteAccountPairingComputers :exec
DELETE FROM pairing_computers WHERE user_id = ?
`

func (q *Queries) DeleteAccountPairingComputers(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountPairingComputers, userID)
	return err
}

const deleteAccountPairingDefaults = `-- name: DeleteAccountPairingDefaults :exec
DELETE FROM pairing_user_defaults WHERE user_id = ?
`

func (q *Queries) DeleteAccountPairingDefaults(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteAccountPairingDefaults, userID)
	return err
}

const deleteIdentity = `-- name: DeleteIdentity :execrows
DELETE FROM user_identities WHERE user_id = ? AND provider = ?
`

type DeleteIdentityParams struct {
	UserID   string
	Provider string
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteIdentity, arg.UserID, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSettings = `-- name: GetSettings :one
SELECT id, instance_url, settings_version, updated_at, github_oauth_client_id, github_oauth_client_secret, google_oauth_client_id, google_oauth_client_secret, discord_oauth_client_id, discord_oauth_client_secret FROM instance_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.SettingsVersion,
		&i.UpdatedAt,
		&i.GithubOauthClientID,
		&i.GithubOauthClientSecret,
		&i.GoogleOauthClientID,
		&i.GoogleOauthClientSecret,
		&i.DiscordOauthClientID,
		&i.DiscordOauthClientSecret,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, name, avatar_url, first_login_done, display_name, avatar_override_url, account_status, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.login, u.name, u.avatar_url, u.first_login_done, u.display_name, u.avatar_override_url, u.account_status, u.created_at, u.updated_at FROM users u JOIN user_identities i ON i.user_id = u.id
WHERE i.provider = ? AND i.provider_user_id = ?
`

type GetUserByIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIdentity, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, name, avatar_url, first_login_done, display_name, avatar_override_url, account_status, created_at, updated_at FROM users WHERE lower(login) = lower(?)
`

func (q *Queries) GetUserByLogin(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO user_identities (user_id, provider, provider_user_id, login, name, avatar_url, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertIdentityParams struct {
	UserID         string
	Provider       string
	ProviderUserID string
	Login          string
	Name           string
	AvatarUrl      string
	CreatedAt      int64
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, login, name, avatar_url, first_login_done, created_at, updated_at)
VALUES (?, ?, ?, ?, 0, ?, ?)
`

type InsertUserParams struct {
	ID        string
	Login     string
	Name      string
	AvatarUrl string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listActiveOwnerIDs = `-- name: ListActiveOwnerIDs :many
SELECT DISTINCT m.user_id FROM workspace_members m
JOIN roles r ON r.id = m.role_id AND r.is_owner_role = 1
JOIN users u ON u.id = m.user_id AND u.account_status = 'active'
ORDER BY m.user_id
`

func (q *Queries) ListActiveOwnerIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveOwnerIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllowlist = `-- name: ListAllowlist :many
SELECT login FROM allowlist ORDER BY login
`

func (q *Queries) ListAllowlist(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllowlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login string
		if err := rows.Scan(&login); err != nil {
			return nil, err
		}
		items = append(items, login)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT user_id, provider, provider_user_id, login, name, avatar_url, created_at FROM user_identities WHERE user_id = ? ORDER BY created_at, provider
`

func (q *Queries) ListIdentitiesByUser(ctx context.Context, userID string) ([]UserIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentitiesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Login,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, login, name, avatar_url, first_login_done, display_name, avatar_override_url, account_status, created_at, updated_at FROM users ORDER BY login
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.Name,
			&i.AvatarUrl,
			&i.FirstLoginDone,
			&i.DisplayName,
			&i.AvatarOverrideUrl,
			&i.AccountStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFirstLoginDone = `-- name: MarkFirstLoginDone :execrows
UPDATE users SET first_login_done = 1, updated_at = ? WHERE id = ?
`

type MarkFirstLoginDoneParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) MarkFirstLoginDone(ctx context.Context, arg MarkFirstLoginDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFirstLoginDone, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeAllowlistMember = `-- name: RemoveAllowlistMember :execrows
DELETE FROM allowlist WHERE login = ?
`

func (q *Queries) RemoveAllowlistMember(ctx context.Context, login string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeAllowlistMember, login)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeAccountPATs = `-- name: RevokeAccountPATs :exec
UPDATE personal_access_tokens SET revoked_at = ? WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeAccountPATsParams struct {
	RevokedAt sql.NullInt64
	UserID    string
}

func (q *Queries) RevokeAccountPATs(ctx context.Context, arg RevokeAccountPATsParams) error {
	_, err := q.db.ExecContext(ctx, revokeAccountPATs, arg.RevokedAt, arg.UserID)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :execrows
UPDATE users SET account_status = ?, updated_at = ? WHERE id = ?
`

type SetAccountStatusParams struct {
	AccountStatus string
	UpdatedAt     int64
	ID            string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountStatus, arg.AccountStatus, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setInstanceURL = `-- name: SetInstanceURL :execrows
UPDATE instance_settings SET instance_url = ?, settings_version = settings_version + 1, updated_at = ? WHERE id = 1
`

type SetInstanceURLParams struct {
	InstanceUrl string
	UpdatedAt   int64
}

func (q *Queries) SetInstanceURL(ctx context.Context, arg SetInstanceURLParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstanceURL, arg.InstanceUrl, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProfileOverride = `-- name: SetProfileOverride :execrows
UPDATE users SET display_name = ?, avatar_override_url = ?, updated_at = ? WHERE id = ?
`

type SetProfileOverrideParams struct {
	DisplayName       sql.NullString
	AvatarOverrideUrl sql.NullString
	UpdatedAt         int64
	ID                string
}

func (q *Queries) SetProfileOverride(ctx context.Context, arg SetProfileOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProfileOverride,
		arg.DisplayName,
		arg.AvatarOverrideUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSettingsGitHubOAuth = `-- name: SetSettingsGitHubOAuth :execrows
UPDATE instance_settings SET github_oauth_client_id = ?, github_oauth_client_secret = ?, updated_at = ? WHERE id = 1
`

type SetSettingsGitHubOAuthParams struct {
	GithubOauthClientID     string
	GithubOauthClientSecret string
	UpdatedAt               int64
}

func (q *Queries) SetSettingsGitHubOAuth(ctx context.Context, arg SetSettingsGitHubOAuthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSettingsGitHubOAuth, arg.GithubOauthClientID, arg.GithubOauthClientSecret, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const syncIdentity = `-- name: SyncIdentity :exec
UPDATE user_identities SET login = ?, name = ?, avatar_url = ? WHERE provider = ? AND provider_user_id = ?
`

type SyncIdentityParams struct {
	Login          string
	Name           string
	AvatarUrl      string
	Provider       string
	ProviderUserID string
}

func (q *Queries) SyncIdentity(ctx context.Context, arg SyncIdentityParams) error {
	_, err := q.db.ExecContext(ctx, syncIdentity,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderUserID,
	)
	return err
}

const syncUserFromFirstIdentity = `-- name: SyncUserFromFirstIdentity :exec
UPDATE users SET login = ?, name = ?, avatar_url = ?, updated_at = ?
WHERE id = ?5
  AND ?6 = (SELECT provider FROM user_identities WHERE user_id = ?5 ORDER BY created_at, provider LIMIT 1)
`

type SyncUserFromFirstIdentityParams struct {
	Login     string
	Name      string
	AvatarUrl string
	UpdatedAt int64
	UserID    string
	Provider  string
}

func (q *Queries) SyncUserFromFirstIdentity(ctx context.Context, arg SyncUserFromFirstIdentityParams) error {
	_, err := q.db.ExecContext(ctx, syncUserFromFirstIdentity,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.UpdatedAt,
		arg.UserID,
		arg.Provider,
	)
	return err
}
