// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addAllowlistMember = `-- name: AddAllowlistMember :exec
INSERT INTO allowlist (login, added_at) VALUES (?, ?)
`

type AddAllowlistMemberParams struct {
	Login   string
	AddedAt int64
}

func (q *Queries) AddAllowlistMember(ctx context.Context, arg AddAllowlistMemberParams) error {
	_, err := q.db.ExecContext(ctx, addAllowlistMember, arg.Login, arg.AddedAt)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT COUNT(*) FROM users WHERE can_create_workspace = 1 AND account_status = 'active'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllowlistMember = `-- name: CountAllowlistMember :one
SELECT COUNT(*) FROM allowlist WHERE login = ?
`

func (q *Queries) CountAllowlistMember(ctx context.Context, login string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllowlistMember, login)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCanCreateWorkspace = `-- name: CountCanCreateWorkspace :one
SELECT COUNT(*) FROM users WHERE can_create_workspace = 1
`

func (q *Queries) CountCanCreateWorkspace(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCanCreateWorkspace)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, instance_url, settings_version, updated_at, github_oauth_client_id, github_oauth_client_secret, mention_chip_template, google_oauth_client_id, google_oauth_client_secret, discord_oauth_client_id, discord_oauth_client_secret, runner_secret FROM instance_settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (InstanceSetting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i InstanceSetting
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.SettingsVersion,
		&i.UpdatedAt,
		&i.GithubOauthClientID,
		&i.GithubOauthClientSecret,
		&i.MentionChipTemplate,
		&i.GoogleOauthClientID,
		&i.GoogleOauthClientSecret,
		&i.DiscordOauthClientID,
		&i.DiscordOauthClientSecret,
		&i.RunnerSecret,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, display_name, avatar_override_url, account_status FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanCreateWorkspace,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, display_name, avatar_override_url, account_status FROM users WHERE lower(login) = lower(?)
`

func (q *Queries) GetUserByLogin(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByLogin, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanCreateWorkspace,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, display_name, avatar_override_url, account_status FROM users WHERE provider = ? AND provider_user_id = ?
`

type GetUserByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanCreateWorkspace,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
	)
	return i, err
}

const getUserIDByProvider = `-- name: GetUserIDByProvider :one
SELECT id FROM users WHERE provider = ? AND provider_user_id = ?
`

type GetUserIDByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserIDByProvider(ctx context.Context, arg GetUserIDByProviderParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByProvider, arg.Provider, arg.ProviderUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, provider, provider_user_id, login, name, avatar_url, can_create_workspace, first_login_done, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?, ?)
`

type InsertUserParams struct {
	ID             string
	Provider       string
	ProviderUserID string
	Login          string
	Name           string
	AvatarUrl      string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAllowlist = `-- name: ListAllowlist :many
SELECT login FROM allowlist ORDER BY login
`

func (q *Queries) ListAllowlist(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllowlist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var login string
		if err := rows.Scan(&login); err != nil {
			return nil, err
		}
		items = append(items, login)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, display_name, avatar_override_url, account_status FROM users ORDER BY login
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Login,
			&i.Name,
			&i.AvatarUrl,
			&i.FirstLoginDone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanCreateWorkspace,
			&i.DisplayName,
			&i.AvatarOverrideUrl,
			&i.AccountStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFirstLoginDone = `-- name: MarkFirstLoginDone :execrows
UPDATE users SET first_login_done = 1, updated_at = ? WHERE id = ?
`

type MarkFirstLoginDoneParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) MarkFirstLoginDone(ctx context.Context, arg MarkFirstLoginDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFirstLoginDone, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeAllowlistMember = `-- name: RemoveAllowlistMember :execrows
DELETE FROM allowlist WHERE login = ?
`

func (q *Queries) RemoveAllowlistMember(ctx context.Context, login string) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeAllowlistMember, login)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAccountStatus = `-- name: SetAccountStatus :execrows
UPDATE users SET account_status = ?, updated_at = ? WHERE id = ?
`

type SetAccountStatusParams struct {
	AccountStatus string
	UpdatedAt     int64
	ID            string
}

func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAccountStatus, arg.AccountStatus, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setCanCreateWorkspace = `-- name: SetCanCreateWorkspace :execrows
UPDATE users SET can_create_workspace = ?, updated_at = ? WHERE id = ?
`

type SetCanCreateWorkspaceParams struct {
	CanCreateWorkspace int64
	UpdatedAt          int64
	ID                 string
}

func (q *Queries) SetCanCreateWorkspace(ctx context.Context, arg SetCanCreateWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCanCreateWorkspace, arg.CanCreateWorkspace, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setInstanceURL = `-- name: SetInstanceURL :execrows
UPDATE instance_settings SET instance_url = ?, settings_version = settings_version + 1, updated_at = ? WHERE id = 1
`

type SetInstanceURLParams struct {
	InstanceUrl string
	UpdatedAt   int64
}

func (q *Queries) SetInstanceURL(ctx context.Context, arg SetInstanceURLParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstanceURL, arg.InstanceUrl, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setProfileOverride = `-- name: SetProfileOverride :execrows
UPDATE users SET display_name = ?, avatar_override_url = ?, updated_at = ? WHERE id = ?
`

type SetProfileOverrideParams struct {
	DisplayName       sql.NullString
	AvatarOverrideUrl sql.NullString
	UpdatedAt         int64
	ID                string
}

func (q *Queries) SetProfileOverride(ctx context.Context, arg SetProfileOverrideParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setProfileOverride,
		arg.DisplayName,
		arg.AvatarOverrideUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSettingsGitHubOAuth = `-- name: SetSettingsGitHubOAuth :execrows
UPDATE instance_settings SET github_oauth_client_id = ?, github_oauth_client_secret = ?, updated_at = ? WHERE id = 1
`

type SetSettingsGitHubOAuthParams struct {
	GithubOauthClientID     string
	GithubOauthClientSecret string
	UpdatedAt               int64
}

func (q *Queries) SetSettingsGitHubOAuth(ctx context.Context, arg SetSettingsGitHubOAuthParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSettingsGitHubOAuth, arg.GithubOauthClientID, arg.GithubOauthClientSecret, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setSettingsMentionChipTemplate = `-- name: SetSettingsMentionChipTemplate :execrows
UPDATE instance_settings SET mention_chip_template = ?, updated_at = ? WHERE id = 1
`

type SetSettingsMentionChipTemplateParams struct {
	MentionChipTemplate string
	UpdatedAt           int64
}

func (q *Queries) SetSettingsMentionChipTemplate(ctx context.Context, arg SetSettingsMentionChipTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSettingsMentionChipTemplate, arg.MentionChipTemplate, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const syncUser = `-- name: SyncUser :exec
UPDATE users SET login = ?, name = ?, avatar_url = ?, updated_at = ? WHERE id = ?
`

type SyncUserParams struct {
	Login     string
	Name      string
	AvatarUrl string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SyncUser(ctx context.Context, arg SyncUserParams) error {
	_, err := q.db.ExecContext(ctx, syncUser,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
