// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_cursors.sql

package sqlcgen

import (
	"context"
)

const getAutomationCursor = `-- name: GetAutomationCursor :one
SELECT last_created_at, last_event_id FROM automation_cursors WHERE automation_id = ?
`

type GetAutomationCursorRow struct {
	LastCreatedAt int64
	LastEventID   string
}

func (q *Queries) GetAutomationCursor(ctx context.Context, automationID string) (GetAutomationCursorRow, error) {
	row := q.db.QueryRowContext(ctx, getAutomationCursor, automationID)
	var i GetAutomationCursorRow
	err := row.Scan(&i.LastCreatedAt, &i.LastEventID)
	return i, err
}

const setAutomationCursor = `-- name: SetAutomationCursor :exec
INSERT INTO automation_cursors (automation_id, last_created_at, last_event_id, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(automation_id) DO UPDATE SET last_created_at = excluded.last_created_at, last_event_id = excluded.last_event_id, updated_at = excluded.updated_at
`

type SetAutomationCursorParams struct {
	AutomationID  string
	LastCreatedAt int64
	LastEventID   string
	UpdatedAt     int64
}

func (q *Queries) SetAutomationCursor(ctx context.Context, arg SetAutomationCursorParams) error {
	_, err := q.db.ExecContext(ctx, setAutomationCursor,
		arg.AutomationID,
		arg.LastCreatedAt,
		arg.LastEventID,
		arg.UpdatedAt,
	)
	return err
}
