// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAutomation = `-- name: CreateAutomation :exec
INSERT INTO automations (id, name, description, kind, enabled, subscriptions, config_schema, config_values, scopes, created_by, token_hash, token_prefix, token_revoked_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAutomationParams struct {
	ID             string
	Name           string
	Description    string
	Kind           string
	Enabled        int64
	Subscriptions  []byte
	ConfigSchema   []byte
	ConfigValues   []byte
	Scopes         []byte
	CreatedBy      string
	TokenHash      string
	TokenPrefix    string
	TokenRevokedAt sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) error {
	_, err := q.db.ExecContext(ctx, createAutomation,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Enabled,
		arg.Subscriptions,
		arg.ConfigSchema,
		arg.ConfigValues,
		arg.Scopes,
		arg.CreatedBy,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.TokenRevokedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAutomation = `-- name: DeleteAutomation :execrows
DELETE FROM automations WHERE id = ?
`

func (q *Queries) DeleteAutomation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAutomation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, name, description, kind, enabled, subscriptions, config_schema, config_values, scopes, token_hash, token_prefix, token_revoked_at, created_at, updated_at, created_by FROM automations WHERE id = ?
`

func (q *Queries) GetAutomation(ctx context.Context, id string) (Automation, error) {
	row := q.db.QueryRowContext(ctx, getAutomation, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Enabled,
		&i.Subscriptions,
		&i.ConfigSchema,
		&i.ConfigValues,
		&i.Scopes,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAutomationByTokenHash = `-- name: GetAutomationByTokenHash :one
SELECT id, name, description, kind, enabled, subscriptions, config_schema, config_values, scopes, token_hash, token_prefix, token_revoked_at, created_at, updated_at, created_by FROM automations WHERE token_hash = ?
`

func (q *Queries) GetAutomationByTokenHash(ctx context.Context, tokenHash string) (Automation, error) {
	row := q.db.QueryRowContext(ctx, getAutomationByTokenHash, tokenHash)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Kind,
		&i.Enabled,
		&i.Subscriptions,
		&i.ConfigSchema,
		&i.ConfigValues,
		&i.Scopes,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenRevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listAutomations = `-- name: ListAutomations :many
SELECT id, name, description, kind, enabled, subscriptions, config_schema, config_values, scopes, token_hash, token_prefix, token_revoked_at, created_at, updated_at, created_by FROM automations ORDER BY created_at
`

func (q *Queries) ListAutomations(ctx context.Context) ([]Automation, error) {
	rows, err := q.db.QueryContext(ctx, listAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Kind,
			&i.Enabled,
			&i.Subscriptions,
			&i.ConfigSchema,
			&i.ConfigValues,
			&i.Scopes,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.TokenRevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutomation = `-- name: UpdateAutomation :execrows
UPDATE automations SET name = ?, description = ?, kind = ?, enabled = ?, subscriptions = ?, config_schema = ?, config_values = ?, scopes = ?, token_hash = ?, token_prefix = ?, token_revoked_at = ?, updated_at = ? WHERE id = ?
`

type UpdateAutomationParams struct {
	Name           string
	Description    string
	Kind           string
	Enabled        int64
	Subscriptions  []byte
	ConfigSchema   []byte
	ConfigValues   []byte
	Scopes         []byte
	TokenHash      string
	TokenPrefix    string
	TokenRevokedAt sql.NullInt64
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateAutomation(ctx context.Context, arg UpdateAutomationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAutomation,
		arg.Name,
		arg.Description,
		arg.Kind,
		arg.Enabled,
		arg.Subscriptions,
		arg.ConfigSchema,
		arg.ConfigValues,
		arg.Scopes,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.TokenRevokedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
