// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_eventlog.sql

package sqlcgen

import (
	"context"
	"strings"
)

const latestOutboxPosition = `-- name: LatestOutboxPosition :one
SELECT id, created_at FROM outbox ORDER BY created_at DESC, id DESC LIMIT 1
`

type LatestOutboxPositionRow struct {
	ID        string
	CreatedAt int64
}

func (q *Queries) LatestOutboxPosition(ctx context.Context) (LatestOutboxPositionRow, error) {
	row := q.db.QueryRowContext(ctx, latestOutboxPosition)
	var i LatestOutboxPositionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listOutboxAfterCursor = `-- name: ListOutboxAfterCursor :many
SELECT id, topic, payload, created_at FROM outbox
WHERE topic IN (/*SLICE:topics*/?) AND (created_at > ?2 OR (created_at = ?2 AND id > ?3))
ORDER BY created_at, id LIMIT ?4
`

type ListOutboxAfterCursorParams struct {
	Topics          []string
	CursorCreatedAt int64
	CursorID        string
	Limit           int64
}

type ListOutboxAfterCursorRow struct {
	ID        string
	Topic     string
	Payload   []byte
	CreatedAt int64
}

func (q *Queries) ListOutboxAfterCursor(ctx context.Context, arg ListOutboxAfterCursorParams) ([]ListOutboxAfterCursorRow, error) {
	query := listOutboxAfterCursor
	var queryParams []interface{}
	if len(arg.Topics) > 0 {
		for _, v := range arg.Topics {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:topics*/?", strings.Repeat(",?", len(arg.Topics))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:topics*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CursorCreatedAt)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboxAfterCursorRow
	for rows.Next() {
		var i ListOutboxAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
