// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_secrets.sql

package sqlcgen

import (
	"context"
)

const deleteAutomationSecret = `-- name: DeleteAutomationSecret :exec
DELETE FROM automation_secrets WHERE workspace_id = ? AND name = ?
`

type DeleteAutomationSecretParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) DeleteAutomationSecret(ctx context.Context, arg DeleteAutomationSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteAutomationSecret, arg.WorkspaceID, arg.Name)
	return err
}

const listAutomationSecretMeta = `-- name: ListAutomationSecretMeta :many
SELECT name, created_at, updated_at FROM automation_secrets WHERE workspace_id = ? ORDER BY name
`

type ListAutomationSecretMetaRow struct {
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) ListAutomationSecretMeta(ctx context.Context, workspaceID string) ([]ListAutomationSecretMetaRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationSecretMeta, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutomationSecretMetaRow
	for rows.Next() {
		var i ListAutomationSecretMetaRow
		if err := rows.Scan(&i.Name, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomationSecretValues = `-- name: ListAutomationSecretValues :many
SELECT name, value FROM automation_secrets WHERE workspace_id = ?
`

type ListAutomationSecretValuesRow struct {
	Name  string
	Value string
}

func (q *Queries) ListAutomationSecretValues(ctx context.Context, workspaceID string) ([]ListAutomationSecretValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationSecretValues, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutomationSecretValuesRow
	for rows.Next() {
		var i ListAutomationSecretValuesRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAutomationSecret = `-- name: SetAutomationSecret :exec
INSERT INTO automation_secrets (workspace_id, name, value, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, name) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type SetAutomationSecretParams struct {
	WorkspaceID string
	Name        string
	Value       string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) SetAutomationSecret(ctx context.Context, arg SetAutomationSecretParams) error {
	_, err := q.db.ExecContext(ctx, setAutomationSecret,
		arg.WorkspaceID,
		arg.Name,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
