// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_hosts.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const consumeAutomationHostEnrollmentCode = `-- name: ConsumeAutomationHostEnrollmentCode :execrows
DELETE FROM automation_host_enrollment_codes WHERE code_hash = ? AND expires_at > ?
`

type ConsumeAutomationHostEnrollmentCodeParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) ConsumeAutomationHostEnrollmentCode(ctx context.Context, arg ConsumeAutomationHostEnrollmentCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeAutomationHostEnrollmentCode, arg.CodeHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAutomationHost = `-- name: CreateAutomationHost :exec
INSERT INTO automation_hosts (id, name, machine, os, arch, version, last_seen, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAutomationHostParams struct {
	ID        string
	Name      string
	Machine   string
	Os        string
	Arch      string
	Version   string
	LastSeen  int64
	CreatedAt int64
}

func (q *Queries) CreateAutomationHost(ctx context.Context, arg CreateAutomationHostParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationHost,
		arg.ID,
		arg.Name,
		arg.Machine,
		arg.Os,
		arg.Arch,
		arg.Version,
		arg.LastSeen,
		arg.CreatedAt,
	)
	return err
}

const createAutomationHostCredential = `-- name: CreateAutomationHostCredential :exec
INSERT INTO automation_host_credentials (credential_hash, host_id, host_name, created_at) VALUES (?, ?, ?, ?)
`

type CreateAutomationHostCredentialParams struct {
	CredentialHash string
	HostID         string
	HostName       string
	CreatedAt      int64
}

func (q *Queries) CreateAutomationHostCredential(ctx context.Context, arg CreateAutomationHostCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationHostCredential,
		arg.CredentialHash,
		arg.HostID,
		arg.HostName,
		arg.CreatedAt,
	)
	return err
}

const createAutomationHostEnrollmentCode = `-- name: CreateAutomationHostEnrollmentCode :exec
INSERT INTO automation_host_enrollment_codes (code_hash, name, machine, created_at, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateAutomationHostEnrollmentCodeParams struct {
	CodeHash  string
	Name      string
	Machine   string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateAutomationHostEnrollmentCode(ctx context.Context, arg CreateAutomationHostEnrollmentCodeParams) error {
	_, err := q.db.ExecContext(ctx, createAutomationHostEnrollmentCode,
		arg.CodeHash,
		arg.Name,
		arg.Machine,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteAutomationHost = `-- name: DeleteAutomationHost :execrows
DELETE FROM automation_hosts WHERE id = ?
`

func (q *Queries) DeleteAutomationHost(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAutomationHost, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAutomationHost = `-- name: GetAutomationHost :one
SELECT id, name, machine, os, arch, version, last_seen, created_at FROM automation_hosts WHERE id = ?
`

func (q *Queries) GetAutomationHost(ctx context.Context, id string) (AutomationHost, error) {
	row := q.db.QueryRowContext(ctx, getAutomationHost, id)
	var i AutomationHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Machine,
		&i.Os,
		&i.Arch,
		&i.Version,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationHostByName = `-- name: GetAutomationHostByName :one
SELECT id, name, machine, os, arch, version, last_seen, created_at FROM automation_hosts WHERE name = ?
`

func (q *Queries) GetAutomationHostByName(ctx context.Context, name string) (AutomationHost, error) {
	row := q.db.QueryRowContext(ctx, getAutomationHostByName, name)
	var i AutomationHost
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Machine,
		&i.Os,
		&i.Arch,
		&i.Version,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationHostCredential = `-- name: GetAutomationHostCredential :one
SELECT credential_hash, host_id, host_name, created_at, revoked_at FROM automation_host_credentials WHERE credential_hash = ?
`

func (q *Queries) GetAutomationHostCredential(ctx context.Context, credentialHash string) (AutomationHostCredential, error) {
	row := q.db.QueryRowContext(ctx, getAutomationHostCredential, credentialHash)
	var i AutomationHostCredential
	err := row.Scan(
		&i.CredentialHash,
		&i.HostID,
		&i.HostName,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAutomationHostEnrollmentCode = `-- name: GetAutomationHostEnrollmentCode :one
SELECT code_hash, name, machine, created_at, expires_at FROM automation_host_enrollment_codes WHERE code_hash = ? AND expires_at > ?
`

type GetAutomationHostEnrollmentCodeParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) GetAutomationHostEnrollmentCode(ctx context.Context, arg GetAutomationHostEnrollmentCodeParams) (AutomationHostEnrollmentCode, error) {
	row := q.db.QueryRowContext(ctx, getAutomationHostEnrollmentCode, arg.CodeHash, arg.ExpiresAt)
	var i AutomationHostEnrollmentCode
	err := row.Scan(
		&i.CodeHash,
		&i.Name,
		&i.Machine,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLiveAutomationHostCredential = `-- name: GetLiveAutomationHostCredential :one
SELECT credential_hash, host_id, host_name, created_at, revoked_at FROM automation_host_credentials WHERE host_id = ? AND revoked_at IS NULL LIMIT 1
`

func (q *Queries) GetLiveAutomationHostCredential(ctx context.Context, hostID string) (AutomationHostCredential, error) {
	row := q.db.QueryRowContext(ctx, getLiveAutomationHostCredential, hostID)
	var i AutomationHostCredential
	err := row.Scan(
		&i.CredentialHash,
		&i.HostID,
		&i.HostName,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAutomationHosts = `-- name: ListAutomationHosts :many
SELECT id, name, machine, os, arch, version, last_seen, created_at FROM automation_hosts ORDER BY created_at, id
`

func (q *Queries) ListAutomationHosts(ctx context.Context) ([]AutomationHost, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationHost
	for rows.Next() {
		var i AutomationHost
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Machine,
			&i.Os,
			&i.Arch,
			&i.Version,
			&i.LastSeen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAutomationHostEnrollmentCodes = `-- name: PruneAutomationHostEnrollmentCodes :exec
DELETE FROM automation_host_enrollment_codes WHERE expires_at <= ?
`

func (q *Queries) PruneAutomationHostEnrollmentCodes(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneAutomationHostEnrollmentCodes, expiresAt)
	return err
}

const revokeAutomationHostCredentials = `-- name: RevokeAutomationHostCredentials :exec
UPDATE automation_host_credentials SET revoked_at = ? WHERE host_id = ? AND revoked_at IS NULL
`

type RevokeAutomationHostCredentialsParams struct {
	RevokedAt sql.NullInt64
	HostID    string
}

func (q *Queries) RevokeAutomationHostCredentials(ctx context.Context, arg RevokeAutomationHostCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, revokeAutomationHostCredentials, arg.RevokedAt, arg.HostID)
	return err
}

const touchAutomationHost = `-- name: TouchAutomationHost :execrows
UPDATE automation_hosts SET last_seen = ? WHERE id = ?
`

type TouchAutomationHostParams struct {
	LastSeen int64
	ID       string
}

func (q *Queries) TouchAutomationHost(ctx context.Context, arg TouchAutomationHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchAutomationHost, arg.LastSeen, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
