// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_versions.sql

package sqlcgen

import (
	"context"
)

const countAutomationVersionForAutomation = `-- name: CountAutomationVersionForAutomation :one
SELECT COUNT(*) FROM automation_versions WHERE id = ? AND automation_id = ?
`

type CountAutomationVersionForAutomationParams struct {
	ID           string
	AutomationID string
}

func (q *Queries) CountAutomationVersionForAutomation(ctx context.Context, arg CountAutomationVersionForAutomationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAutomationVersionForAutomation, arg.ID, arg.AutomationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deactivateAutomationVersions = `-- name: DeactivateAutomationVersions :exec
UPDATE automation_versions SET status = ?1 WHERE automation_id = ?2 AND status = ?3
`

type DeactivateAutomationVersionsParams struct {
	NewStatus    string
	AutomationID string
	OldStatus    string
}

func (q *Queries) DeactivateAutomationVersions(ctx context.Context, arg DeactivateAutomationVersionsParams) error {
	_, err := q.db.ExecContext(ctx, deactivateAutomationVersions, arg.NewStatus, arg.AutomationID, arg.OldStatus)
	return err
}

const deletePendingAutomationVersion = `-- name: DeletePendingAutomationVersion :exec
DELETE FROM automation_versions WHERE automation_id = ? AND status = ?
`

type DeletePendingAutomationVersionParams struct {
	AutomationID string
	Status       string
}

func (q *Queries) DeletePendingAutomationVersion(ctx context.Context, arg DeletePendingAutomationVersionParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingAutomationVersion, arg.AutomationID, arg.Status)
	return err
}

const getAutomationVersion = `-- name: GetAutomationVersion :one
SELECT id, automation_id, sequence, code, pusher_id, message, status, created_at FROM automation_versions WHERE id = ? AND automation_id = ?
`

type GetAutomationVersionParams struct {
	ID           string
	AutomationID string
}

func (q *Queries) GetAutomationVersion(ctx context.Context, arg GetAutomationVersionParams) (AutomationVersion, error) {
	row := q.db.QueryRowContext(ctx, getAutomationVersion, arg.ID, arg.AutomationID)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Sequence,
		&i.Code,
		&i.PusherID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationVersionByID = `-- name: GetAutomationVersionByID :one
SELECT id, automation_id, sequence, code, pusher_id, message, status, created_at FROM automation_versions WHERE id = ?
`

func (q *Queries) GetAutomationVersionByID(ctx context.Context, id string) (AutomationVersion, error) {
	row := q.db.QueryRowContext(ctx, getAutomationVersionByID, id)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Sequence,
		&i.Code,
		&i.PusherID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationVersionByStatus = `-- name: GetAutomationVersionByStatus :one
SELECT id, automation_id, sequence, code, pusher_id, message, status, created_at FROM automation_versions WHERE automation_id = ? AND status = ?
`

type GetAutomationVersionByStatusParams struct {
	AutomationID string
	Status       string
}

func (q *Queries) GetAutomationVersionByStatus(ctx context.Context, arg GetAutomationVersionByStatusParams) (AutomationVersion, error) {
	row := q.db.QueryRowContext(ctx, getAutomationVersionByStatus, arg.AutomationID, arg.Status)
	var i AutomationVersion
	err := row.Scan(
		&i.ID,
		&i.AutomationID,
		&i.Sequence,
		&i.Code,
		&i.PusherID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertAutomationVersion = `-- name: InsertAutomationVersion :exec
INSERT INTO automation_versions (id, automation_id, sequence, code, pusher_id, message, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertAutomationVersionParams struct {
	ID           string
	AutomationID string
	Sequence     int64
	Code         []byte
	PusherID     string
	Message      string
	Status       string
	CreatedAt    int64
}

func (q *Queries) InsertAutomationVersion(ctx context.Context, arg InsertAutomationVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertAutomationVersion,
		arg.ID,
		arg.AutomationID,
		arg.Sequence,
		arg.Code,
		arg.PusherID,
		arg.Message,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listAutomationVersionsByAutomation = `-- name: ListAutomationVersionsByAutomation :many
SELECT id, automation_id, sequence, code, pusher_id, message, status, created_at FROM automation_versions WHERE automation_id = ? ORDER BY sequence DESC
`

func (q *Queries) ListAutomationVersionsByAutomation(ctx context.Context, automationID string) ([]AutomationVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAutomationVersionsByAutomation, automationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutomationVersion
	for rows.Next() {
		var i AutomationVersion
		if err := rows.Scan(
			&i.ID,
			&i.AutomationID,
			&i.Sequence,
			&i.Code,
			&i.PusherID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxAutomationVersionSequence = `-- name: MaxAutomationVersionSequence :one
SELECT MAX(sequence) FROM automation_versions WHERE automation_id = ?
`

func (q *Queries) MaxAutomationVersionSequence(ctx context.Context, automationID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxAutomationVersionSequence, automationID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const setAutomationVersionStatus = `-- name: SetAutomationVersionStatus :exec
UPDATE automation_versions SET status = ? WHERE id = ?
`

type SetAutomationVersionStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetAutomationVersionStatus(ctx context.Context, arg SetAutomationVersionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAutomationVersionStatus, arg.Status, arg.ID)
	return err
}
