// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auto_plays.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createAutoPlay = `-- name: CreateAutoPlay :exec
INSERT INTO auto_plays (id, play_id, workspace_id, enabled, moment, moment_stage, conditions, priority, once_within_minutes, run_on, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAutoPlayParams struct {
	ID                string
	PlayID            string
	WorkspaceID       string
	Enabled           int64
	Moment            string
	MomentStage       sql.NullString
	Conditions        string
	Priority          string
	OnceWithinMinutes int64
	RunOn             string
	CreatedBy         string
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) CreateAutoPlay(ctx context.Context, arg CreateAutoPlayParams) error {
	_, err := q.db.ExecContext(ctx, createAutoPlay,
		arg.ID,
		arg.PlayID,
		arg.WorkspaceID,
		arg.Enabled,
		arg.Moment,
		arg.MomentStage,
		arg.Conditions,
		arg.Priority,
		arg.OnceWithinMinutes,
		arg.RunOn,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAutoPlay = `-- name: DeleteAutoPlay :execrows
DELETE FROM auto_plays WHERE id = ?
`

func (q *Queries) DeleteAutoPlay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAutoPlay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAutoPlay = `-- name: GetAutoPlay :one
SELECT id, play_id, workspace_id, enabled, moment, moment_stage, conditions, priority, once_within_minutes, run_on, created_by, created_at, updated_at FROM auto_plays WHERE id = ?
`

func (q *Queries) GetAutoPlay(ctx context.Context, id string) (AutoPlay, error) {
	row := q.db.QueryRowContext(ctx, getAutoPlay, id)
	var i AutoPlay
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.WorkspaceID,
		&i.Enabled,
		&i.Moment,
		&i.MomentStage,
		&i.Conditions,
		&i.Priority,
		&i.OnceWithinMinutes,
		&i.RunOn,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAutoPlayDailyCap = `-- name: GetAutoPlayDailyCap :one
SELECT auto_play_daily_cap FROM workspaces WHERE id = ?
`

func (q *Queries) GetAutoPlayDailyCap(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAutoPlayDailyCap, id)
	var auto_play_daily_cap int64
	err := row.Scan(&auto_play_daily_cap)
	return auto_play_daily_cap, err
}

const listAutoPlaysByPlays = `-- name: ListAutoPlaysByPlays :many
SELECT id, play_id, workspace_id, enabled, moment, moment_stage, conditions, priority, once_within_minutes, run_on, created_by, created_at, updated_at FROM auto_plays WHERE play_id IN (SELECT value FROM json_each(?1)) ORDER BY play_id, created_at, id
`

func (q *Queries) ListAutoPlaysByPlays(ctx context.Context, playIds interface{}) ([]AutoPlay, error) {
	rows, err := q.db.QueryContext(ctx, listAutoPlaysByPlays, playIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AutoPlay
	for rows.Next() {
		var i AutoPlay
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.WorkspaceID,
			&i.Enabled,
			&i.Moment,
			&i.MomentStage,
			&i.Conditions,
			&i.Priority,
			&i.OnceWithinMinutes,
			&i.RunOn,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAutoPlayDailyCap = `-- name: SetAutoPlayDailyCap :execrows
UPDATE workspaces SET auto_play_daily_cap = ? WHERE id = ?
`

type SetAutoPlayDailyCapParams struct {
	AutoPlayDailyCap int64
	ID               string
}

func (q *Queries) SetAutoPlayDailyCap(ctx context.Context, arg SetAutoPlayDailyCapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAutoPlayDailyCap, arg.AutoPlayDailyCap, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateAutoPlay = `-- name: UpdateAutoPlay :execrows
UPDATE auto_plays SET enabled = ?, moment = ?, moment_stage = ?, conditions = ?, priority = ?, once_within_minutes = ?, run_on = ?, updated_at = ?
WHERE id = ?
`

type UpdateAutoPlayParams struct {
	Enabled           int64
	Moment            string
	MomentStage       sql.NullString
	Conditions        string
	Priority          string
	OnceWithinMinutes int64
	RunOn             string
	UpdatedAt         int64
	ID                string
}

func (q *Queries) UpdateAutoPlay(ctx context.Context, arg UpdateAutoPlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAutoPlay,
		arg.Enabled,
		arg.Moment,
		arg.MomentStage,
		arg.Conditions,
		arg.Priority,
		arg.OnceWithinMinutes,
		arg.RunOn,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
