// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: botwebhooks.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createBotwebhook = `-- name: CreateBotwebhook :exec
INSERT INTO botwebhooks (id, conversation_id, name, avatar, token, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateBotwebhookParams struct {
	ID             string
	ConversationID string
	Name           string
	Avatar         string
	Token          string
	CreatedBy      string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateBotwebhook(ctx context.Context, arg CreateBotwebhookParams) error {
	_, err := q.db.ExecContext(ctx, createBotwebhook,
		arg.ID,
		arg.ConversationID,
		arg.Name,
		arg.Avatar,
		arg.Token,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getBotwebhook = `-- name: GetBotwebhook :one
SELECT id, conversation_id, name, avatar, token, created_by, created_at, updated_at, last_post_at, post_count, deleted_at, deleted_by FROM botwebhooks WHERE id = ?
`

func (q *Queries) GetBotwebhook(ctx context.Context, id string) (Botwebhook, error) {
	row := q.db.QueryRowContext(ctx, getBotwebhook, id)
	var i Botwebhook
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Name,
		&i.Avatar,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastPostAt,
		&i.PostCount,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listBotwebhooks = `-- name: ListBotwebhooks :many
SELECT id, conversation_id, name, avatar, token, created_by, created_at, updated_at, last_post_at, post_count, deleted_at, deleted_by FROM botwebhooks WHERE conversation_id = ? AND (deleted_at IS NOT NULL) = ?2 ORDER BY created_at, id
`

type ListBotwebhooksParams struct {
	ConversationID string
	Deleted        sql.NullInt64
}

func (q *Queries) ListBotwebhooks(ctx context.Context, arg ListBotwebhooksParams) ([]Botwebhook, error) {
	rows, err := q.db.QueryContext(ctx, listBotwebhooks, arg.ConversationID, arg.Deleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Botwebhook
	for rows.Next() {
		var i Botwebhook
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Name,
			&i.Avatar,
			&i.Token,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastPostAt,
			&i.PostCount,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotwebhook = `-- name: UpdateBotwebhook :execrows
UPDATE botwebhooks SET name = ?, avatar = ?, token = ?, updated_at = ?, deleted_at = ?, deleted_by = ? WHERE id = ?
`

type UpdateBotwebhookParams struct {
	Name      string
	Avatar    string
	Token     string
	UpdatedAt int64
	DeletedAt sql.NullInt64
	DeletedBy string
	ID        string
}

func (q *Queries) UpdateBotwebhook(ctx context.Context, arg UpdateBotwebhookParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateBotwebhook,
		arg.Name,
		arg.Avatar,
		arg.Token,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.DeletedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
