// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countCategoryTickets = `-- name: CountCategoryTickets :one
SELECT COUNT(*) FROM tickets WHERE category_id = ?
`

func (q *Queries) CountCategoryTickets(ctx context.Context, categoryID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategoryTickets, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO categories (id, project_id, name, position, color, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCategoryParams struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	Color     string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCategory = `-- name: GetCategory :one
SELECT id, project_id, name, position, created_at, updated_at, color FROM categories WHERE id = ?
`

func (q *Queries) GetCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Color,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, project_id, name, position, created_at, updated_at, color FROM categories ORDER BY project_id, position, id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByProject = `-- name: ListCategoriesByProject :many
SELECT id, project_id, name, position, created_at, updated_at, color FROM categories WHERE project_id = ? ORDER BY position, id
`

func (q *Queries) ListCategoriesByProject(ctx context.Context, projectID string) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderCategoryPosition = `-- name: ReorderCategoryPosition :execrows
UPDATE categories SET position = ?, updated_at = ? WHERE id = ? AND project_id = ?
`

type ReorderCategoryPositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
	ProjectID string
}

func (q *Queries) ReorderCategoryPosition(ctx context.Context, arg ReorderCategoryPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reorderCategoryPosition,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCategory = `-- name: UpdateCategory :execrows
UPDATE categories SET name = ?, color = ?, updated_at = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name      string
	Color     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Color,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
