// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, workspace_id, kind, name, ticket_id, doc_id, project_id, parent_message_id, created_by, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateConversationParams struct {
	ID              string
	WorkspaceID     string
	Kind            string
	Name            string
	TicketID        sql.NullString
	DocID           sql.NullString
	ProjectID       sql.NullString
	ParentMessageID string
	CreatedBy       string
	CreatedAt       int64
	UpdatedAt       int64
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation,
		arg.ID,
		arg.WorkspaceID,
		arg.Kind,
		arg.Name,
		arg.TicketID,
		arg.DocID,
		arg.ProjectID,
		arg.ParentMessageID,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, conversation_id, author_id, author_kind, body, mentions, attachment_id, edited_at, deleted_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, NULL, NULL, ?, ?)
`

type CreateMessageParams struct {
	ID             string
	ConversationID string
	AuthorID       string
	AuthorKind     string
	Body           string
	Mentions       string
	AttachmentID   sql.NullString
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.AuthorID,
		arg.AuthorKind,
		arg.Body,
		arg.Mentions,
		arg.AttachmentID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMessage = `-- name: DeleteMessage :execrows
UPDATE messages SET body = '', mentions = '[]', deleted_at = ?, updated_at = ? WHERE id = ?
`

type DeleteMessageParams struct {
	DeletedAt sql.NullInt64
	UpdatedAt int64
	ID        string
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMessage, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getChannelByName = `-- name: GetChannelByName :one
SELECT id, workspace_id, kind, name, ticket_id, parent_message_id, created_by, created_at, updated_at, agent_thread_id, agent_synced_at, doc_id, project_id FROM conversations WHERE workspace_id = ? AND kind = 'channel' AND name = ?
`

type GetChannelByNameParams struct {
	WorkspaceID string
	Name        string
}

func (q *Queries) GetChannelByName(ctx context.Context, arg GetChannelByNameParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getChannelByName, arg.WorkspaceID, arg.Name)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.TicketID,
		&i.ParentMessageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentThreadID,
		&i.AgentSyncedAt,
		&i.DocID,
		&i.ProjectID,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, workspace_id, kind, name, ticket_id, parent_message_id, created_by, created_at, updated_at, agent_thread_id, agent_synced_at, doc_id, project_id FROM conversations WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.TicketID,
		&i.ParentMessageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentThreadID,
		&i.AgentSyncedAt,
		&i.DocID,
		&i.ProjectID,
	)
	return i, err
}

const getDocThread = `-- name: GetDocThread :one
SELECT id, workspace_id, kind, name, ticket_id, parent_message_id, created_by, created_at, updated_at, agent_thread_id, agent_synced_at, doc_id, project_id FROM conversations WHERE doc_id = ?
`

func (q *Queries) GetDocThread(ctx context.Context, docID sql.NullString) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getDocThread, docID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.TicketID,
		&i.ParentMessageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentThreadID,
		&i.AgentSyncedAt,
		&i.DocID,
		&i.ProjectID,
	)
	return i, err
}

const getInterviewThread = `-- name: GetInterviewThread :one
SELECT id, workspace_id, kind, name, ticket_id, parent_message_id, created_by, created_at, updated_at, agent_thread_id, agent_synced_at, doc_id, project_id FROM conversations WHERE project_id = ?
`

func (q *Queries) GetInterviewThread(ctx context.Context, projectID sql.NullString) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getInterviewThread, projectID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.TicketID,
		&i.ParentMessageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentThreadID,
		&i.AgentSyncedAt,
		&i.DocID,
		&i.ProjectID,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, author_id, body, mentions, attachment_id, edited_at, deleted_at, created_at, updated_at, author_kind FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorID,
		&i.Body,
		&i.Mentions,
		&i.AttachmentID,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorKind,
	)
	return i, err
}

const getTicketThread = `-- name: GetTicketThread :one
SELECT id, workspace_id, kind, name, ticket_id, parent_message_id, created_by, created_at, updated_at, agent_thread_id, agent_synced_at, doc_id, project_id FROM conversations WHERE ticket_id = ?
`

func (q *Queries) GetTicketThread(ctx context.Context, ticketID sql.NullString) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getTicketThread, ticketID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Kind,
		&i.Name,
		&i.TicketID,
		&i.ParentMessageID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AgentThreadID,
		&i.AgentSyncedAt,
		&i.DocID,
		&i.ProjectID,
	)
	return i, err
}

const insertConversationParticipant = `-- name: InsertConversationParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id, created_at) VALUES (?, ?, ?)
    ON CONFLICT(conversation_id, user_id) DO NOTHING
`

type InsertConversationParticipantParams struct {
	ConversationID string
	UserID         string
	CreatedAt      int64
}

func (q *Queries) InsertConversationParticipant(ctx context.Context, arg InsertConversationParticipantParams) error {
	_, err := q.db.ExecContext(ctx, insertConversationParticipant, arg.ConversationID, arg.UserID, arg.CreatedAt)
	return err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT DISTINCT c.id, c.workspace_id, c.kind, c.name, c.ticket_id, c.parent_message_id, c.created_by, c.created_at, c.updated_at, c.agent_thread_id, c.agent_synced_at, c.doc_id, c.project_id FROM conversations c
LEFT JOIN conversation_participants p ON p.conversation_id = c.id AND p.user_id = ?
WHERE c.workspace_id = ? AND (c.kind IN ('channel', 'voice_channel', 'doc_thread') OR p.user_id IS NOT NULL)
ORDER BY c.created_at
`

type ListConversationsForUserParams struct {
	UserID      string
	WorkspaceID string
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Kind,
			&i.Name,
			&i.TicketID,
			&i.ParentMessageID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AgentThreadID,
			&i.AgentSyncedAt,
			&i.DocID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, author_id, body, mentions, attachment_id, edited_at, deleted_at, created_at, updated_at, author_kind FROM messages WHERE conversation_id = ? ORDER BY created_at LIMIT ?
`

type ListMessagesParams struct {
	ConversationID string
	Limit          int64
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorID,
			&i.Body,
			&i.Mentions,
			&i.AttachmentID,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesSince = `-- name: ListMessagesSince :many
SELECT id, conversation_id, author_id, body, mentions, attachment_id, edited_at, deleted_at, created_at, updated_at, author_kind FROM messages WHERE conversation_id = ? AND deleted_at IS NULL AND created_at > ? ORDER BY created_at
`

type ListMessagesSinceParams struct {
	ConversationID string
	CreatedAt      int64
}

func (q *Queries) ListMessagesSince(ctx context.Context, arg ListMessagesSinceParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesSince, arg.ConversationID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.AuthorID,
			&i.Body,
			&i.Mentions,
			&i.AttachmentID,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantsByConversationIDs = `-- name: ListParticipantsByConversationIDs :many
SELECT conversation_id, user_id FROM conversation_participants WHERE conversation_id IN (/*SLICE:ids*/?)
`

type ListParticipantsByConversationIDsRow struct {
	ConversationID string
	UserID         string
}

func (q *Queries) ListParticipantsByConversationIDs(ctx context.Context, ids []string) ([]ListParticipantsByConversationIDsRow, error) {
	query := listParticipantsByConversationIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantsByConversationIDsRow
	for rows.Next() {
		var i ListParticipantsByConversationIDsRow
		if err := rows.Scan(&i.ConversationID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketIDsWithThreads = `-- name: ListTicketIDsWithThreads :many
SELECT ticket_id FROM conversations WHERE ticket_id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListTicketIDsWithThreads(ctx context.Context, ids []sql.NullString) ([]sql.NullString, error) {
	query := listTicketIDsWithThreads
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var ticket_id sql.NullString
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
INSERT INTO conversation_unread_state (user_id, conversation_id, last_read_at) VALUES (?, ?, ?)
    ON CONFLICT(user_id, conversation_id) DO UPDATE SET last_read_at = excluded.last_read_at
`

type MarkReadParams struct {
	UserID         string
	ConversationID string
	LastReadAt     int64
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.ExecContext(ctx, markRead, arg.UserID, arg.ConversationID, arg.LastReadAt)
	return err
}

const setAgentSyncedAt = `-- name: SetAgentSyncedAt :execrows
UPDATE conversations SET agent_synced_at = ? WHERE id = ?
`

type SetAgentSyncedAtParams struct {
	AgentSyncedAt int64
	ID            string
}

func (q *Queries) SetAgentSyncedAt(ctx context.Context, arg SetAgentSyncedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentSyncedAt, arg.AgentSyncedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentThread = `-- name: SetAgentThread :execrows
UPDATE conversations SET agent_thread_id = ? WHERE id = ?
`

type SetAgentThreadParams struct {
	AgentThreadID string
	ID            string
}

func (q *Queries) SetAgentThread(ctx context.Context, arg SetAgentThreadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentThread, arg.AgentThreadID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unreadCounts = `-- name: UnreadCounts :many
SELECT c.id, c.kind, c.doc_id, COUNT(m.id) AS count FROM conversations c
LEFT JOIN conversation_participants p ON p.conversation_id = c.id AND p.user_id = ?1
LEFT JOIN conversation_unread_state u ON u.conversation_id = c.id AND u.user_id = ?1
LEFT JOIN messages m ON m.conversation_id = c.id AND m.deleted_at IS NULL AND m.author_id != ?1 AND m.created_at > COALESCE(u.last_read_at, 0)
WHERE c.workspace_id = ?2 AND (c.kind IN ('channel', 'voice_channel', 'doc_thread') OR p.user_id IS NOT NULL)
GROUP BY c.id
`

type UnreadCountsParams struct {
	UserID      string
	WorkspaceID string
}

type UnreadCountsRow struct {
	ID    string
	Kind  string
	DocID sql.NullString
	Count int64
}

func (q *Queries) UnreadCounts(ctx context.Context, arg UnreadCountsParams) ([]UnreadCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, unreadCounts, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnreadCountsRow
	for rows.Next() {
		var i UnreadCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DocID,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :execrows
UPDATE messages SET body = ?, mentions = ?, edited_at = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageParams struct {
	Body      string
	Mentions  string
	EditedAt  sql.NullInt64
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMessage,
		arg.Body,
		arg.Mentions,
		arg.EditedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
