// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: code_reviews.sql

package sqlcgen

import (
	"context"
)

const createCodeReview = `-- name: CreateCodeReview :exec
INSERT INTO code_reviews (id, pr_number, repo, status, reviewer, created_at) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(repo, pr_number) DO NOTHING
`

type CreateCodeReviewParams struct {
	ID        string
	PrNumber  int64
	Repo      string
	Status    string
	Reviewer  string
	CreatedAt int64
}

func (q *Queries) CreateCodeReview(ctx context.Context, arg CreateCodeReviewParams) error {
	_, err := q.db.ExecContext(ctx, createCodeReview,
		arg.ID,
		arg.PrNumber,
		arg.Repo,
		arg.Status,
		arg.Reviewer,
		arg.CreatedAt,
	)
	return err
}

const getCodeReview = `-- name: GetCodeReview :one
SELECT id, pr_number, repo, status, reviewer, created_at FROM code_reviews WHERE id = ?
`

func (q *Queries) GetCodeReview(ctx context.Context, id string) (CodeReview, error) {
	row := q.db.QueryRowContext(ctx, getCodeReview, id)
	var i CodeReview
	err := row.Scan(
		&i.ID,
		&i.PrNumber,
		&i.Repo,
		&i.Status,
		&i.Reviewer,
		&i.CreatedAt,
	)
	return i, err
}

const listCodeReviewsByPR = `-- name: ListCodeReviewsByPR :many
SELECT id, pr_number, repo, status, reviewer, created_at FROM code_reviews WHERE repo = ? AND pr_number = ? ORDER BY created_at
`

type ListCodeReviewsByPRParams struct {
	Repo     string
	PrNumber int64
}

func (q *Queries) ListCodeReviewsByPR(ctx context.Context, arg ListCodeReviewsByPRParams) ([]CodeReview, error) {
	rows, err := q.db.QueryContext(ctx, listCodeReviewsByPR, arg.Repo, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeReview
	for rows.Next() {
		var i CodeReview
		if err := rows.Scan(
			&i.ID,
			&i.PrNumber,
			&i.Repo,
			&i.Status,
			&i.Reviewer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCodeReviewsByTicket = `-- name: ListCodeReviewsByTicket :many
SELECT r.id, r.pr_number, r.repo, r.status, r.reviewer, r.created_at FROM code_reviews r
JOIN ticket_pr_links l ON l.pr_owner || '/' || l.pr_repo = r.repo AND l.pr_number = r.pr_number
WHERE l.ticket_id = ? ORDER BY r.created_at
`

func (q *Queries) ListCodeReviewsByTicket(ctx context.Context, ticketID string) ([]CodeReview, error) {
	rows, err := q.db.QueryContext(ctx, listCodeReviewsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CodeReview
	for rows.Next() {
		var i CodeReview
		if err := rows.Scan(
			&i.ID,
			&i.PrNumber,
			&i.Repo,
			&i.Status,
			&i.Reviewer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCodeReviewStatus = `-- name: UpdateCodeReviewStatus :execrows
UPDATE code_reviews SET status = ?, reviewer = ? WHERE id = ?
`

type UpdateCodeReviewStatusParams struct {
	Status   string
	Reviewer string
	ID       string
}

func (q *Queries) UpdateCodeReviewStatus(ctx context.Context, arg UpdateCodeReviewStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCodeReviewStatus, arg.Status, arg.Reviewer, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
