// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collab.sql

package sqlcgen

import (
	"context"
)

const appendCollabUpdate = `-- name: AppendCollabUpdate :execlastid
INSERT INTO collab_updates (doc_id, kind, actor_id, payload, created_at) VALUES (?, ?, ?, ?, ?)
`

type AppendCollabUpdateParams struct {
	DocID     string
	Kind      string
	ActorID   string
	Payload   string
	CreatedAt int64
}

func (q *Queries) AppendCollabUpdate(ctx context.Context, arg AppendCollabUpdateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendCollabUpdate,
		arg.DocID,
		arg.Kind,
		arg.ActorID,
		arg.Payload,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getCollabSessionSeq = `-- name: GetCollabSessionSeq :one
SELECT last_seq FROM collab_sessions WHERE doc_id = ?
`

func (q *Queries) GetCollabSessionSeq(ctx context.Context, docID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCollabSessionSeq, docID)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const getLatestCollabSnapshot = `-- name: GetLatestCollabSnapshot :one
SELECT doc_id, seq, kind, actor_id, payload, created_at FROM collab_updates WHERE doc_id = ? AND kind = 'snapshot' ORDER BY seq DESC LIMIT 1
`

func (q *Queries) GetLatestCollabSnapshot(ctx context.Context, docID string) (CollabUpdate, error) {
	row := q.db.QueryRowContext(ctx, getLatestCollabSnapshot, docID)
	var i CollabUpdate
	err := row.Scan(
		&i.DocID,
		&i.Seq,
		&i.Kind,
		&i.ActorID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listCollabIncrementsAfter = `-- name: ListCollabIncrementsAfter :many
SELECT doc_id, seq, kind, actor_id, payload, created_at FROM collab_updates WHERE doc_id = ? AND kind = 'update' AND seq > ? ORDER BY seq
`

type ListCollabIncrementsAfterParams struct {
	DocID string
	Seq   int64
}

func (q *Queries) ListCollabIncrementsAfter(ctx context.Context, arg ListCollabIncrementsAfterParams) ([]CollabUpdate, error) {
	rows, err := q.db.QueryContext(ctx, listCollabIncrementsAfter, arg.DocID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollabUpdate
	for rows.Next() {
		var i CollabUpdate
		if err := rows.Scan(
			&i.DocID,
			&i.Seq,
			&i.Kind,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchCollabSession = `-- name: TouchCollabSession :exec
INSERT INTO collab_sessions (doc_id, last_seq, last_commit_at) VALUES (?, ?, ?)
ON CONFLICT(doc_id) DO UPDATE SET last_seq = excluded.last_seq
`

type TouchCollabSessionParams struct {
	DocID        string
	LastSeq      int64
	LastCommitAt int64
}

func (q *Queries) TouchCollabSession(ctx context.Context, arg TouchCollabSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchCollabSession, arg.DocID, arg.LastSeq, arg.LastCommitAt)
	return err
}

const trimCollabUpdates = `-- name: TrimCollabUpdates :exec
DELETE FROM collab_updates WHERE doc_id = ? AND kind = 'update' AND seq <= ?
`

type TrimCollabUpdatesParams struct {
	DocID string
	Seq   int64
}

func (q *Queries) TrimCollabUpdates(ctx context.Context, arg TrimCollabUpdatesParams) error {
	_, err := q.db.ExecContext(ctx, trimCollabUpdates, arg.DocID, arg.Seq)
	return err
}
