// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connector_appconfig.sql

package sqlcgen

import (
	"context"
)

const getConnectorAppConfig = `-- name: GetConnectorAppConfig :one
SELECT connector_id, client_id, client_secret, base_url, app_slug FROM connector_app_config WHERE connector_id = ?
`

func (q *Queries) GetConnectorAppConfig(ctx context.Context, connectorID string) (ConnectorAppConfig, error) {
	row := q.db.QueryRowContext(ctx, getConnectorAppConfig, connectorID)
	var i ConnectorAppConfig
	err := row.Scan(
		&i.ConnectorID,
		&i.ClientID,
		&i.ClientSecret,
		&i.BaseUrl,
		&i.AppSlug,
	)
	return i, err
}

const setConnectorAppConfig = `-- name: SetConnectorAppConfig :exec
INSERT INTO connector_app_config (connector_id, client_id, client_secret, base_url, app_slug)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(connector_id) DO UPDATE SET
  client_id = excluded.client_id, client_secret = excluded.client_secret,
  base_url = excluded.base_url, app_slug = excluded.app_slug
`

type SetConnectorAppConfigParams struct {
	ConnectorID  string
	ClientID     string
	ClientSecret string
	BaseUrl      string
	AppSlug      string
}

func (q *Queries) SetConnectorAppConfig(ctx context.Context, arg SetConnectorAppConfigParams) error {
	_, err := q.db.ExecContext(ctx, setConnectorAppConfig,
		arg.ConnectorID,
		arg.ClientID,
		arg.ClientSecret,
		arg.BaseUrl,
		arg.AppSlug,
	)
	return err
}
