// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package sqlcgen

import (
	"context"
)

const deleteConnectorCredentials = `-- name: DeleteConnectorCredentials :exec
DELETE FROM connector_credentials WHERE connector_id = ?
`

func (q *Queries) DeleteConnectorCredentials(ctx context.Context, connectorID string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectorCredentials, connectorID)
	return err
}

const getConnectorCredentials = `-- name: GetConnectorCredentials :one
SELECT connector_id, access_token, refresh_token, expires_at, connected_by, connected_at, manual_fields FROM connector_credentials WHERE connector_id = ?
`

func (q *Queries) GetConnectorCredentials(ctx context.Context, connectorID string) (ConnectorCredential, error) {
	row := q.db.QueryRowContext(ctx, getConnectorCredentials, connectorID)
	var i ConnectorCredential
	err := row.Scan(
		&i.ConnectorID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.ConnectedBy,
		&i.ConnectedAt,
		&i.ManualFields,
	)
	return i, err
}

const saveConnectorCredentials = `-- name: SaveConnectorCredentials :exec
INSERT INTO connector_credentials (connector_id, access_token, refresh_token, expires_at, connected_by, connected_at, manual_fields)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(connector_id) DO UPDATE SET
  access_token = excluded.access_token, refresh_token = excluded.refresh_token,
  expires_at = excluded.expires_at, connected_by = excluded.connected_by,
  connected_at = excluded.connected_at, manual_fields = excluded.manual_fields
`

type SaveConnectorCredentialsParams struct {
	ConnectorID  string
	AccessToken  string
	RefreshToken string
	ExpiresAt    int64
	ConnectedBy  string
	ConnectedAt  int64
	ManualFields string
}

func (q *Queries) SaveConnectorCredentials(ctx context.Context, arg SaveConnectorCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, saveConnectorCredentials,
		arg.ConnectorID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.ConnectedBy,
		arg.ConnectedAt,
		arg.ManualFields,
	)
	return err
}
