// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connect_codes.sql

package sqlcgen

import (
	"context"
)

const createConnectCode = `-- name: CreateConnectCode :exec
INSERT INTO connect_codes (code_hash, user_id, created_at, expires_at) VALUES (?, ?, ?, ?)
`

type CreateConnectCodeParams struct {
	CodeHash  string
	UserID    string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateConnectCode(ctx context.Context, arg CreateConnectCodeParams) error {
	_, err := q.db.ExecContext(ctx, createConnectCode,
		arg.CodeHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteConnectCode = `-- name: DeleteConnectCode :exec
DELETE FROM connect_codes WHERE code_hash = ?
`

func (q *Queries) DeleteConnectCode(ctx context.Context, codeHash string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectCode, codeHash)
	return err
}

const deleteConnectCodesByUser = `-- name: DeleteConnectCodesByUser :exec
DELETE FROM connect_codes WHERE user_id = ?
`

func (q *Queries) DeleteConnectCodesByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteConnectCodesByUser, userID)
	return err
}

const getLiveConnectCodeUser = `-- name: GetLiveConnectCodeUser :one
SELECT user_id FROM connect_codes WHERE code_hash = ? AND expires_at > ?
`

type GetLiveConnectCodeUserParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) GetLiveConnectCodeUser(ctx context.Context, arg GetLiveConnectCodeUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLiveConnectCodeUser, arg.CodeHash, arg.ExpiresAt)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
