// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploy_log_lines.sql

package sqlcgen

import (
	"context"
)

const insertDeployLogLine = `-- name: InsertDeployLogLine :exec
INSERT INTO deploy_log_lines (deploy_id, ts, phase, line) VALUES (?, ?, ?, ?)
`

type InsertDeployLogLineParams struct {
	DeployID string
	Ts       int64
	Phase    string
	Line     string
}

func (q *Queries) InsertDeployLogLine(ctx context.Context, arg InsertDeployLogLineParams) error {
	_, err := q.db.ExecContext(ctx, insertDeployLogLine,
		arg.DeployID,
		arg.Ts,
		arg.Phase,
		arg.Line,
	)
	return err
}

const listDeployLogLines = `-- name: ListDeployLogLines :many
SELECT seq, ts, phase, line FROM deploy_log_lines WHERE deploy_id = ? ORDER BY ts, seq
`

type ListDeployLogLinesRow struct {
	Seq   int64
	Ts    int64
	Phase string
	Line  string
}

func (q *Queries) ListDeployLogLines(ctx context.Context, deployID string) ([]ListDeployLogLinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeployLogLines, deployID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeployLogLinesRow
	for rows.Next() {
		var i ListDeployLogLinesRow
		if err := rows.Scan(
			&i.Seq,
			&i.Ts,
			&i.Phase,
			&i.Line,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
