// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendDeployLog = `-- name: AppendDeployLog :execrows
UPDATE deploys SET log = log || ?, updated_at = ? WHERE id = ?
`

type AppendDeployLogParams struct {
	Log       string
	UpdatedAt int64
	ID        string
}

func (q *Queries) AppendDeployLog(ctx context.Context, arg AppendDeployLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, appendDeployLog, arg.Log, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveDeploys = `-- name: CountActiveDeploys :one
SELECT COUNT(*) FROM deploys WHERE stack_id = ? AND status IN ('pending', 'running')
`

func (q *Queries) CountActiveDeploys(ctx context.Context, stackID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveDeploys, stackID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeploy = `-- name: CreateDeploy :exec
INSERT INTO deploys (id, kind, stack_id, service_id, service, target, image, status, strategy, log,
    triggered_by, rule_id, rule_name, ticket_id, pr_number, created_at, updated_at, address)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDeployParams struct {
	ID          string
	Kind        string
	StackID     sql.NullString
	ServiceID   string
	Service     string
	Target      string
	Image       string
	Status      string
	Strategy    string
	Log         string
	TriggeredBy string
	RuleID      string
	RuleName    string
	TicketID    string
	PrNumber    int64
	CreatedAt   int64
	UpdatedAt   int64
	Address     string
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) error {
	_, err := q.db.ExecContext(ctx, createDeploy,
		arg.ID,
		arg.Kind,
		arg.StackID,
		arg.ServiceID,
		arg.Service,
		arg.Target,
		arg.Image,
		arg.Status,
		arg.Strategy,
		arg.Log,
		arg.TriggeredBy,
		arg.RuleID,
		arg.RuleName,
		arg.TicketID,
		arg.PrNumber,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Address,
	)
	return err
}

const getDeploy = `-- name: GetDeploy :one
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys WHERE id = ?
`

func (q *Queries) GetDeploy(ctx context.Context, id string) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, getDeploy, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Target,
		&i.Image,
		&i.Status,
		&i.Strategy,
		&i.Log,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StackID,
		&i.ServiceID,
		&i.TriggeredBy,
		&i.RuleID,
		&i.RuleName,
		&i.TicketID,
		&i.PrNumber,
		&i.Kind,
		&i.Address,
	)
	return i, err
}

const lastHealthyDeploy = `-- name: LastHealthyDeploy :one
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys WHERE stack_id = ? AND status = 'healthy' ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LastHealthyDeploy(ctx context.Context, stackID sql.NullString) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, lastHealthyDeploy, stackID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Target,
		&i.Image,
		&i.Status,
		&i.Strategy,
		&i.Log,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StackID,
		&i.ServiceID,
		&i.TriggeredBy,
		&i.RuleID,
		&i.RuleName,
		&i.TicketID,
		&i.PrNumber,
		&i.Kind,
		&i.Address,
	)
	return i, err
}

const listDeploys = `-- name: ListDeploys :many
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys ORDER BY created_at
`

func (q *Queries) ListDeploys(ctx context.Context) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Target,
			&i.Image,
			&i.Status,
			&i.Strategy,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StackID,
			&i.ServiceID,
			&i.TriggeredBy,
			&i.RuleID,
			&i.RuleName,
			&i.TicketID,
			&i.PrNumber,
			&i.Kind,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploysByService = `-- name: ListDeploysByService :many
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys WHERE service = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploysByService(ctx context.Context, service string) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploysByService, service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Target,
			&i.Image,
			&i.Status,
			&i.Strategy,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StackID,
			&i.ServiceID,
			&i.TriggeredBy,
			&i.RuleID,
			&i.RuleName,
			&i.TicketID,
			&i.PrNumber,
			&i.Kind,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploysByStackID = `-- name: ListDeploysByStackID :many
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys WHERE stack_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploysByStackID(ctx context.Context, stackID sql.NullString) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploysByStackID, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Target,
			&i.Image,
			&i.Status,
			&i.Strategy,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StackID,
			&i.ServiceID,
			&i.TriggeredBy,
			&i.RuleID,
			&i.RuleName,
			&i.TicketID,
			&i.PrNumber,
			&i.Kind,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploysByStatus = `-- name: ListDeploysByStatus :many
SELECT id, service, target, image, status, strategy, log, created_at, updated_at, stack_id, service_id, triggered_by, rule_id, rule_name, ticket_id, pr_number, kind, address FROM deploys WHERE status = ? ORDER BY created_at DESC
`

func (q *Queries) ListDeploysByStatus(ctx context.Context, status string) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, listDeploysByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deploy
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Target,
			&i.Image,
			&i.Status,
			&i.Strategy,
			&i.Log,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StackID,
			&i.ServiceID,
			&i.TriggeredBy,
			&i.RuleID,
			&i.RuleName,
			&i.TicketID,
			&i.PrNumber,
			&i.Kind,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDeployAddress = `-- name: SetDeployAddress :execrows
UPDATE deploys SET address = ?, updated_at = ? WHERE id = ?
`

type SetDeployAddressParams struct {
	Address   string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetDeployAddress(ctx context.Context, arg SetDeployAddressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDeployAddress, arg.Address, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDeployStatus = `-- name: UpdateDeployStatus :execrows
UPDATE deploys SET status = ?, updated_at = ? WHERE id = ?
`

type UpdateDeployStatusParams struct {
	Status    string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateDeployStatus(ctx context.Context, arg UpdateDeployStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDeployStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
