// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dns.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteAccessServiceToken = `-- name: DeleteAccessServiceToken :execrows
DELETE FROM dns_access_service_token WHERE id = 1
`

func (q *Queries) DeleteAccessServiceToken(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessServiceToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExposure = `-- name: DeleteExposure :execrows
DELETE FROM dns_exposures WHERE id = ?
`

func (q *Queries) DeleteExposure(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExposure, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGateway = `-- name: DeleteGateway :execrows
DELETE FROM dns_gateways WHERE id = ?
`

func (q *Queries) DeleteGateway(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGateway, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteServiceHostname = `-- name: DeleteServiceHostname :execrows
DELETE FROM dns_service_hostnames WHERE service = ?
`

func (q *Queries) DeleteServiceHostname(ctx context.Context, service string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteServiceHostname, service)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTunnel = `-- name: DeleteTunnel :execrows
DELETE FROM dns_tunnels WHERE id = ?
`

func (q *Queries) DeleteTunnel(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTunnel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccessServiceToken = `-- name: GetAccessServiceToken :one
SELECT id, token_id, client_id, client_secret, created_at, updated_at FROM dns_access_service_token WHERE id = 1
`

func (q *Queries) GetAccessServiceToken(ctx context.Context) (DnsAccessServiceToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessServiceToken)
	var i DnsAccessServiceToken
	err := row.Scan(
		&i.ID,
		&i.TokenID,
		&i.ClientID,
		&i.ClientSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExposure = `-- name: GetExposure :one
SELECT id, gateway_id, hostname, service, port, zone_id, zone, record_id, created_at, updated_at, service_id FROM dns_exposures WHERE id = ?
`

func (q *Queries) GetExposure(ctx context.Context, id string) (DnsExposure, error) {
	row := q.db.QueryRowContext(ctx, getExposure, id)
	var i DnsExposure
	err := row.Scan(
		&i.ID,
		&i.GatewayID,
		&i.Hostname,
		&i.Service,
		&i.Port,
		&i.ZoneID,
		&i.Zone,
		&i.RecordID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServiceID,
	)
	return i, err
}

const getGateway = `-- name: GetGateway :one
SELECT id, kind, docker_network, service_id, service_name, tunnel_id, zone_id, zone, server_address, created_at, updated_at, networks, machine FROM dns_gateways WHERE id = ?
`

func (q *Queries) GetGateway(ctx context.Context, id string) (DnsGateway, error) {
	row := q.db.QueryRowContext(ctx, getGateway, id)
	var i DnsGateway
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DockerNetwork,
		&i.ServiceID,
		&i.ServiceName,
		&i.TunnelID,
		&i.ZoneID,
		&i.Zone,
		&i.ServerAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Networks,
		&i.Machine,
	)
	return i, err
}

const getGatewayByNetwork = `-- name: GetGatewayByNetwork :one
SELECT id, kind, docker_network, service_id, service_name, tunnel_id, zone_id, zone, server_address, created_at, updated_at, networks, machine FROM dns_gateways WHERE docker_network = ?
`

func (q *Queries) GetGatewayByNetwork(ctx context.Context, dockerNetwork string) (DnsGateway, error) {
	row := q.db.QueryRowContext(ctx, getGatewayByNetwork, dockerNetwork)
	var i DnsGateway
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DockerNetwork,
		&i.ServiceID,
		&i.ServiceName,
		&i.TunnelID,
		&i.ZoneID,
		&i.Zone,
		&i.ServerAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Networks,
		&i.Machine,
	)
	return i, err
}

const getServiceHostname = `-- name: GetServiceHostname :one
SELECT service, hostname, zone_id, zone, record_id, type, content, created_at FROM dns_service_hostnames WHERE service = ?
`

func (q *Queries) GetServiceHostname(ctx context.Context, service string) (DnsServiceHostname, error) {
	row := q.db.QueryRowContext(ctx, getServiceHostname, service)
	var i DnsServiceHostname
	err := row.Scan(
		&i.Service,
		&i.Hostname,
		&i.ZoneID,
		&i.Zone,
		&i.RecordID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getTunnel = `-- name: GetTunnel :one
SELECT id, name, account_id, status, hostname, zone_id, zone, record_id, service, agent_service_id, token, created_at, updated_at FROM dns_tunnels WHERE id = ?
`

func (q *Queries) GetTunnel(ctx context.Context, id string) (DnsTunnel, error) {
	row := q.db.QueryRowContext(ctx, getTunnel, id)
	var i DnsTunnel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.Status,
		&i.Hostname,
		&i.ZoneID,
		&i.Zone,
		&i.RecordID,
		&i.Service,
		&i.AgentServiceID,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExposures = `-- name: ListExposures :many
SELECT id, gateway_id, hostname, service, port, zone_id, zone, record_id, created_at, updated_at, service_id FROM dns_exposures ORDER BY created_at
`

func (q *Queries) ListExposures(ctx context.Context) ([]DnsExposure, error) {
	rows, err := q.db.QueryContext(ctx, listExposures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsExposure
	for rows.Next() {
		var i DnsExposure
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Hostname,
			&i.Service,
			&i.Port,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposuresByGateway = `-- name: ListExposuresByGateway :many
SELECT id, gateway_id, hostname, service, port, zone_id, zone, record_id, created_at, updated_at, service_id FROM dns_exposures WHERE gateway_id = ? ORDER BY created_at
`

func (q *Queries) ListExposuresByGateway(ctx context.Context, gatewayID string) ([]DnsExposure, error) {
	rows, err := q.db.QueryContext(ctx, listExposuresByGateway, gatewayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsExposure
	for rows.Next() {
		var i DnsExposure
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Hostname,
			&i.Service,
			&i.Port,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposuresByService = `-- name: ListExposuresByService :many
SELECT id, gateway_id, hostname, service, port, zone_id, zone, record_id, created_at, updated_at, service_id FROM dns_exposures WHERE service_id = ? ORDER BY created_at
`

func (q *Queries) ListExposuresByService(ctx context.Context, serviceID sql.NullString) ([]DnsExposure, error) {
	rows, err := q.db.QueryContext(ctx, listExposuresByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsExposure
	for rows.Next() {
		var i DnsExposure
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Hostname,
			&i.Service,
			&i.Port,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExposuresByServiceName = `-- name: ListExposuresByServiceName :many
SELECT id, gateway_id, hostname, service, port, zone_id, zone, record_id, created_at, updated_at, service_id FROM dns_exposures WHERE service = ? ORDER BY created_at
`

func (q *Queries) ListExposuresByServiceName(ctx context.Context, service string) ([]DnsExposure, error) {
	rows, err := q.db.QueryContext(ctx, listExposuresByServiceName, service)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsExposure
	for rows.Next() {
		var i DnsExposure
		if err := rows.Scan(
			&i.ID,
			&i.GatewayID,
			&i.Hostname,
			&i.Service,
			&i.Port,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGateways = `-- name: ListGateways :many
SELECT id, kind, docker_network, service_id, service_name, tunnel_id, zone_id, zone, server_address, created_at, updated_at, networks, machine FROM dns_gateways ORDER BY created_at
`

func (q *Queries) ListGateways(ctx context.Context) ([]DnsGateway, error) {
	rows, err := q.db.QueryContext(ctx, listGateways)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsGateway
	for rows.Next() {
		var i DnsGateway
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DockerNetwork,
			&i.ServiceID,
			&i.ServiceName,
			&i.TunnelID,
			&i.ZoneID,
			&i.Zone,
			&i.ServerAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Networks,
			&i.Machine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGatewaysByMachine = `-- name: ListGatewaysByMachine :many
SELECT id, kind, docker_network, service_id, service_name, tunnel_id, zone_id, zone, server_address, created_at, updated_at, networks, machine FROM dns_gateways WHERE machine = ? ORDER BY created_at
`

func (q *Queries) ListGatewaysByMachine(ctx context.Context, machine string) ([]DnsGateway, error) {
	rows, err := q.db.QueryContext(ctx, listGatewaysByMachine, machine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsGateway
	for rows.Next() {
		var i DnsGateway
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DockerNetwork,
			&i.ServiceID,
			&i.ServiceName,
			&i.TunnelID,
			&i.ZoneID,
			&i.Zone,
			&i.ServerAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Networks,
			&i.Machine,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceHostnames = `-- name: ListServiceHostnames :many
SELECT service, hostname, zone_id, zone, record_id, type, content, created_at FROM dns_service_hostnames ORDER BY created_at
`

func (q *Queries) ListServiceHostnames(ctx context.Context) ([]DnsServiceHostname, error) {
	rows, err := q.db.QueryContext(ctx, listServiceHostnames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsServiceHostname
	for rows.Next() {
		var i DnsServiceHostname
		if err := rows.Scan(
			&i.Service,
			&i.Hostname,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTunnels = `-- name: ListTunnels :many
SELECT id, name, account_id, status, hostname, zone_id, zone, record_id, service, agent_service_id, token, created_at, updated_at FROM dns_tunnels ORDER BY created_at
`

func (q *Queries) ListTunnels(ctx context.Context) ([]DnsTunnel, error) {
	rows, err := q.db.QueryContext(ctx, listTunnels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsTunnel
	for rows.Next() {
		var i DnsTunnel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountID,
			&i.Status,
			&i.Hostname,
			&i.ZoneID,
			&i.Zone,
			&i.RecordID,
			&i.Service,
			&i.AgentServiceID,
			&i.Token,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveAccessServiceToken = `-- name: SaveAccessServiceToken :exec
INSERT INTO dns_access_service_token (id, token_id, client_id, client_secret, created_at, updated_at)
VALUES (1, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  token_id = excluded.token_id, client_id = excluded.client_id,
  client_secret = excluded.client_secret, updated_at = excluded.updated_at
`

type SaveAccessServiceTokenParams struct {
	TokenID      string
	ClientID     string
	ClientSecret string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) SaveAccessServiceToken(ctx context.Context, arg SaveAccessServiceTokenParams) error {
	_, err := q.db.ExecContext(ctx, saveAccessServiceToken,
		arg.TokenID,
		arg.ClientID,
		arg.ClientSecret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveExposure = `-- name: SaveExposure :exec
INSERT INTO dns_exposures (id, gateway_id, hostname, service, service_id, port, zone_id, zone, record_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  gateway_id = excluded.gateway_id, hostname = excluded.hostname, service = excluded.service, service_id = excluded.service_id,
  port = excluded.port, zone_id = excluded.zone_id, zone = excluded.zone,
  record_id = excluded.record_id, updated_at = excluded.updated_at
`

type SaveExposureParams struct {
	ID        string
	GatewayID string
	Hostname  string
	Service   string
	ServiceID sql.NullString
	Port      int64
	ZoneID    string
	Zone      string
	RecordID  string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) SaveExposure(ctx context.Context, arg SaveExposureParams) error {
	_, err := q.db.ExecContext(ctx, saveExposure,
		arg.ID,
		arg.GatewayID,
		arg.Hostname,
		arg.Service,
		arg.ServiceID,
		arg.Port,
		arg.ZoneID,
		arg.Zone,
		arg.RecordID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveGateway = `-- name: SaveGateway :exec
INSERT INTO dns_gateways (id, kind, docker_network, machine, networks, service_id, service_name, tunnel_id, zone_id, zone, server_address, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind, docker_network = excluded.docker_network, machine = excluded.machine, networks = excluded.networks,
  service_id = excluded.service_id, service_name = excluded.service_name,
  tunnel_id = excluded.tunnel_id, zone_id = excluded.zone_id, zone = excluded.zone,
  server_address = excluded.server_address, updated_at = excluded.updated_at
`

type SaveGatewayParams struct {
	ID            string
	Kind          string
	DockerNetwork string
	Machine       string
	Networks      string
	ServiceID     string
	ServiceName   string
	TunnelID      string
	ZoneID        string
	Zone          string
	ServerAddress string
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) SaveGateway(ctx context.Context, arg SaveGatewayParams) error {
	_, err := q.db.ExecContext(ctx, saveGateway,
		arg.ID,
		arg.Kind,
		arg.DockerNetwork,
		arg.Machine,
		arg.Networks,
		arg.ServiceID,
		arg.ServiceName,
		arg.TunnelID,
		arg.ZoneID,
		arg.Zone,
		arg.ServerAddress,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const saveTunnel = `-- name: SaveTunnel :exec
INSERT INTO dns_tunnels (id, name, account_id, status, hostname, zone_id, zone, record_id, service, agent_service_id, token, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name, account_id = excluded.account_id, status = excluded.status,
  hostname = excluded.hostname, zone_id = excluded.zone_id, zone = excluded.zone,
  record_id = excluded.record_id, service = excluded.service,
  agent_service_id = excluded.agent_service_id, token = excluded.token,
  updated_at = excluded.updated_at
`

type SaveTunnelParams struct {
	ID             string
	Name           string
	AccountID      string
	Status         string
	Hostname       string
	ZoneID         string
	Zone           string
	RecordID       string
	Service        string
	AgentServiceID string
	Token          string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) SaveTunnel(ctx context.Context, arg SaveTunnelParams) error {
	_, err := q.db.ExecContext(ctx, saveTunnel,
		arg.ID,
		arg.Name,
		arg.AccountID,
		arg.Status,
		arg.Hostname,
		arg.ZoneID,
		arg.Zone,
		arg.RecordID,
		arg.Service,
		arg.AgentServiceID,
		arg.Token,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertServiceHostname = `-- name: UpsertServiceHostname :exec
INSERT INTO dns_service_hostnames (service, hostname, zone_id, zone, record_id, type, content, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(service) DO UPDATE SET
  hostname = excluded.hostname, zone_id = excluded.zone_id, zone = excluded.zone,
  record_id = excluded.record_id, type = excluded.type, content = excluded.content,
  created_at = excluded.created_at
`

type UpsertServiceHostnameParams struct {
	Service   string
	Hostname  string
	ZoneID    string
	Zone      string
	RecordID  string
	Type      string
	Content   string
	CreatedAt int64
}

func (q *Queries) UpsertServiceHostname(ctx context.Context, arg UpsertServiceHostnameParams) error {
	_, err := q.db.ExecContext(ctx, upsertServiceHostname,
		arg.Service,
		arg.Hostname,
		arg.ZoneID,
		arg.Zone,
		arg.RecordID,
		arg.Type,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}
