// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_watchers.sql

package sqlcgen

import (
	"context"
)

const addAutoDocWatcher = `-- name: AddAutoDocWatcher :exec
INSERT INTO doc_watchers (doc_id, user_id, watching, source, created_at, updated_at)
VALUES (?1, ?2, 1, 'auto', ?3, ?3)
ON CONFLICT(doc_id, user_id) DO NOTHING
`

type AddAutoDocWatcherParams struct {
	DocID  string
	UserID string
	At     int64
}

// DO NOTHING keeps an opt-out: someone who stopped watching is not re-added by their own edit.
func (q *Queries) AddAutoDocWatcher(ctx context.Context, arg AddAutoDocWatcherParams) error {
	_, err := q.db.ExecContext(ctx, addAutoDocWatcher, arg.DocID, arg.UserID, arg.At)
	return err
}

const listDocWatchers = `-- name: ListDocWatchers :many
SELECT doc_id, user_id, watching, source, created_at, updated_at FROM doc_watchers WHERE doc_id = ? AND watching = 1 ORDER BY created_at, user_id
`

func (q *Queries) ListDocWatchers(ctx context.Context, docID string) ([]DocWatcher, error) {
	rows, err := q.db.QueryContext(ctx, listDocWatchers, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocWatcher
	for rows.Next() {
		var i DocWatcher
		if err := rows.Scan(
			&i.DocID,
			&i.UserID,
			&i.Watching,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocWatching = `-- name: SetDocWatching :exec
INSERT INTO doc_watchers (doc_id, user_id, watching, source, created_at, updated_at)
VALUES (?1, ?2, ?3, 'manual', ?4, ?4)
ON CONFLICT(doc_id, user_id) DO UPDATE SET watching = excluded.watching, updated_at = excluded.updated_at
`

type SetDocWatchingParams struct {
	DocID    string
	UserID   string
	Watching int64
	At       int64
}

func (q *Queries) SetDocWatching(ctx context.Context, arg SetDocWatchingParams) error {
	_, err := q.db.ExecContext(ctx, setDocWatching,
		arg.DocID,
		arg.UserID,
		arg.Watching,
		arg.At,
	)
	return err
}
