// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_settles.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteDueDocSettles = `-- name: DeleteDueDocSettles :exec
DELETE FROM doc_settles WHERE due_at <= ?
`

func (q *Queries) DeleteDueDocSettles(ctx context.Context, dueAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteDueDocSettles, dueAt)
	return err
}

const listDueDocSettles = `-- name: ListDueDocSettles :many
SELECT s.doc_id, s.first, s.actor_id, d.project_id, d.title
FROM doc_settles s
JOIN docs d ON d.id = s.doc_id
WHERE s.due_at <= ? AND d.archived = 0
ORDER BY s.due_at, s.doc_id
`

type ListDueDocSettlesRow struct {
	DocID     string
	First     int64
	ActorID   string
	ProjectID sql.NullString
	Title     string
}

func (q *Queries) ListDueDocSettles(ctx context.Context, dueAt int64) ([]ListDueDocSettlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDueDocSettles, dueAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueDocSettlesRow
	for rows.Next() {
		var i ListDueDocSettlesRow
		if err := rows.Scan(
			&i.DocID,
			&i.First,
			&i.ActorID,
			&i.ProjectID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDocSettleDue = `-- name: NextDocSettleDue :one
SELECT MIN(due_at) FROM doc_settles
`

func (q *Queries) NextDocSettleDue(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, nextDocSettleDue)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const upsertDocSettle = `-- name: UpsertDocSettle :exec
INSERT INTO doc_settles (doc_id, due_at, actor_id, first) VALUES (?, ?, ?, ?)
ON CONFLICT(doc_id) DO UPDATE SET due_at = excluded.due_at, actor_id = excluded.actor_id
`

type UpsertDocSettleParams struct {
	DocID   string
	DueAt   int64
	ActorID string
	First   int64
}

func (q *Queries) UpsertDocSettle(ctx context.Context, arg UpsertDocSettleParams) error {
	_, err := q.db.ExecContext(ctx, upsertDocSettle,
		arg.DocID,
		arg.DueAt,
		arg.ActorID,
		arg.First,
	)
	return err
}
