// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_clarifications.sql

package sqlcgen

import (
	"context"
)

const countPendingDocClarificationQuestions = `-- name: CountPendingDocClarificationQuestions :one
SELECT COUNT(*) FROM doc_clarification_questions
WHERE doc_id = ? AND round = ? AND skipped = 0 AND free_text = '' AND selected = '[]'
`

type CountPendingDocClarificationQuestionsParams struct {
	DocID string
	Round int64
}

func (q *Queries) CountPendingDocClarificationQuestions(ctx context.Context, arg CountPendingDocClarificationQuestionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingDocClarificationQuestions, arg.DocID, arg.Round)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDocClarificationRound = `-- name: DeleteDocClarificationRound :execrows
DELETE FROM doc_clarification_rounds WHERE doc_id = ? AND round = ?
`

type DeleteDocClarificationRoundParams struct {
	DocID string
	Round int64
}

func (q *Queries) DeleteDocClarificationRound(ctx context.Context, arg DeleteDocClarificationRoundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocClarificationRound, arg.DocID, arg.Round)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDocClarificationQuestion = `-- name: GetDocClarificationQuestion :one
SELECT id, doc_id, round, position, question, why, options, multi_select, selected, free_text, skipped, answered_by, answered_at FROM doc_clarification_questions WHERE id = ?
`

func (q *Queries) GetDocClarificationQuestion(ctx context.Context, id string) (DocClarificationQuestion, error) {
	row := q.db.QueryRowContext(ctx, getDocClarificationQuestion, id)
	var i DocClarificationQuestion
	err := row.Scan(
		&i.ID,
		&i.DocID,
		&i.Round,
		&i.Position,
		&i.Question,
		&i.Why,
		&i.Options,
		&i.MultiSelect,
		&i.Selected,
		&i.FreeText,
		&i.Skipped,
		&i.AnsweredBy,
		&i.AnsweredAt,
	)
	return i, err
}

const insertDocClarificationQuestion = `-- name: InsertDocClarificationQuestion :exec
INSERT INTO doc_clarification_questions (id, doc_id, round, position, question, why, options, multi_select)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDocClarificationQuestionParams struct {
	ID          string
	DocID       string
	Round       int64
	Position    int64
	Question    string
	Why         string
	Options     string
	MultiSelect int64
}

func (q *Queries) InsertDocClarificationQuestion(ctx context.Context, arg InsertDocClarificationQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertDocClarificationQuestion,
		arg.ID,
		arg.DocID,
		arg.Round,
		arg.Position,
		arg.Question,
		arg.Why,
		arg.Options,
		arg.MultiSelect,
	)
	return err
}

const insertDocClarificationRound = `-- name: InsertDocClarificationRound :exec
INSERT INTO doc_clarification_rounds (doc_id, round, started_by, trail_id, started_at, running, took_lock)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertDocClarificationRoundParams struct {
	DocID     string
	Round     int64
	StartedBy string
	TrailID   string
	StartedAt int64
	Running   int64
	TookLock  int64
}

func (q *Queries) InsertDocClarificationRound(ctx context.Context, arg InsertDocClarificationRoundParams) error {
	_, err := q.db.ExecContext(ctx, insertDocClarificationRound,
		arg.DocID,
		arg.Round,
		arg.StartedBy,
		arg.TrailID,
		arg.StartedAt,
		arg.Running,
		arg.TookLock,
	)
	return err
}

const listDocClarificationQuestions = `-- name: ListDocClarificationQuestions :many
SELECT id, doc_id, round, position, question, why, options, multi_select, selected, free_text, skipped, answered_by, answered_at FROM doc_clarification_questions WHERE doc_id = ? ORDER BY round, position
`

func (q *Queries) ListDocClarificationQuestions(ctx context.Context, docID string) ([]DocClarificationQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listDocClarificationQuestions, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocClarificationQuestion
	for rows.Next() {
		var i DocClarificationQuestion
		if err := rows.Scan(
			&i.ID,
			&i.DocID,
			&i.Round,
			&i.Position,
			&i.Question,
			&i.Why,
			&i.Options,
			&i.MultiSelect,
			&i.Selected,
			&i.FreeText,
			&i.Skipped,
			&i.AnsweredBy,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocClarificationRounds = `-- name: ListDocClarificationRounds :many
SELECT doc_id, round, started_by, trail_id, started_at, running, took_lock, anything_else, anything_else_by, anything_else_at, anything_else_reply, no_gaps_at, closed_by, closed_at FROM doc_clarification_rounds WHERE doc_id = ? ORDER BY round
`

func (q *Queries) ListDocClarificationRounds(ctx context.Context, docID string) ([]DocClarificationRound, error) {
	rows, err := q.db.QueryContext(ctx, listDocClarificationRounds, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocClarificationRound
	for rows.Next() {
		var i DocClarificationRound
		if err := rows.Scan(
			&i.DocID,
			&i.Round,
			&i.StartedBy,
			&i.TrailID,
			&i.StartedAt,
			&i.Running,
			&i.TookLock,
			&i.AnythingElse,
			&i.AnythingElseBy,
			&i.AnythingElseAt,
			&i.AnythingElseReply,
			&i.NoGapsAt,
			&i.ClosedBy,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocClarificationAnswer = `-- name: UpdateDocClarificationAnswer :execrows
UPDATE doc_clarification_questions SET selected = ?, free_text = ?, skipped = ?, answered_by = ?, answered_at = ?
WHERE id = ?
`

type UpdateDocClarificationAnswerParams struct {
	Selected   string
	FreeText   string
	Skipped    int64
	AnsweredBy string
	AnsweredAt int64
	ID         string
}

func (q *Queries) UpdateDocClarificationAnswer(ctx context.Context, arg UpdateDocClarificationAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocClarificationAnswer,
		arg.Selected,
		arg.FreeText,
		arg.Skipped,
		arg.AnsweredBy,
		arg.AnsweredAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDocClarificationRound = `-- name: UpdateDocClarificationRound :execrows
UPDATE doc_clarification_rounds SET running = ?, anything_else = ?, anything_else_by = ?, anything_else_at = ?,
    anything_else_reply = ?, no_gaps_at = ?, closed_by = ?, closed_at = ?
WHERE doc_id = ? AND round = ?
`

type UpdateDocClarificationRoundParams struct {
	Running           int64
	AnythingElse      string
	AnythingElseBy    string
	AnythingElseAt    int64
	AnythingElseReply string
	NoGapsAt          int64
	ClosedBy          string
	ClosedAt          int64
	DocID             string
	Round             int64
}

func (q *Queries) UpdateDocClarificationRound(ctx context.Context, arg UpdateDocClarificationRoundParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDocClarificationRound,
		arg.Running,
		arg.AnythingElse,
		arg.AnythingElseBy,
		arg.AnythingElseAt,
		arg.AnythingElseReply,
		arg.NoGapsAt,
		arg.ClosedBy,
		arg.ClosedAt,
		arg.DocID,
		arg.Round,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
