// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: doc_folders.sql

package sqlcgen

import (
	"context"
)

const createDocFolder = `-- name: CreateDocFolder :exec
INSERT INTO doc_folders (id, project_id, name, is_default, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateDocFolderParams struct {
	ID        string
	ProjectID string
	Name      string
	IsDefault int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateDocFolder(ctx context.Context, arg CreateDocFolderParams) error {
	_, err := q.db.ExecContext(ctx, createDocFolder,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.IsDefault,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDocFolder = `-- name: DeleteDocFolder :execrows
DELETE FROM doc_folders WHERE id = ?
`

func (q *Queries) DeleteDocFolder(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDocFolder, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDefaultDocFolder = `-- name: GetDefaultDocFolder :one
SELECT id, project_id, name, is_default, created_at, updated_at FROM doc_folders WHERE project_id = ? AND is_default = 1
`

func (q *Queries) GetDefaultDocFolder(ctx context.Context, projectID string) (DocFolder, error) {
	row := q.db.QueryRowContext(ctx, getDefaultDocFolder, projectID)
	var i DocFolder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocFolder = `-- name: GetDocFolder :one
SELECT id, project_id, name, is_default, created_at, updated_at FROM doc_folders WHERE id = ?
`

func (q *Queries) GetDocFolder(ctx context.Context, id string) (DocFolder, error) {
	row := q.db.QueryRowContext(ctx, getDocFolder, id)
	var i DocFolder
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocFoldersByProject = `-- name: ListDocFoldersByProject :many
SELECT id, project_id, name, is_default, created_at, updated_at FROM doc_folders WHERE project_id = ? ORDER BY is_default DESC, created_at, id
`

func (q *Queries) ListDocFoldersByProject(ctx context.Context, projectID string) ([]DocFolder, error) {
	rows, err := q.db.QueryContext(ctx, listDocFoldersByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocFolder
	for rows.Next() {
		var i DocFolder
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveDocsToFolder = `-- name: MoveDocsToFolder :exec
UPDATE docs SET folder_id = ?1 WHERE folder_id = ?2
`

type MoveDocsToFolderParams struct {
	ToFolderID   string
	FromFolderID string
}

func (q *Queries) MoveDocsToFolder(ctx context.Context, arg MoveDocsToFolderParams) error {
	_, err := q.db.ExecContext(ctx, moveDocsToFolder, arg.ToFolderID, arg.FromFolderID)
	return err
}

const renameDocFolder = `-- name: RenameDocFolder :execrows
UPDATE doc_folders SET name = ?, updated_at = ? WHERE id = ?
`

type RenameDocFolderParams struct {
	Name      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) RenameDocFolder(ctx context.Context, arg RenameDocFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameDocFolder, arg.Name, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDocFolder = `-- name: SetDocFolder :execrows
UPDATE docs SET folder_id = ? WHERE id = ?
`

type SetDocFolderParams struct {
	FolderID string
	ID       string
}

func (q *Queries) SetDocFolder(ctx context.Context, arg SetDocFolderParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDocFolder, arg.FolderID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
