// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const bumpDocVersion = `-- name: BumpDocVersion :execrows
UPDATE docs SET version = ? WHERE id = ?
`

type BumpDocVersionParams struct {
	Version int64
	ID      string
}

func (q *Queries) BumpDocVersion(ctx context.Context, arg BumpDocVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bumpDocVersion, arg.Version, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const commitDocBody = `-- name: CommitDocBody :execrows
UPDATE docs SET title = ?, body = ?, body_md = ?, version = ?, updated_at = ? WHERE id = ?
`

type CommitDocBodyParams struct {
	Title     string
	Body      string
	BodyMd    string
	Version   int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) CommitDocBody(ctx context.Context, arg CommitDocBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, commitDocBody,
		arg.Title,
		arg.Body,
		arg.BodyMd,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDoc = `-- name: CreateDoc :exec
INSERT INTO docs (id, project_id, title, body, body_md, version, archived, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateDocParams struct {
	ID        string
	ProjectID sql.NullString
	Title     string
	Body      string
	BodyMd    string
	Version   int64
	Archived  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateDoc(ctx context.Context, arg CreateDocParams) error {
	_, err := q.db.ExecContext(ctx, createDoc,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Body,
		arg.BodyMd,
		arg.Version,
		arg.Archived,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDoc = `-- name: DeleteDoc :execrows
DELETE FROM docs WHERE id = ?
`

func (q *Queries) DeleteDoc(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteDoc, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDoc = `-- name: GetDoc :one
SELECT id, title, body, version, created_at, updated_at, archived, body_md, project_id FROM docs WHERE id = ?
`

func (q *Queries) GetDoc(ctx context.Context, id string) (Doc, error) {
	row := q.db.QueryRowContext(ctx, getDoc, id)
	var i Doc
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
		&i.BodyMd,
		&i.ProjectID,
	)
	return i, err
}

const getDocVersion = `-- name: GetDocVersion :one
SELECT doc_id, version, title, body, name, author_id, created_at FROM doc_versions WHERE doc_id = ? AND version = ?
`

type GetDocVersionParams struct {
	DocID   string
	Version int64
}

type GetDocVersionRow struct {
	DocID     string
	Version   int64
	Title     string
	Body      string
	Name      string
	AuthorID  string
	CreatedAt int64
}

func (q *Queries) GetDocVersion(ctx context.Context, arg GetDocVersionParams) (GetDocVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getDocVersion, arg.DocID, arg.Version)
	var i GetDocVersionRow
	err := row.Scan(
		&i.DocID,
		&i.Version,
		&i.Title,
		&i.Body,
		&i.Name,
		&i.AuthorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertDocVersion = `-- name: InsertDocVersion :exec
INSERT INTO doc_versions (doc_id, version, title, body, created_at) VALUES (?, ?, ?, ?, ?)
`

type InsertDocVersionParams struct {
	DocID     string
	Version   int64
	Title     string
	Body      string
	CreatedAt int64
}

func (q *Queries) InsertDocVersion(ctx context.Context, arg InsertDocVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertDocVersion,
		arg.DocID,
		arg.Version,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const insertNamedDocVersion = `-- name: InsertNamedDocVersion :exec
INSERT INTO doc_versions (doc_id, version, title, body, name, author_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertNamedDocVersionParams struct {
	DocID     string
	Version   int64
	Title     string
	Body      string
	Name      string
	AuthorID  string
	CreatedAt int64
}

func (q *Queries) InsertNamedDocVersion(ctx context.Context, arg InsertNamedDocVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertNamedDocVersion,
		arg.DocID,
		arg.Version,
		arg.Title,
		arg.Body,
		arg.Name,
		arg.AuthorID,
		arg.CreatedAt,
	)
	return err
}

const listDocVersions = `-- name: ListDocVersions :many
SELECT doc_id, version, title, body, name, author_id, created_at FROM doc_versions WHERE doc_id = ? ORDER BY version DESC
`

type ListDocVersionsRow struct {
	DocID     string
	Version   int64
	Title     string
	Body      string
	Name      string
	AuthorID  string
	CreatedAt int64
}

func (q *Queries) ListDocVersions(ctx context.Context, docID string) ([]ListDocVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDocVersions, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocVersionsRow
	for rows.Next() {
		var i ListDocVersionsRow
		if err := rows.Scan(
			&i.DocID,
			&i.Version,
			&i.Title,
			&i.Body,
			&i.Name,
			&i.AuthorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocs = `-- name: ListDocs :many
SELECT id, title, body, version, created_at, updated_at, archived, body_md, project_id FROM docs ORDER BY created_at
`

func (q *Queries) ListDocs(ctx context.Context) ([]Doc, error) {
	rows, err := q.db.QueryContext(ctx, listDocs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
			&i.BodyMd,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocsByProject = `-- name: ListDocsByProject :many
SELECT id, title, body, version, created_at, updated_at, archived, body_md, project_id FROM docs WHERE project_id = ? ORDER BY created_at
`

func (q *Queries) ListDocsByProject(ctx context.Context, projectID sql.NullString) ([]Doc, error) {
	rows, err := q.db.QueryContext(ctx, listDocsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Doc
	for rows.Next() {
		var i Doc
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
			&i.BodyMd,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDocArchived = `-- name: SetDocArchived :execrows
UPDATE docs SET archived = ?, updated_at = ? WHERE id = ?
`

type SetDocArchivedParams struct {
	Archived  int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetDocArchived(ctx context.Context, arg SetDocArchivedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDocArchived, arg.Archived, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateDoc = `-- name: UpdateDoc :execrows
UPDATE docs SET title = ?, body = ?, body_md = ?, version = ?, updated_at = ? WHERE id = ?
`

type UpdateDocParams struct {
	Title     string
	Body      string
	BodyMd    string
	Version   int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateDoc(ctx context.Context, arg UpdateDocParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateDoc,
		arg.Title,
		arg.Body,
		arg.BodyMd,
		arg.Version,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
