// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_workspaces.sql

package sqlcgen

import (
	"context"
)

const eventWorkspaceOfConversation = `-- name: EventWorkspaceOfConversation :one
SELECT workspace_id FROM conversations WHERE id = ?
`

func (q *Queries) EventWorkspaceOfConversation(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfConversation, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfDeploy = `-- name: EventWorkspaceOfDeploy :one
SELECT COALESCE(p.workspace_id, '') FROM deploys d LEFT JOIN stacks s ON s.id = d.stack_id LEFT JOIN projects p ON p.id = s.project_id WHERE d.id = ?
`

func (q *Queries) EventWorkspaceOfDeploy(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfDeploy, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfDoc = `-- name: EventWorkspaceOfDoc :one
SELECT p.workspace_id FROM docs d JOIN projects p ON p.id = d.project_id WHERE d.id = ?
`

func (q *Queries) EventWorkspaceOfDoc(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfDoc, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfPlay = `-- name: EventWorkspaceOfPlay :one
SELECT workspace_id FROM plays WHERE id = ?
`

func (q *Queries) EventWorkspaceOfPlay(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfPlay, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfProject = `-- name: EventWorkspaceOfProject :one
SELECT workspace_id FROM projects WHERE id = ?
`

func (q *Queries) EventWorkspaceOfProject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfProject, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfRepo = `-- name: EventWorkspaceOfRepo :one
SELECT p.workspace_id FROM project_repos r JOIN projects p ON p.id = r.project_id WHERE r.owner = ? AND r.name = ?
`

type EventWorkspaceOfRepoParams struct {
	Owner string
	Name  string
}

func (q *Queries) EventWorkspaceOfRepo(ctx context.Context, arg EventWorkspaceOfRepoParams) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfRepo, arg.Owner, arg.Name)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfStack = `-- name: EventWorkspaceOfStack :one
SELECT COALESCE(p.workspace_id, '') FROM stacks s LEFT JOIN projects p ON p.id = s.project_id WHERE s.id = ?
`

func (q *Queries) EventWorkspaceOfStack(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfStack, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const eventWorkspaceOfTicket = `-- name: EventWorkspaceOfTicket :one
SELECT p.workspace_id FROM tickets t JOIN projects p ON p.id = t.project_id WHERE t.id = ?
`

func (q *Queries) EventWorkspaceOfTicket(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, eventWorkspaceOfTicket, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const listWorkspaceIDs = `-- name: ListWorkspaceIDs :many
SELECT id FROM workspaces ORDER BY created_at, id
`

func (q *Queries) ListWorkspaceIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
