// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_manifests.sql

package sqlcgen

import (
	"context"
)

const consumeGitHubManifest = `-- name: ConsumeGitHubManifest :execrows
DELETE FROM github_manifest_requests WHERE state_hash = ? AND initiator_hash = ? AND expires_at > ?
`

type ConsumeGitHubManifestParams struct {
	StateHash     string
	InitiatorHash string
	ExpiresAt     int64
}

func (q *Queries) ConsumeGitHubManifest(ctx context.Context, arg ConsumeGitHubManifestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeGitHubManifest, arg.StateHash, arg.InitiatorHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredGitHubManifests = `-- name: DeleteExpiredGitHubManifests :exec
DELETE FROM github_manifest_requests WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredGitHubManifests(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredGitHubManifests, expiresAt)
	return err
}

const startGitHubManifest = `-- name: StartGitHubManifest :exec
INSERT INTO github_manifest_requests (state_hash, initiator_hash, expires_at)
VALUES (?, ?, ?)
ON CONFLICT (initiator_hash) DO UPDATE SET state_hash = excluded.state_hash, expires_at = excluded.expires_at
`

type StartGitHubManifestParams struct {
	StateHash     string
	InitiatorHash string
	ExpiresAt     int64
}

func (q *Queries) StartGitHubManifest(ctx context.Context, arg StartGitHubManifestParams) error {
	_, err := q.db.ExecContext(ctx, startGitHubManifest, arg.StateHash, arg.InitiatorHash, arg.ExpiresAt)
	return err
}
