// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_user_links.sql

package sqlcgen

import (
	"context"
)

const deleteGitHubUserLink = `-- name: DeleteGitHubUserLink :exec
DELETE FROM github_user_links WHERE user_id = ?
`

func (q *Queries) DeleteGitHubUserLink(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteGitHubUserLink, userID)
	return err
}

const getGitHubUserLink = `-- name: GetGitHubUserLink :one
SELECT user_id, access_token, refresh_token, expires_at, refresh_expires_at, needs_reconnect, connected_at FROM github_user_links WHERE user_id = ?
`

func (q *Queries) GetGitHubUserLink(ctx context.Context, userID string) (GithubUserLink, error) {
	row := q.db.QueryRowContext(ctx, getGitHubUserLink, userID)
	var i GithubUserLink
	err := row.Scan(
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.RefreshExpiresAt,
		&i.NeedsReconnect,
		&i.ConnectedAt,
	)
	return i, err
}

const saveGitHubUserLink = `-- name: SaveGitHubUserLink :exec
INSERT INTO github_user_links (user_id, access_token, refresh_token, expires_at, refresh_expires_at, needs_reconnect, connected_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
  access_token = excluded.access_token, refresh_token = excluded.refresh_token, expires_at = excluded.expires_at,
  refresh_expires_at = excluded.refresh_expires_at, needs_reconnect = excluded.needs_reconnect,
  connected_at = excluded.connected_at
`

type SaveGitHubUserLinkParams struct {
	UserID           string
	AccessToken      string
	RefreshToken     string
	ExpiresAt        int64
	RefreshExpiresAt int64
	NeedsReconnect   int64
	ConnectedAt      int64
}

func (q *Queries) SaveGitHubUserLink(ctx context.Context, arg SaveGitHubUserLinkParams) error {
	_, err := q.db.ExecContext(ctx, saveGitHubUserLink,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.RefreshExpiresAt,
		arg.NeedsReconnect,
		arg.ConnectedAt,
	)
	return err
}
