// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_installations.sql

package sqlcgen

import (
	"context"
)

const assignGitHubInstallation = `-- name: AssignGitHubInstallation :exec
INSERT INTO github_installation_workspaces (account_login, workspace_id, assigned_at)
VALUES (?, ?, ?)
ON CONFLICT(account_login, workspace_id) DO NOTHING
`

type AssignGitHubInstallationParams struct {
	AccountLogin string
	WorkspaceID  string
	AssignedAt   int64
}

func (q *Queries) AssignGitHubInstallation(ctx context.Context, arg AssignGitHubInstallationParams) error {
	_, err := q.db.ExecContext(ctx, assignGitHubInstallation, arg.AccountLogin, arg.WorkspaceID, arg.AssignedAt)
	return err
}

const listGitHubInstallationAccountsIn = `-- name: ListGitHubInstallationAccountsIn :many
SELECT DISTINCT account_login FROM github_installation_workspaces
WHERE workspace_id IN (SELECT value FROM json_each(?))
ORDER BY account_login
`

func (q *Queries) ListGitHubInstallationAccountsIn(ctx context.Context, jsonEach interface{}) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubInstallationAccountsIn, jsonEach)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_login string
		if err := rows.Scan(&account_login); err != nil {
			return nil, err
		}
		items = append(items, account_login)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGitHubInstallationWorkspaces = `-- name: ListGitHubInstallationWorkspaces :many
SELECT a.account_login, w.id AS workspace_id, w.name AS workspace_name
FROM github_installation_workspaces a
JOIN workspaces w ON w.id = a.workspace_id
ORDER BY a.account_login, w.name, w.id
`

type ListGitHubInstallationWorkspacesRow struct {
	AccountLogin  string
	WorkspaceID   string
	WorkspaceName string
}

func (q *Queries) ListGitHubInstallationWorkspaces(ctx context.Context) ([]ListGitHubInstallationWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGitHubInstallationWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGitHubInstallationWorkspacesRow
	for rows.Next() {
		var i ListGitHubInstallationWorkspacesRow
		if err := rows.Scan(&i.AccountLogin, &i.WorkspaceID, &i.WorkspaceName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignGitHubInstallation = `-- name: UnassignGitHubInstallation :exec
DELETE FROM github_installation_workspaces WHERE account_login = ? AND workspace_id = ?
`

type UnassignGitHubInstallationParams struct {
	AccountLogin string
	WorkspaceID  string
}

func (q *Queries) UnassignGitHubInstallation(ctx context.Context, arg UnassignGitHubInstallationParams) error {
	_, err := q.db.ExecContext(ctx, unassignGitHubInstallation, arg.AccountLogin, arg.WorkspaceID)
	return err
}
