// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instance_templates.sql

package sqlcgen

import (
	"context"
)

const deleteInstanceTemplate = `-- name: DeleteInstanceTemplate :exec
DELETE FROM instance_templates WHERE kind = ? AND key = ?
`

type DeleteInstanceTemplateParams struct {
	Kind string
	Key  string
}

func (q *Queries) DeleteInstanceTemplate(ctx context.Context, arg DeleteInstanceTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteInstanceTemplate, arg.Kind, arg.Key)
	return err
}

const getInstanceTemplate = `-- name: GetInstanceTemplate :one
SELECT kind, "key", body, updated_by, updated_at FROM instance_templates WHERE kind = ? AND key = ?
`

type GetInstanceTemplateParams struct {
	Kind string
	Key  string
}

func (q *Queries) GetInstanceTemplate(ctx context.Context, arg GetInstanceTemplateParams) (InstanceTemplate, error) {
	row := q.db.QueryRowContext(ctx, getInstanceTemplate, arg.Kind, arg.Key)
	var i InstanceTemplate
	err := row.Scan(
		&i.Kind,
		&i.Key,
		&i.Body,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstanceTemplates = `-- name: ListInstanceTemplates :many
SELECT kind, "key", body, updated_by, updated_at FROM instance_templates ORDER BY kind, key
`

func (q *Queries) ListInstanceTemplates(ctx context.Context) ([]InstanceTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listInstanceTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceTemplate
	for rows.Next() {
		var i InstanceTemplate
		if err := rows.Scan(
			&i.Kind,
			&i.Key,
			&i.Body,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInstanceTemplate = `-- name: UpsertInstanceTemplate :exec
INSERT INTO instance_templates (kind, key, body, updated_by, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (kind, key) DO UPDATE SET body = excluded.body, updated_by = excluded.updated_by, updated_at = excluded.updated_at
`

type UpsertInstanceTemplateParams struct {
	Kind      string
	Key       string
	Body      string
	UpdatedBy string
	UpdatedAt int64
}

func (q *Queries) UpsertInstanceTemplate(ctx context.Context, arg UpsertInstanceTemplateParams) error {
	_, err := q.db.ExecContext(ctx, upsertInstanceTemplate,
		arg.Kind,
		arg.Key,
		arg.Body,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}
