// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interview_sources.sql

package sqlcgen

import (
	"context"
)

const countInterviewSources = `-- name: CountInterviewSources :one
SELECT COUNT(*) FROM interview_sources WHERE project_id = ?
`

func (q *Queries) CountInterviewSources(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInterviewSources, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInterviewDraft = `-- name: DeleteInterviewDraft :execrows
DELETE FROM interview_drafts WHERE id = ?
`

func (q *Queries) DeleteInterviewDraft(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInterviewDraft, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInterviewSource = `-- name: DeleteInterviewSource :execrows
DELETE FROM interview_sources WHERE id = ?
`

func (q *Queries) DeleteInterviewSource(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInterviewSource, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInterviewDraft = `-- name: GetInterviewDraft :one
SELECT id, workspace_id, project_id, question, selected, free_text, source_ids, where_line, trail_id, drafted_by, drafted_at FROM interview_drafts WHERE id = ?
`

func (q *Queries) GetInterviewDraft(ctx context.Context, id string) (InterviewDraft, error) {
	row := q.db.QueryRowContext(ctx, getInterviewDraft, id)
	var i InterviewDraft
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Question,
		&i.Selected,
		&i.FreeText,
		&i.SourceIds,
		&i.WhereLine,
		&i.TrailID,
		&i.DraftedBy,
		&i.DraftedAt,
	)
	return i, err
}

const getInterviewSource = `-- name: GetInterviewSource :one
SELECT id, workspace_id, project_id, kind, ref, label, body, stance, added_by, added_at, updated_at FROM interview_sources WHERE id = ?
`

func (q *Queries) GetInterviewSource(ctx context.Context, id string) (InterviewSource, error) {
	row := q.db.QueryRowContext(ctx, getInterviewSource, id)
	var i InterviewSource
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Kind,
		&i.Ref,
		&i.Label,
		&i.Body,
		&i.Stance,
		&i.AddedBy,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInterviewSource = `-- name: InsertInterviewSource :exec
INSERT INTO interview_sources (id, workspace_id, project_id, kind, ref, label, body, stance, added_by, added_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInterviewSourceParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Kind        string
	Ref         string
	Label       string
	Body        string
	Stance      string
	AddedBy     string
	AddedAt     int64
	UpdatedAt   int64
}

func (q *Queries) InsertInterviewSource(ctx context.Context, arg InsertInterviewSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertInterviewSource,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Kind,
		arg.Ref,
		arg.Label,
		arg.Body,
		arg.Stance,
		arg.AddedBy,
		arg.AddedAt,
		arg.UpdatedAt,
	)
	return err
}

const listInterviewDrafts = `-- name: ListInterviewDrafts :many
SELECT id, workspace_id, project_id, question, selected, free_text, source_ids, where_line, trail_id, drafted_by, drafted_at FROM interview_drafts WHERE project_id = ? ORDER BY drafted_at, id
`

func (q *Queries) ListInterviewDrafts(ctx context.Context, projectID string) ([]InterviewDraft, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewDrafts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewDraft
	for rows.Next() {
		var i InterviewDraft
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Question,
			&i.Selected,
			&i.FreeText,
			&i.SourceIds,
			&i.WhereLine,
			&i.TrailID,
			&i.DraftedBy,
			&i.DraftedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInterviewSources = `-- name: ListInterviewSources :many
SELECT id, workspace_id, project_id, kind, ref, label, body, stance, added_by, added_at, updated_at FROM interview_sources WHERE project_id = ? ORDER BY added_at, id
`

func (q *Queries) ListInterviewSources(ctx context.Context, projectID string) ([]InterviewSource, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewSource
	for rows.Next() {
		var i InterviewSource
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Kind,
			&i.Ref,
			&i.Label,
			&i.Body,
			&i.Stance,
			&i.AddedBy,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewSource = `-- name: UpdateInterviewSource :execrows
UPDATE interview_sources SET stance = ?, label = ?, updated_at = ? WHERE id = ?
`

type UpdateInterviewSourceParams struct {
	Stance    string
	Label     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateInterviewSource(ctx context.Context, arg UpdateInterviewSourceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateInterviewSource,
		arg.Stance,
		arg.Label,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertInterviewDraft = `-- name: UpsertInterviewDraft :exec
INSERT INTO interview_drafts (id, workspace_id, project_id, question, selected, free_text, source_ids, where_line, trail_id, drafted_by, drafted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, question) DO UPDATE SET
    id = excluded.id, selected = excluded.selected, free_text = excluded.free_text, source_ids = excluded.source_ids,
    where_line = excluded.where_line, trail_id = excluded.trail_id, drafted_by = excluded.drafted_by, drafted_at = excluded.drafted_at
`

type UpsertInterviewDraftParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Question    string
	Selected    string
	FreeText    string
	SourceIds   string
	WhereLine   string
	TrailID     string
	DraftedBy   string
	DraftedAt   int64
}

func (q *Queries) UpsertInterviewDraft(ctx context.Context, arg UpsertInterviewDraftParams) error {
	_, err := q.db.ExecContext(ctx, upsertInterviewDraft,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Question,
		arg.Selected,
		arg.FreeText,
		arg.SourceIds,
		arg.WhereLine,
		arg.TrailID,
		arg.DraftedBy,
		arg.DraftedAt,
	)
	return err
}
