// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interview_answers.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteInterviewAnswer = `-- name: DeleteInterviewAnswer :execrows
DELETE FROM interview_answers WHERE project_id = ? AND round = ? AND question = ?
`

type DeleteInterviewAnswerParams struct {
	ProjectID string
	Round     int64
	Question  string
}

func (q *Queries) DeleteInterviewAnswer(ctx context.Context, arg DeleteInterviewAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInterviewAnswer, arg.ProjectID, arg.Round, arg.Question)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertInterviewAnswer = `-- name: InsertInterviewAnswer :exec
INSERT INTO interview_answers (id, workspace_id, project_id, round, question, options, multi_select, why, selected, free_text, skipped, answered_by, answered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInterviewAnswerParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Round       int64
	Question    string
	Options     sql.NullString
	MultiSelect int64
	Why         sql.NullString
	Selected    string
	FreeText    string
	Skipped     int64
	AnsweredBy  string
	AnsweredAt  int64
}

func (q *Queries) InsertInterviewAnswer(ctx context.Context, arg InsertInterviewAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertInterviewAnswer,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Round,
		arg.Question,
		arg.Options,
		arg.MultiSelect,
		arg.Why,
		arg.Selected,
		arg.FreeText,
		arg.Skipped,
		arg.AnsweredBy,
		arg.AnsweredAt,
	)
	return err
}

const lastInterviewRound = `-- name: LastInterviewRound :one
SELECT MAX(round) FROM interview_answers WHERE project_id = ?
`

func (q *Queries) LastInterviewRound(ctx context.Context, projectID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, lastInterviewRound, projectID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const listInterviewAnswers = `-- name: ListInterviewAnswers :many
SELECT id, workspace_id, project_id, round, question, options, multi_select, why, selected, free_text, skipped, answered_by, answered_at FROM interview_answers WHERE project_id = ? ORDER BY round, id
`

func (q *Queries) ListInterviewAnswers(ctx context.Context, projectID string) ([]InterviewAnswer, error) {
	rows, err := q.db.QueryContext(ctx, listInterviewAnswers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InterviewAnswer
	for rows.Next() {
		var i InterviewAnswer
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Round,
			&i.Question,
			&i.Options,
			&i.MultiSelect,
			&i.Why,
			&i.Selected,
			&i.FreeText,
			&i.Skipped,
			&i.AnsweredBy,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInterviewAnswer = `-- name: UpdateInterviewAnswer :one
UPDATE interview_answers SET selected = ?, free_text = ?, skipped = ?, answered_by = ?, answered_at = ?
WHERE project_id = ? AND round = ? AND question = ?
RETURNING id, workspace_id, project_id, round, question, options, multi_select, why, selected, free_text, skipped, answered_by, answered_at
`

type UpdateInterviewAnswerParams struct {
	Selected   string
	FreeText   string
	Skipped    int64
	AnsweredBy string
	AnsweredAt int64
	ProjectID  string
	Round      int64
	Question   string
}

func (q *Queries) UpdateInterviewAnswer(ctx context.Context, arg UpdateInterviewAnswerParams) (InterviewAnswer, error) {
	row := q.db.QueryRowContext(ctx, updateInterviewAnswer,
		arg.Selected,
		arg.FreeText,
		arg.Skipped,
		arg.AnsweredBy,
		arg.AnsweredAt,
		arg.ProjectID,
		arg.Round,
		arg.Question,
	)
	var i InterviewAnswer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Round,
		&i.Question,
		&i.Options,
		&i.MultiSelect,
		&i.Why,
		&i.Selected,
		&i.FreeText,
		&i.Skipped,
		&i.AnsweredBy,
		&i.AnsweredAt,
	)
	return i, err
}

const upsertInterviewAnswer = `-- name: UpsertInterviewAnswer :one
INSERT INTO interview_answers (id, workspace_id, project_id, round, question, selected, free_text, skipped, answered_by, answered_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (project_id, round, question) DO UPDATE SET
    selected = excluded.selected, free_text = excluded.free_text, skipped = excluded.skipped,
    answered_by = excluded.answered_by, answered_at = excluded.answered_at
RETURNING id, workspace_id, project_id, round, question, options, multi_select, why, selected, free_text, skipped, answered_by, answered_at
`

type UpsertInterviewAnswerParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	Round       int64
	Question    string
	Selected    string
	FreeText    string
	Skipped     int64
	AnsweredBy  string
	AnsweredAt  int64
}

func (q *Queries) UpsertInterviewAnswer(ctx context.Context, arg UpsertInterviewAnswerParams) (InterviewAnswer, error) {
	row := q.db.QueryRowContext(ctx, upsertInterviewAnswer,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Round,
		arg.Question,
		arg.Selected,
		arg.FreeText,
		arg.Skipped,
		arg.AnsweredBy,
		arg.AnsweredAt,
	)
	var i InterviewAnswer
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Round,
		&i.Question,
		&i.Options,
		&i.MultiSelect,
		&i.Why,
		&i.Selected,
		&i.FreeText,
		&i.Skipped,
		&i.AnsweredBy,
		&i.AnsweredAt,
	)
	return i, err
}
