// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addInvitationMember = `-- name: AddInvitationMember :exec
INSERT INTO workspace_members (user_id, workspace_id, role_id, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id, workspace_id) DO NOTHING
`

type AddInvitationMemberParams struct {
	UserID      string
	WorkspaceID string
	RoleID      string
	CreatedAt   int64
}

func (q *Queries) AddInvitationMember(ctx context.Context, arg AddInvitationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addInvitationMember,
		arg.UserID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.CreatedAt,
	)
	return err
}

const addInvitationOverwrite = `-- name: AddInvitationOverwrite :exec
INSERT INTO permission_overwrites (resource_type, resource_id, user_id, allow, deny, created_at, updated_at)
VALUES ('workspace', ?, ?, ?, ?, ?, ?)
ON CONFLICT(resource_type, resource_id, user_id) DO NOTHING
`

type AddInvitationOverwriteParams struct {
	ResourceID string
	UserID     string
	Allow      string
	Deny       string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) AddInvitationOverwrite(ctx context.Context, arg AddInvitationOverwriteParams) error {
	_, err := q.db.ExecContext(ctx, addInvitationOverwrite,
		arg.ResourceID,
		arg.UserID,
		arg.Allow,
		arg.Deny,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const completeOAuthHandoffRedemption = `-- name: CompleteOAuthHandoffRedemption :execrows
UPDATE invitation_oauth_handoffs
SET admitted_user_id = ?, completed_at = ?
WHERE acceptance_hash = ? AND completed_at IS NULL AND expires_at > ?
`

type CompleteOAuthHandoffRedemptionParams struct {
	AdmittedUserID sql.NullString
	CompletedAt    sql.NullInt64
	AcceptanceHash sql.NullString
	ExpiresAt      int64
}

func (q *Queries) CompleteOAuthHandoffRedemption(ctx context.Context, arg CompleteOAuthHandoffRedemptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeOAuthHandoffRedemption,
		arg.AdmittedUserID,
		arg.CompletedAt,
		arg.AcceptanceHash,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeOAuthHandoffTransition = `-- name: CompleteOAuthHandoffTransition :execrows
UPDATE invitation_oauth_handoffs
SET oauth_state_hash = NULL,
    acceptance_hash = ?,
    provider_user_id = ?,
    login = ?,
    name = ?,
    avatar_url = ?,
    existing_user_id = ?,
    expires_at = ?
WHERE oauth_state_hash = ? AND expires_at > ? AND acceptance_hash IS NULL
`

type CompleteOAuthHandoffTransitionParams struct {
	AcceptanceHash sql.NullString
	ProviderUserID sql.NullString
	Login          sql.NullString
	Name           sql.NullString
	AvatarUrl      sql.NullString
	ExistingUserID sql.NullString
	ExpiresAt      int64
	OauthStateHash sql.NullString
	ExpiresAt_2    int64
}

func (q *Queries) CompleteOAuthHandoffTransition(ctx context.Context, arg CompleteOAuthHandoffTransitionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeOAuthHandoffTransition,
		arg.AcceptanceHash,
		arg.ProviderUserID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.ExistingUserID,
		arg.ExpiresAt,
		arg.OauthStateHash,
		arg.ExpiresAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createInvitation = `-- name: CreateInvitation :exec
INSERT INTO invitations (id, token_hash, invited_by, created_at, expires_at)
VALUES (?, ?, ?, ?, ?)
`

type CreateInvitationParams struct {
	ID        string
	TokenHash string
	InvitedBy string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.ExecContext(ctx, createInvitation,
		arg.ID,
		arg.TokenHash,
		arg.InvitedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createInvitationGrant = `-- name: CreateInvitationGrant :exec
INSERT INTO invitation_grants (invitation_id, workspace_id, role_id, allow_json, deny_json)
VALUES (?, ?, ?, ?, ?)
`

type CreateInvitationGrantParams struct {
	InvitationID string
	WorkspaceID  string
	RoleID       string
	AllowJson    string
	DenyJson     string
}

func (q *Queries) CreateInvitationGrant(ctx context.Context, arg CreateInvitationGrantParams) error {
	_, err := q.db.ExecContext(ctx, createInvitationGrant,
		arg.InvitationID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.AllowJson,
		arg.DenyJson,
	)
	return err
}

const createOAuthHandoff = `-- name: CreateOAuthHandoff :exec
INSERT INTO invitation_oauth_handoffs (id, invitation_id, oauth_state_hash, acceptance_hash, provider, created_at, expires_at)
VALUES (?, ?, ?, NULL, ?, ?, ?)
`

type CreateOAuthHandoffParams struct {
	ID             string
	InvitationID   string
	OauthStateHash sql.NullString
	Provider       string
	CreatedAt      int64
	ExpiresAt      int64
}

func (q *Queries) CreateOAuthHandoff(ctx context.Context, arg CreateOAuthHandoffParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthHandoff,
		arg.ID,
		arg.InvitationID,
		arg.OauthStateHash,
		arg.Provider,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :exec
DELETE FROM invitations WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInvitations, expiresAt)
	return err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM invitations WHERE id = ?
`

func (q *Queries) DeleteInvitation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvitation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteInvitationBeforeRedeem = `-- name: DeleteInvitationBeforeRedeem :execrows
DELETE FROM invitations
WHERE id = ? AND token_hash = ? AND expires_at > ?
`

type DeleteInvitationBeforeRedeemParams struct {
	ID        string
	TokenHash string
	ExpiresAt int64
}

func (q *Queries) DeleteInvitationBeforeRedeem(ctx context.Context, arg DeleteInvitationBeforeRedeemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvitationBeforeRedeem, arg.ID, arg.TokenHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, token_hash, invited_by, created_at, expires_at, redeemed_at, redeemed_by
FROM invitations
WHERE id = ?
`

func (q *Queries) GetInvitationByID(ctx context.Context, id string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, token_hash, invited_by, created_at, expires_at, redeemed_at, redeemed_by
FROM invitations
WHERE token_hash = ?
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRowContext(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.RedeemedBy,
	)
	return i, err
}

const getInvitationCreatorWorkspaceAccess = `-- name: GetInvitationCreatorWorkspaceAccess :one
SELECT r.is_owner_role, r.permissions, po.allow, po.deny
FROM workspace_members m
JOIN roles r ON r.id = m.role_id
LEFT JOIN permission_overwrites po
  ON po.resource_type = 'workspace'
 AND po.resource_id = m.workspace_id
 AND po.user_id = m.user_id
WHERE m.workspace_id = ? AND m.user_id = ?
`

type GetInvitationCreatorWorkspaceAccessParams struct {
	WorkspaceID string
	UserID      string
}

type GetInvitationCreatorWorkspaceAccessRow struct {
	IsOwnerRole int64
	Permissions string
	Allow       sql.NullString
	Deny        sql.NullString
}

func (q *Queries) GetInvitationCreatorWorkspaceAccess(ctx context.Context, arg GetInvitationCreatorWorkspaceAccessParams) (GetInvitationCreatorWorkspaceAccessRow, error) {
	row := q.db.QueryRowContext(ctx, getInvitationCreatorWorkspaceAccess, arg.WorkspaceID, arg.UserID)
	var i GetInvitationCreatorWorkspaceAccessRow
	err := row.Scan(
		&i.IsOwnerRole,
		&i.Permissions,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}

const getInvitationMember = `-- name: GetInvitationMember :one
SELECT role_id
FROM workspace_members
WHERE workspace_id = ? AND user_id = ?
`

type GetInvitationMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetInvitationMember(ctx context.Context, arg GetInvitationMemberParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getInvitationMember, arg.WorkspaceID, arg.UserID)
	var role_id string
	err := row.Scan(&role_id)
	return role_id, err
}

const getOAuthHandoffByAcceptanceHash = `-- name: GetOAuthHandoffByAcceptanceHash :one
SELECT id, invitation_id, oauth_state_hash, acceptance_hash, provider, provider_user_id, login, name, avatar_url, existing_user_id, admitted_user_id, completed_at, created_at, expires_at
FROM invitation_oauth_handoffs
WHERE acceptance_hash = ?
`

func (q *Queries) GetOAuthHandoffByAcceptanceHash(ctx context.Context, acceptanceHash sql.NullString) (InvitationOauthHandoff, error) {
	row := q.db.QueryRowContext(ctx, getOAuthHandoffByAcceptanceHash, acceptanceHash)
	var i InvitationOauthHandoff
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.OauthStateHash,
		&i.AcceptanceHash,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.ExistingUserID,
		&i.AdmittedUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getOAuthHandoffByState = `-- name: GetOAuthHandoffByState :one
SELECT id, invitation_id, oauth_state_hash, acceptance_hash, provider, provider_user_id, login, name, avatar_url, existing_user_id, admitted_user_id, completed_at, created_at, expires_at
FROM invitation_oauth_handoffs
WHERE oauth_state_hash = ?
`

func (q *Queries) GetOAuthHandoffByState(ctx context.Context, oauthStateHash sql.NullString) (InvitationOauthHandoff, error) {
	row := q.db.QueryRowContext(ctx, getOAuthHandoffByState, oauthStateHash)
	var i InvitationOauthHandoff
	err := row.Scan(
		&i.ID,
		&i.InvitationID,
		&i.OauthStateHash,
		&i.AcceptanceHash,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.ExistingUserID,
		&i.AdmittedUserID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRoleForInvitationGrant = `-- name: GetRoleForInvitationGrant :one
SELECT id, workspace_id, name, is_owner_role, created_at, updated_at, permissions
FROM roles
WHERE id = ? AND workspace_id = ?
`

type GetRoleForInvitationGrantParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetRoleForInvitationGrant(ctx context.Context, arg GetRoleForInvitationGrantParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleForInvitationGrant, arg.ID, arg.WorkspaceID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.IsOwnerRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Permissions,
	)
	return i, err
}

const getUserByProviderForInvitation = `-- name: GetUserByProviderForInvitation :one
SELECT id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, display_name, avatar_override_url, account_status FROM users WHERE provider = ? AND provider_user_id = ?
`

type GetUserByProviderForInvitationParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetUserByProviderForInvitation(ctx context.Context, arg GetUserByProviderForInvitationParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProviderForInvitation, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Login,
		&i.Name,
		&i.AvatarUrl,
		&i.FirstLoginDone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanCreateWorkspace,
		&i.DisplayName,
		&i.AvatarOverrideUrl,
		&i.AccountStatus,
	)
	return i, err
}

const getWorkspaceForInvitationGrant = `-- name: GetWorkspaceForInvitationGrant :one
SELECT w.id, w.name
FROM workspaces w
WHERE w.id = ?
`

type GetWorkspaceForInvitationGrantRow struct {
	ID   string
	Name string
}

func (q *Queries) GetWorkspaceForInvitationGrant(ctx context.Context, id string) (GetWorkspaceForInvitationGrantRow, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceForInvitationGrant, id)
	var i GetWorkspaceForInvitationGrantRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertUserForInvitation = `-- name: InsertUserForInvitation :exec
INSERT INTO users (id, provider, provider_user_id, login, name, avatar_url, first_login_done, created_at, updated_at, can_create_workspace, account_status)
VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, 0, 'active')
`

type InsertUserForInvitationParams struct {
	ID             string
	Provider       string
	ProviderUserID string
	Login          string
	Name           string
	AvatarUrl      string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) InsertUserForInvitation(ctx context.Context, arg InsertUserForInvitationParams) error {
	_, err := q.db.ExecContext(ctx, insertUserForInvitation,
		arg.ID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Login,
		arg.Name,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listAllInvitations = `-- name: ListAllInvitations :many
SELECT id, token_hash, invited_by, created_at, expires_at, redeemed_at, redeemed_by
FROM invitations
ORDER BY created_at, id
`

func (q *Queries) ListAllInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listAllInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RedeemedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationGrantsByInvitation = `-- name: ListInvitationGrantsByInvitation :many
SELECT invitation_id, workspace_id, role_id, allow_json, deny_json
FROM invitation_grants
WHERE invitation_id = ?
ORDER BY workspace_id
`

func (q *Queries) ListInvitationGrantsByInvitation(ctx context.Context, invitationID string) ([]InvitationGrant, error) {
	rows, err := q.db.QueryContext(ctx, listInvitationGrantsByInvitation, invitationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvitationGrant
	for rows.Next() {
		var i InvitationGrant
		if err := rows.Scan(
			&i.InvitationID,
			&i.WorkspaceID,
			&i.RoleID,
			&i.AllowJson,
			&i.DenyJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitationsByActor = `-- name: ListInvitationsByActor :many
SELECT id, token_hash, invited_by, created_at, expires_at, redeemed_at, redeemed_by
FROM invitations
WHERE invited_by = ?
ORDER BY created_at, id
`

func (q *Queries) ListInvitationsByActor(ctx context.Context, invitedBy string) ([]Invitation, error) {
	rows, err := q.db.QueryContext(ctx, listInvitationsByActor, invitedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.RedeemedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationRedeemed = `-- name: MarkInvitationRedeemed :execrows
UPDATE invitations
SET redeemed_at = ?, redeemed_by = ?
WHERE id = ? AND redeemed_at IS NULL AND expires_at > ?
`

type MarkInvitationRedeemedParams struct {
	RedeemedAt sql.NullInt64
	RedeemedBy sql.NullString
	ID         string
	ExpiresAt  int64
}

func (q *Queries) MarkInvitationRedeemed(ctx context.Context, arg MarkInvitationRedeemedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markInvitationRedeemed,
		arg.RedeemedAt,
		arg.RedeemedBy,
		arg.ID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setInvitationRedeemedBy = `-- name: SetInvitationRedeemedBy :execrows
UPDATE invitations SET redeemed_by = ? WHERE id = ? AND redeemed_at IS NOT NULL
`

type SetInvitationRedeemedByParams struct {
	RedeemedBy sql.NullString
	ID         string
}

func (q *Queries) SetInvitationRedeemedBy(ctx context.Context, arg SetInvitationRedeemedByParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInvitationRedeemedBy, arg.RedeemedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
