// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: machines.sql

package sqlcgen

import (
	"context"
)

const createMachine = `-- name: CreateMachine :exec
INSERT INTO machines (id, name, stack_root, reported_hostname, first_seen, last_seen) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMachineParams struct {
	ID               string
	Name             string
	StackRoot        string
	ReportedHostname string
	FirstSeen        int64
	LastSeen         int64
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) error {
	_, err := q.db.ExecContext(ctx, createMachine,
		arg.ID,
		arg.Name,
		arg.StackRoot,
		arg.ReportedHostname,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT id, name, stack_root, reported_hostname, first_seen, last_seen FROM machines WHERE id = ?
`

func (q *Queries) GetMachine(ctx context.Context, id string) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StackRoot,
		&i.ReportedHostname,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const getMachineByName = `-- name: GetMachineByName :one
SELECT id, name, stack_root, reported_hostname, first_seen, last_seen FROM machines WHERE name = ?
`

func (q *Queries) GetMachineByName(ctx context.Context, name string) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachineByName, name)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StackRoot,
		&i.ReportedHostname,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, name, stack_root, reported_hostname, first_seen, last_seen FROM machines ORDER BY name
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StackRoot,
			&i.ReportedHostname,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameMachine = `-- name: RenameMachine :execrows
UPDATE machines SET name = ? WHERE id = ?
`

type RenameMachineParams struct {
	Name string
	ID   string
}

func (q *Queries) RenameMachine(ctx context.Context, arg RenameMachineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameMachine, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setMachineStackRoot = `-- name: SetMachineStackRoot :execrows
UPDATE machines SET stack_root = ? WHERE id = ?
`

type SetMachineStackRootParams struct {
	StackRoot string
	ID        string
}

func (q *Queries) SetMachineStackRoot(ctx context.Context, arg SetMachineStackRootParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setMachineStackRoot, arg.StackRoot, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchMachine = `-- name: TouchMachine :execrows
UPDATE machines SET last_seen = ?, reported_hostname = ? WHERE id = ?
`

type TouchMachineParams struct {
	LastSeen         int64
	ReportedHostname string
	ID               string
}

func (q *Queries) TouchMachine(ctx context.Context, arg TouchMachineParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, touchMachine, arg.LastSeen, arg.ReportedHostname, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
