// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memories.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createMemory = `-- name: CreateMemory :exec
INSERT INTO memories (id, workspace_id, project_id, title, when_to_use, body, always_included, version, created_by, created_at, updated_by, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMemoryParams struct {
	ID             string
	WorkspaceID    string
	ProjectID      sql.NullString
	Title          string
	WhenToUse      string
	Body           string
	AlwaysIncluded int64
	Version        int64
	CreatedBy      string
	CreatedAt      int64
	UpdatedBy      string
	UpdatedAt      int64
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) error {
	_, err := q.db.ExecContext(ctx, createMemory,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.Title,
		arg.WhenToUse,
		arg.Body,
		arg.AlwaysIncluded,
		arg.Version,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedBy,
		arg.UpdatedAt,
	)
	return err
}

const deleteMemory = `-- name: DeleteMemory :execrows
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMemory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMemory = `-- name: GetMemory :one
SELECT id, workspace_id, project_id, title, when_to_use, body, always_included, version, created_by, created_at, updated_by, updated_at FROM memories WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.Title,
		&i.WhenToUse,
		&i.Body,
		&i.AlwaysIncluded,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemoryVersion = `-- name: GetMemoryVersion :one
SELECT id, memory_id, version, title, when_to_use, body, always_included, author_id, author_via, created_at
FROM memory_versions WHERE memory_id = ? AND version = ?
`

type GetMemoryVersionParams struct {
	MemoryID string
	Version  int64
}

func (q *Queries) GetMemoryVersion(ctx context.Context, arg GetMemoryVersionParams) (MemoryVersion, error) {
	row := q.db.QueryRowContext(ctx, getMemoryVersion, arg.MemoryID, arg.Version)
	var i MemoryVersion
	err := row.Scan(
		&i.ID,
		&i.MemoryID,
		&i.Version,
		&i.Title,
		&i.WhenToUse,
		&i.Body,
		&i.AlwaysIncluded,
		&i.AuthorID,
		&i.AuthorVia,
		&i.CreatedAt,
	)
	return i, err
}

const insertMemoryVersion = `-- name: InsertMemoryVersion :exec
INSERT INTO memory_versions (id, memory_id, version, title, when_to_use, body, always_included, author_id, author_via, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMemoryVersionParams struct {
	ID             string
	MemoryID       string
	Version        int64
	Title          string
	WhenToUse      string
	Body           string
	AlwaysIncluded int64
	AuthorID       string
	AuthorVia      string
	CreatedAt      int64
}

func (q *Queries) InsertMemoryVersion(ctx context.Context, arg InsertMemoryVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertMemoryVersion,
		arg.ID,
		arg.MemoryID,
		arg.Version,
		arg.Title,
		arg.WhenToUse,
		arg.Body,
		arg.AlwaysIncluded,
		arg.AuthorID,
		arg.AuthorVia,
		arg.CreatedAt,
	)
	return err
}

const listMemoriesByProject = `-- name: ListMemoriesByProject :many
SELECT id, workspace_id, project_id, title, when_to_use, body, always_included, version, created_by, created_at, updated_by, updated_at FROM memories
WHERE project_id = ? OR (project_id IS NULL AND workspace_id = ?)
ORDER BY project_id IS NOT NULL, project_id, created_at
`

type ListMemoriesByProjectParams struct {
	ProjectID   sql.NullString
	WorkspaceID string
}

// The project's own memories plus its workspace's workspace-scoped ones, workspace-scoped first.
func (q *Queries) ListMemoriesByProject(ctx context.Context, arg ListMemoriesByProjectParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesByProject, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Title,
			&i.WhenToUse,
			&i.Body,
			&i.AlwaysIncluded,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByWorkspace = `-- name: ListMemoriesByWorkspace :many
SELECT id, workspace_id, project_id, title, when_to_use, body, always_included, version, created_by, created_at, updated_by, updated_at FROM memories WHERE workspace_id = ? ORDER BY project_id IS NOT NULL, project_id, created_at
`

func (q *Queries) ListMemoriesByWorkspace(ctx context.Context, workspaceID string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Title,
			&i.WhenToUse,
			&i.Body,
			&i.AlwaysIncluded,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryVersions = `-- name: ListMemoryVersions :many
SELECT id, memory_id, version, title, when_to_use, body, always_included, author_id, author_via, created_at
FROM memory_versions WHERE memory_id = ? ORDER BY version DESC
`

func (q *Queries) ListMemoryVersions(ctx context.Context, memoryID string) ([]MemoryVersion, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryVersions, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryVersion
	for rows.Next() {
		var i MemoryVersion
		if err := rows.Scan(
			&i.ID,
			&i.MemoryID,
			&i.Version,
			&i.Title,
			&i.WhenToUse,
			&i.Body,
			&i.AlwaysIncluded,
			&i.AuthorID,
			&i.AuthorVia,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceScopedMemories = `-- name: ListWorkspaceScopedMemories :many
SELECT id, workspace_id, project_id, title, when_to_use, body, always_included, version, created_by, created_at, updated_by, updated_at FROM memories WHERE workspace_id = ? AND project_id IS NULL ORDER BY created_at
`

func (q *Queries) ListWorkspaceScopedMemories(ctx context.Context, workspaceID string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceScopedMemories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Memory
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.Title,
			&i.WhenToUse,
			&i.Body,
			&i.AlwaysIncluded,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :execrows
UPDATE memories SET title = ?, when_to_use = ?, body = ?, always_included = ?, version = ?, updated_by = ?, updated_at = ? WHERE id = ?
`

type UpdateMemoryParams struct {
	Title          string
	WhenToUse      string
	Body           string
	AlwaysIncluded int64
	Version        int64
	UpdatedBy      string
	UpdatedAt      int64
	ID             string
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMemory,
		arg.Title,
		arg.WhenToUse,
		arg.Body,
		arg.AlwaysIncluded,
		arg.Version,
		arg.UpdatedBy,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
