// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type Allowlist struct {
	Login   string
	AddedAt int64
}

type Attachment struct {
	ID             string
	DocID          sql.NullString
	TicketID       sql.NullString
	ConversationID sql.NullString
	MemoryID       sql.NullString
	Name           string
	ContentType    string
	Size           int64
	Data           []byte
	UploadedBy     string
	CreatedAt      int64
}

type AuditLog struct {
	ID        string
	ActorType string
	ActorID   string
	TokenID   sql.NullString
	Action    string
	CreatedAt int64
}

type Automation struct {
	ID             string
	Name           string
	Description    string
	Kind           string
	Enabled        int64
	Subscriptions  []byte
	ConfigSchema   []byte
	ConfigValues   []byte
	Scopes         []byte
	TokenHash      string
	TokenPrefix    string
	TokenRevokedAt sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
	CreatedBy      string
}

type AutomationCursor struct {
	AutomationID  string
	LastCreatedAt int64
	LastEventID   string
	UpdatedAt     int64
}

type AutomationRun struct {
	ID           string
	AutomationID string
	EventTopic   string
	EventID      string
	Outcome      string
	Error        string
	StartedAt    int64
	FinishedAt   int64
	DurationMs   int64
	Logs         string
	CreatedAt    int64
}

type AutomationSecret struct {
	Name      string
	Value     string
	CreatedAt int64
	UpdatedAt int64
}

type AutomationVersion struct {
	ID           string
	AutomationID string
	Sequence     int64
	Code         []byte
	PusherID     string
	Message      string
	Status       string
	CreatedAt    int64
}

type Category struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	CreatedAt int64
	UpdatedAt int64
	Color     string
}

type CodeReview struct {
	ID        string
	PrNumber  int64
	Repo      string
	Status    string
	Reviewer  string
	CreatedAt int64
}

type CollabSession struct {
	DocID        string
	LastSeq      int64
	LastCommitAt int64
}

type CollabUpdate struct {
	DocID     string
	Seq       int64
	Kind      string
	ActorID   string
	Payload   string
	CreatedAt int64
}

type ConnectorAppConfig struct {
	ConnectorID  string
	ClientID     string
	ClientSecret string
	BaseUrl      string
	AppSlug      string
}

type ConnectorCredential struct {
	ConnectorID  string
	AccessToken  string
	RefreshToken string
	ExpiresAt    int64
	ConnectedBy  string
	ConnectedAt  int64
	ManualFields string
}

type Conversation struct {
	ID              string
	WorkspaceID     string
	Kind            string
	Name            string
	TicketID        sql.NullString
	ParentMessageID string
	CreatedBy       string
	CreatedAt       int64
	UpdatedAt       int64
	AgentThreadID   string
	AgentSyncedAt   int64
	DocID           sql.NullString
}

type ConversationParticipant struct {
	ConversationID string
	UserID         string
	CreatedAt      int64
}

type ConversationUnreadState struct {
	UserID         string
	ConversationID string
	LastReadAt     int64
}

type DeadLetter struct {
	ID        string
	Topic     string
	Payload   []byte
	Error     string
	Attempts  int64
	CreatedAt int64
}

type Deploy struct {
	ID          string
	Service     string
	Target      string
	Image       string
	Status      string
	Strategy    string
	CreatedAt   int64
	UpdatedAt   int64
	StackID     sql.NullString
	ServiceID   string
	TriggeredBy string
	RuleID      string
	RuleName    string
	TicketID    string
	PrNumber    int64
	Kind        string
	Address     string
}

type DeployLogLine struct {
	Seq      int64
	DeployID string
	Ts       int64
	Phase    string
	Line     string
}

type DnsAccessServiceToken struct {
	ID           int64
	TokenID      string
	ClientID     string
	ClientSecret string
	CreatedAt    int64
	UpdatedAt    int64
}

type DnsExposure struct {
	ID        string
	GatewayID string
	Hostname  string
	Service   string
	Port      int64
	ZoneID    string
	Zone      string
	RecordID  string
	CreatedAt int64
	UpdatedAt int64
	ServiceID sql.NullString
}

type DnsGateway struct {
	ID            string
	Kind          string
	DockerNetwork string
	ServiceID     string
	ServiceName   string
	TunnelID      string
	ZoneID        string
	Zone          string
	ServerAddress string
	CreatedAt     int64
	UpdatedAt     int64
	Networks      string
	Machine       string
}

type DnsServiceHostname struct {
	Service   string
	Hostname  string
	ZoneID    string
	Zone      string
	RecordID  string
	Type      string
	Content   string
	CreatedAt int64
}

type DnsTunnel struct {
	ID             string
	Name           string
	AccountID      string
	Status         string
	Hostname       string
	ZoneID         string
	Zone           string
	RecordID       string
	Service        string
	AgentServiceID string
	Token          string
	CreatedAt      int64
	UpdatedAt      int64
}

type Doc struct {
	ID        string
	Title     string
	Body      string
	Version   int64
	CreatedAt int64
	UpdatedAt int64
	Archived  int64
	BodyMd    string
	ProjectID sql.NullString
}

type DocVersion struct {
	DocID     string
	Version   int64
	Title     string
	Body      string
	CreatedAt int64
	Name      string
	AuthorID  string
}

type DocsFt struct {
	Title  string
	BodyMd string
}

type EventSchema struct {
	Topic     string
	Version   int64
	Schema    string
	CreatedAt int64
}

type InstanceSetting struct {
	ID                       int64
	InstanceUrl              string
	SettingsVersion          int64
	UpdatedAt                int64
	GithubOauthClientID      string
	GithubOauthClientSecret  string
	MentionChipTemplate      string
	GoogleOauthClientID      string
	GoogleOauthClientSecret  string
	DiscordOauthClientID     string
	DiscordOauthClientSecret string
	RunnerSecret             string
}

type InstanceUpgrade struct {
	ID          string
	FromVersion string
	ToVersion   string
	Status      string
	Error       string
	RequestedBy string
	RunnerID    string
	CreatedAt   int64
	UpdatedAt   int64
}

type IntegrationDelivery struct {
	ID            string
	InstallID     string
	Topic         string
	EventID       string
	Payload       []byte
	Signature     string
	Url           string
	Status        string
	Attempts      int64
	NextAttemptAt int64
	CreatedAt     int64
	DeliveredAt   sql.NullInt64
}

type IntegrationInstall struct {
	ID            string
	Name          string
	TrustTier     string
	WebhookUrl    string
	WebhookSecret string
	Scopes        string
	CreatedBy     string
	CreatedAt     int64
	RevokedAt     sql.NullInt64
}

type IntegrationSubscription struct {
	InstallID string
	Topic     string
	CreatedAt int64
}

type IntegrationToken struct {
	ID         string
	InstallID  string
	TokenHash  string
	Prefix     string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	RevokedAt  sql.NullInt64
}

type Invitation struct {
	ID         string
	TokenHash  string
	InvitedBy  string
	CreatedAt  int64
	ExpiresAt  int64
	RedeemedAt sql.NullInt64
	RedeemedBy sql.NullString
}

type InvitationGrant struct {
	InvitationID string
	WorkspaceID  string
	RoleID       string
	AllowJson    string
	DenyJson     string
}

type InvitationOauthHandoff struct {
	ID             string
	InvitationID   string
	OauthStateHash sql.NullString
	AcceptanceHash sql.NullString
	Provider       string
	ProviderUserID sql.NullString
	Login          sql.NullString
	Name           sql.NullString
	AvatarUrl      sql.NullString
	ExistingUserID sql.NullString
	AdmittedUserID sql.NullString
	CompletedAt    sql.NullInt64
	CreatedAt      int64
	ExpiresAt      int64
}

type LabelColor struct {
	ProjectID string
	Label     string
	Color     string
	CreatedAt int64
	UpdatedAt int64
}

type Machine struct {
	ID               string
	Name             string
	StackRoot        string
	ReportedHostname string
	FirstSeen        int64
	LastSeen         int64
}

type Memory struct {
	ID             string
	WorkspaceID    string
	ProjectID      sql.NullString
	Title          string
	WhenToUse      string
	Body           string
	AlwaysIncluded int64
	Version        int64
	CreatedBy      string
	CreatedAt      int64
	UpdatedBy      string
	UpdatedAt      int64
}

type MemoryVersion struct {
	ID             string
	MemoryID       string
	Version        int64
	Title          string
	WhenToUse      string
	Body           string
	AlwaysIncluded int64
	AuthorID       string
	AuthorVia      string
	CreatedAt      int64
}

type Message struct {
	ID             string
	ConversationID string
	AuthorID       string
	Body           string
	Mentions       string
	AttachmentID   sql.NullString
	EditedAt       sql.NullInt64
	DeletedAt      sql.NullInt64
	CreatedAt      int64
	UpdatedAt      int64
	AuthorKind     string
}

type Notification struct {
	ID           string
	UserID       string
	Kind         string
	SubjectType  string
	SubjectID    string
	SubjectTitle string
	Read         int64
	CreatedAt    int64
}

type Outbox struct {
	ID        string
	Topic     string
	Payload   []byte
	CreatedAt int64
	Published int64
}

type PairingComputer struct {
	ID                string
	UserID            string
	Name              string
	ServerUrl         string
	BearerToken       string
	TokenExpiresAt    int64
	HarnessVersion    string
	CreatedAt         int64
	UpdatedAt         int64
	Kind              string
	SetupConfirmedAt  sql.NullInt64
	TunnelID          string
	TunnelHostname    string
	TunnelZoneID      string
	TunnelRecordID    string
	TunnelAccessAppID string
}

type PairingProjectLink struct {
	ProjectID        string
	ComputerID       string
	HarnessProjectID string
	Provider         string
	Model            string
	UpdatedAt        int64
}

type PairingProviderSetup struct {
	ComputerID  string
	Provider    string
	ConfirmedAt sql.NullInt64
	SkillsJson  string
	UpdatedAt   int64
}

type PairingUserDefault struct {
	UserID            string
	DefaultComputerID sql.NullString
	FallbackProjectID string
	Provider          string
	Model             string
}

type PermissionOverwrite struct {
	ResourceType string
	ResourceID   string
	UserID       string
	Allow        string
	Deny         string
	CreatedAt    int64
	UpdatedAt    int64
}

type PersonalAccessToken struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	CreatedAt  int64
	LastUsedAt sql.NullInt64
	RevokedAt  sql.NullInt64
}

type Play struct {
	ID                 string
	WorkspaceID        string
	Label              string
	Type               string
	Description        string
	Instructions       string
	Enabled            int64
	ShowWhenStage      sql.NullString
	ExcludedProjectIds string
	CreatedBy          string
	CreatedAt          int64
	UpdatedAt          int64
}

type PlayTrail struct {
	ID                 string
	WorkspaceID        string
	PlayID             string
	PlayLabel          string
	TargetType         string
	TargetID           string
	ProjectID          string
	ConversationID     string
	StarterID          string
	Via                string
	SelectedMemoryIds  string
	CustomInstructions string
	MoveToStatusID     sql.NullString
	HarnessSessionID   string
	State              string
	StartedAt          int64
	EndedAt            sql.NullInt64
	LastError          string
	ReplyMessageID     string
	Activity           string
	ComputerID         string
	Provider           string
	Model              string
	Question           sql.NullString
}

type ProcessedEvent struct {
	EventID     string
	ProcessedAt int64
}

type Project struct {
	ID            string
	Name          string
	Prefix        string
	Position      int64
	WorkspaceID   string
	CreatedAt     int64
	UpdatedAt     int64
	Icon          string
	TestsLocation string
}

type ProjectRepo struct {
	ProjectID   string
	Owner       string
	Name        string
	FullName    string
	AddedAt     int64
	ConnectorID string
	Role        string
}

type Role struct {
	ID          string
	WorkspaceID string
	Name        string
	IsOwnerRole int64
	CreatedAt   int64
	UpdatedAt   int64
	Permissions string
}

type Runner struct {
	ID        string
	Name      string
	LastSeen  int64
	Connected int64
	CreatedAt int64
	Version   string
	MachineID string
}

type Service struct {
	ID            string
	StackID       string
	Name          string
	Declared      string
	ContainerName string
	Image         string
	Status        string
	Networks      string
	Ports         string
	ObservedAt    int64
}

type Stack struct {
	ID                string
	ProjectID         string
	Name              string
	Slug              string
	Machine           string
	Strategy          string
	ComposePath       string
	Env               string
	DockerNetwork     string
	Ports             string
	Mounts            string
	Command           string
	BuildRepoOwner    string
	BuildRepoName     string
	BuildBranch       string
	BuildDockerfile   string
	BuildComposePath  string
	BranchDeployRules string
	DerivedFrom       string
	Branch            string
	Managed           int64
	CreatedAt         int64
	UpdatedAt         int64
}

type Status struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	Kind      string
	Icon      string
	CreatedAt int64
	UpdatedAt int64
}

type Ticket struct {
	ID                     string
	Title                  string
	Body                   string
	Status                 string
	DocID                  sql.NullString
	Developer              string
	CreatedAt              int64
	UpdatedAt              int64
	ProjectID              sql.NullString
	CategoryID             sql.NullString
	TypeID                 sql.NullString
	FinishedAt             sql.NullInt64
	Position               int64
	Number                 int64
	Tester                 string
	ReporterKind           string
	ReporterLogin          string
	ReporterAutomationID   string
	ReporterAutomationName string
}

type TicketBranchLink struct {
	TicketID    string
	BranchOwner string
	BranchRepo  string
	BranchName  string
	LinkedAt    int64
}

type TicketLabel struct {
	TicketID string
	Label    string
}

type TicketLink struct {
	TicketID  string
	Kind      string
	TargetID  sql.NullString
	CreatedAt int64
}

type TicketPrLink struct {
	TicketID string
	PrOwner  string
	PrRepo   string
	PrNumber int64
	PrTitle  string
	PrSha    string
	LinkedAt int64
	PrState  string
}

type TicketType struct {
	ID           string
	ProjectID    string
	Name         string
	Position     int64
	Color        string
	CreatedAt    int64
	UpdatedAt    int64
	BodyTemplate string
}

type TicketsFt struct {
	Title string
	Body  string
}

type Topology struct {
	Environment   string
	SchemaVersion int64
	Canvas        []byte
	UpdatedAt     int64
}

type User struct {
	ID                 string
	Provider           string
	ProviderUserID     string
	Login              string
	Name               string
	AvatarUrl          string
	FirstLoginDone     int64
	CreatedAt          int64
	UpdatedAt          int64
	CanCreateWorkspace int64
	DisplayName        sql.NullString
	AvatarOverrideUrl  sql.NullString
	AccountStatus      string
}

type Workspace struct {
	ID        string
	Name      string
	CreatedAt int64
	UpdatedAt int64
}

type WorkspaceInvite struct {
	WorkspaceID string
	Login       string
	RoleID      string
	InvitedBy   string
	CreatedAt   int64
}

type WorkspaceMember struct {
	UserID      string
	WorkspaceID string
	RoleID      string
	CreatedAt   int64
}
