// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const bumpUnreadNotification = `-- name: BumpUnreadNotification :execrows
UPDATE notifications SET id = ?1, subject_title = ?2, created_at = ?3
WHERE id = (
  SELECT n.id FROM notifications n
  WHERE n.user_id = ?4 AND n.workspace_id = ?5 AND n.kind = ?6 AND n.subject_type = ?7 AND n.subject_id = ?8 AND n.read = 0 AND n.id <> ?1
  ORDER BY n.created_at DESC LIMIT 1
)
`

type BumpUnreadNotificationParams struct {
	ID           string
	SubjectTitle string
	CreatedAt    int64
	UserID       string
	WorkspaceID  string
	Kind         string
	SubjectType  string
	SubjectID    string
}

// A repeat on an unread row takes over that row under its own event's id, so it rises in the inbox and a redelivery of
// the same event finds its id taken and does nothing.
func (q *Queries) BumpUnreadNotification(ctx context.Context, arg BumpUnreadNotificationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, bumpUnreadNotification,
		arg.ID,
		arg.SubjectTitle,
		arg.CreatedAt,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.SubjectType,
		arg.SubjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countNotificationsPage = `-- name: CountNotificationsPage :one
SELECT COUNT(*)
FROM notifications n
WHERE n.user_id = ?1 AND (?2 = '' OR n.workspace_id = ?2)
  AND (NOT ?3 OR n.read = 0)
  AND (NOT ?4 OR n.workspace_id = '' OR n.workspace_id IN (SELECT value FROM json_each(?5)))
  AND (NOT ?4
       OR NOT EXISTS (SELECT 1 FROM projects p WHERE p.id NOT IN (SELECT value FROM json_each(?6)))
       OR COALESCE(CASE n.subject_type WHEN 'ticket' THEN (SELECT t.project_id FROM tickets t WHERE t.id = n.subject_id)
         WHEN 'doc' THEN (SELECT d.project_id FROM docs d WHERE d.id = n.subject_id)
         WHEN 'memory' THEN (SELECT m.project_id FROM memories m WHERE m.id = n.subject_id) END, '') IN (SELECT '' UNION ALL SELECT value FROM json_each(?6)))
`

type CountNotificationsPageParams struct {
	UserID       string
	WorkspaceID  interface{}
	UnreadOnly   interface{}
	Scoped       interface{}
	WorkspaceIds interface{}
	ProjectIds   interface{}
}

// How many notifications ListNotificationsPage pages over, under the same filters.
func (q *Queries) CountNotificationsPage(ctx context.Context, arg CountNotificationsPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationsPage,
		arg.UserID,
		arg.WorkspaceID,
		arg.UnreadOnly,
		arg.Scoped,
		arg.WorkspaceIds,
		arg.ProjectIds,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotificationsByProject = `-- name: CountUnreadNotificationsByProject :many
SELECT n.workspace_id, CAST(COALESCE(t.project_id, d.project_id, m.project_id, '') AS TEXT) AS project_id, COUNT(*) AS unread
FROM notifications n INDEXED BY idx_notifications_user_unread
LEFT JOIN docs d ON n.subject_type = 'doc' AND d.id = n.subject_id
LEFT JOIN tickets t ON n.subject_type = 'ticket' AND t.id = n.subject_id
LEFT JOIN memories m ON n.subject_type = 'memory' AND m.id = n.subject_id
WHERE n.user_id = ?1 AND n.read = 0 AND (?2 = '' OR n.workspace_id = ?2)
GROUP BY n.workspace_id, 2
`

type CountUnreadNotificationsByProjectParams struct {
	UserID      string
	WorkspaceID interface{}
}

type CountUnreadNotificationsByProjectRow struct {
	WorkspaceID string
	ProjectID   string
	Unread      int64
}

// Without table statistics SQLite reads every notification the user has, read ones included, through the inbox index.
func (q *Queries) CountUnreadNotificationsByProject(ctx context.Context, arg CountUnreadNotificationsByProjectParams) ([]CountUnreadNotificationsByProjectRow, error) {
	rows, err := q.db.QueryContext(ctx, countUnreadNotificationsByProject, arg.UserID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUnreadNotificationsByProjectRow
	for rows.Next() {
		var i CountUnreadNotificationsByProjectRow
		if err := rows.Scan(&i.WorkspaceID, &i.ProjectID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNotificationIfAbsent = `-- name: CreateNotificationIfAbsent :execrows
INSERT INTO notifications (id, user_id, workspace_id, kind, subject_type, subject_id, subject_title, read, read_at, created_at)
SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10
WHERE NOT EXISTS (
  SELECT 1 FROM notifications
  WHERE user_id = ?2 AND workspace_id = ?3 AND kind = ?4 AND subject_type = ?5 AND subject_id = ?6 AND read = 0
)
`

type CreateNotificationIfAbsentParams struct {
	ID           string
	UserID       string
	WorkspaceID  string
	Kind         string
	SubjectType  string
	SubjectID    string
	SubjectTitle string
	Read         int64
	ReadAt       sql.NullInt64
	CreatedAt    int64
}

// NOT EXISTS collapses repeats while an unread row exists in the same inbox; BumpUnreadNotification then lifts that row.
func (q *Queries) CreateNotificationIfAbsent(ctx context.Context, arg CreateNotificationIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotificationIfAbsent,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectTitle,
		arg.Read,
		arg.ReadAt,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationsCreatedBefore = `-- name: DeleteNotificationsCreatedBefore :execrows
DELETE FROM notifications WHERE created_at < ?
`

func (q *Queries) DeleteNotificationsCreatedBefore(ctx context.Context, createdAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsCreatedBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationsReadBefore = `-- name: DeleteNotificationsReadBefore :execrows
DELETE FROM notifications WHERE read_at IS NOT NULL AND read_at < ?
`

func (q *Queries) DeleteNotificationsReadBefore(ctx context.Context, readAt sql.NullInt64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsReadBefore, readAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNotificationsPage = `-- name: ListNotificationsPage :many
SELECT n.id, n.user_id, n.kind, n.subject_type, n.subject_id, n.subject_title, n.read, n.created_at, n.workspace_id, n.read_at,
       CAST(COALESCE((SELECT f.id FROM docs d JOIN doc_folders f ON f.id = d.folder_id WHERE n.subject_type = 'doc' AND d.id = n.subject_id), '') AS TEXT) AS folder_id,
       CAST(COALESCE((SELECT f.name FROM docs d JOIN doc_folders f ON f.id = d.folder_id WHERE n.subject_type = 'doc' AND d.id = n.subject_id), '') AS TEXT) AS folder_name,
       CAST(COALESCE((SELECT f.is_default FROM docs d JOIN doc_folders f ON f.id = d.folder_id WHERE n.subject_type = 'doc' AND d.id = n.subject_id), 0) AS INTEGER) AS folder_is_default,
       CAST(COALESCE(CASE n.subject_type WHEN 'ticket' THEN (SELECT t.project_id FROM tickets t WHERE t.id = n.subject_id)
         WHEN 'doc' THEN (SELECT d.project_id FROM docs d WHERE d.id = n.subject_id)
         WHEN 'memory' THEN (SELECT m.project_id FROM memories m WHERE m.id = n.subject_id) END, '') AS TEXT) AS project_id
FROM notifications n
WHERE n.user_id = ?1 AND (?2 = '' OR n.workspace_id = ?2)
  AND (NOT ?3 OR n.read = 0)
  AND (NOT ?4 OR n.workspace_id = '' OR n.workspace_id IN (SELECT value FROM json_each(?5)))
  AND (NOT ?4
       OR NOT EXISTS (SELECT 1 FROM projects p WHERE p.id NOT IN (SELECT value FROM json_each(?6)))
       OR COALESCE(CASE n.subject_type WHEN 'ticket' THEN (SELECT t.project_id FROM tickets t WHERE t.id = n.subject_id)
         WHEN 'doc' THEN (SELECT d.project_id FROM docs d WHERE d.id = n.subject_id)
         WHEN 'memory' THEN (SELECT m.project_id FROM memories m WHERE m.id = n.subject_id) END, '') IN (SELECT '' UNION ALL SELECT value FROM json_each(?6)))
ORDER BY n.created_at DESC, n.id DESC
LIMIT ?8 OFFSET ?7
`

type ListNotificationsPageParams struct {
	UserID       string
	WorkspaceID  interface{}
	UnreadOnly   interface{}
	Scoped       interface{}
	WorkspaceIds interface{}
	ProjectIds   interface{}
	PageOffset   int64
	PageLimit    int64
}

type ListNotificationsPageRow struct {
	Notification    Notification
	FolderID        string
	FolderName      string
	FolderIsDefault int64
	ProjectID       string
}

// An empty workspace_id lists every workspace. A doc's folder and the subject's project are read at read time, never
// stored on the row, because a doc or ticket can move after the notice was sent. scoped leaves out a notice from a
// workspace the reader left or about a project they cannot open (ADR 0140); when they open every project the subject is
// never looked up, and otherwise each row looks up its own subject's table only. The folder is read for the page's rows
// alone.
func (q *Queries) ListNotificationsPage(ctx context.Context, arg ListNotificationsPageParams) ([]ListNotificationsPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsPage,
		arg.UserID,
		arg.WorkspaceID,
		arg.UnreadOnly,
		arg.Scoped,
		arg.WorkspaceIds,
		arg.ProjectIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsPageRow
	for rows.Next() {
		var i ListNotificationsPageRow
		if err := rows.Scan(
			&i.Notification.ID,
			&i.Notification.UserID,
			&i.Notification.Kind,
			&i.Notification.SubjectType,
			&i.Notification.SubjectID,
			&i.Notification.SubjectTitle,
			&i.Notification.Read,
			&i.Notification.CreatedAt,
			&i.Notification.WorkspaceID,
			&i.Notification.ReadAt,
			&i.FolderID,
			&i.FolderName,
			&i.FolderIsDefault,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = 1, read_at = ?1
WHERE user_id = ?2 AND read = 0 AND (?3 = '' OR workspace_id = ?3)
`

type MarkAllNotificationsReadParams struct {
	ReadAt      sql.NullInt64
	UserID      string
	WorkspaceID interface{}
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.ReadAt, arg.UserID, arg.WorkspaceID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read = 1, read_at = COALESCE(read_at, ?1) WHERE id = ?2 AND user_id = ?3
`

type MarkNotificationReadParams struct {
	ReadAt sql.NullInt64
	ID     string
	UserID string
}

// Reading an already read row keeps its first read time, so marking it again never extends its retention.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ReadAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
