// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = ?1 AND read = 0 AND (?2 = '' OR workspace_id = ?2)
`

type CountUnreadNotificationsParams struct {
	UserID      string
	WorkspaceID interface{}
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, arg.UserID, arg.WorkspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationIfAbsent = `-- name: CreateNotificationIfAbsent :execrows
INSERT INTO notifications (id, user_id, workspace_id, kind, subject_type, subject_id, subject_title, read, created_at)
SELECT ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9
WHERE NOT EXISTS (
  SELECT 1 FROM notifications
  WHERE user_id = ?2 AND workspace_id = ?3 AND kind = ?4 AND subject_type = ?5 AND subject_id = ?6 AND read = 0
)
`

type CreateNotificationIfAbsentParams struct {
	ID           string
	UserID       string
	WorkspaceID  string
	Kind         string
	SubjectType  string
	SubjectID    string
	SubjectTitle string
	Read         int64
	CreatedAt    int64
}

// NOT EXISTS collapses repeats while an unread row exists in the same inbox, so rapid edits don't flood it.
func (q *Queries) CreateNotificationIfAbsent(ctx context.Context, arg CreateNotificationIfAbsentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotificationIfAbsent,
		arg.ID,
		arg.UserID,
		arg.WorkspaceID,
		arg.Kind,
		arg.SubjectType,
		arg.SubjectID,
		arg.SubjectTitle,
		arg.Read,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, kind, subject_type, subject_id, subject_title, read, created_at, workspace_id FROM notifications
WHERE user_id = ?1 AND (?2 = '' OR workspace_id = ?2)
ORDER BY created_at DESC LIMIT ?3
`

type ListNotificationsParams struct {
	UserID      string
	WorkspaceID interface{}
	Limit       int64
}

// An empty workspace_id lists every workspace, the unscoped inbox older clients still ask for.
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SubjectType,
			&i.SubjectID,
			&i.SubjectTitle,
			&i.Read,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = 1
WHERE user_id = ?1 AND read = 0 AND (?2 = '' OR workspace_id = ?2)
`

type MarkAllNotificationsReadParams struct {
	UserID      string
	WorkspaceID interface{}
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, arg.UserID, arg.WorkspaceID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read = 1 WHERE id = ? AND user_id = ?
`

type MarkNotificationReadParams struct {
	ID     string
	UserID string
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
