// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"
)

const enqueueOutbox = `-- name: EnqueueOutbox :exec
INSERT INTO outbox (id, topic, payload) VALUES (?, ?, ?)
`

type EnqueueOutboxParams struct {
	ID      string
	Topic   string
	Payload []byte
}

func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutbox, arg.ID, arg.Topic, arg.Payload)
	return err
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, topic, payload, created_at FROM outbox WHERE published = 0 ORDER BY created_at LIMIT ?
`

type ListUnpublishedOutboxRow struct {
	ID        string
	Topic     string
	Payload   []byte
	CreatedAt int64
}

func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int64) ([]ListUnpublishedOutboxRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpublishedOutboxRow
	for rows.Next() {
		var i ListUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :execrows
UPDATE outbox SET published = 1 WHERE id = ?
`

func (q *Queries) MarkOutboxPublished(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxPublished, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
