// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pairing.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deletePairingComputer = `-- name: DeletePairingComputer :execrows
DELETE FROM pairing_computers WHERE id = ? AND user_id = ?
`

type DeletePairingComputerParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeletePairingComputer(ctx context.Context, arg DeletePairingComputerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePairingComputer, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePairingProjectLink = `-- name: DeletePairingProjectLink :exec
DELETE FROM pairing_project_links WHERE project_id = ?
`

func (q *Queries) DeletePairingProjectLink(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deletePairingProjectLink, projectID)
	return err
}

const getPairingComputer = `-- name: GetPairingComputer :one
SELECT id, user_id, name, server_url, bearer_token, token_expires_at, harness_version, created_at, updated_at, kind, setup_confirmed_at FROM pairing_computers WHERE id = ? AND user_id = ?
`

type GetPairingComputerParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetPairingComputer(ctx context.Context, arg GetPairingComputerParams) (PairingComputer, error) {
	row := q.db.QueryRowContext(ctx, getPairingComputer, arg.ID, arg.UserID)
	var i PairingComputer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ServerUrl,
		&i.BearerToken,
		&i.TokenExpiresAt,
		&i.HarnessVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SetupConfirmedAt,
	)
	return i, err
}

const getPairingComputerByID = `-- name: GetPairingComputerByID :one
SELECT id, user_id, name, server_url, bearer_token, token_expires_at, harness_version, created_at, updated_at, kind, setup_confirmed_at FROM pairing_computers WHERE id = ?
`

func (q *Queries) GetPairingComputerByID(ctx context.Context, id string) (PairingComputer, error) {
	row := q.db.QueryRowContext(ctx, getPairingComputerByID, id)
	var i PairingComputer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ServerUrl,
		&i.BearerToken,
		&i.TokenExpiresAt,
		&i.HarnessVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Kind,
		&i.SetupConfirmedAt,
	)
	return i, err
}

const getPairingDefaults = `-- name: GetPairingDefaults :one
SELECT default_computer_id, fallback_project_id, provider, model FROM pairing_user_defaults WHERE user_id = ?
`

type GetPairingDefaultsRow struct {
	DefaultComputerID sql.NullString
	FallbackProjectID string
	Provider          string
	Model             string
}

func (q *Queries) GetPairingDefaults(ctx context.Context, userID string) (GetPairingDefaultsRow, error) {
	row := q.db.QueryRowContext(ctx, getPairingDefaults, userID)
	var i GetPairingDefaultsRow
	err := row.Scan(
		&i.DefaultComputerID,
		&i.FallbackProjectID,
		&i.Provider,
		&i.Model,
	)
	return i, err
}

const getPairingProjectLink = `-- name: GetPairingProjectLink :one
SELECT project_id, computer_id, harness_project_id, provider, model, updated_at FROM pairing_project_links WHERE project_id = ?
`

func (q *Queries) GetPairingProjectLink(ctx context.Context, projectID string) (PairingProjectLink, error) {
	row := q.db.QueryRowContext(ctx, getPairingProjectLink, projectID)
	var i PairingProjectLink
	err := row.Scan(
		&i.ProjectID,
		&i.ComputerID,
		&i.HarnessProjectID,
		&i.Provider,
		&i.Model,
		&i.UpdatedAt,
	)
	return i, err
}

const listPairingComputers = `-- name: ListPairingComputers :many
SELECT id, user_id, name, server_url, bearer_token, token_expires_at, harness_version, created_at, updated_at, kind, setup_confirmed_at FROM pairing_computers WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPairingComputers(ctx context.Context, userID string) ([]PairingComputer, error) {
	rows, err := q.db.QueryContext(ctx, listPairingComputers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PairingComputer
	for rows.Next() {
		var i PairingComputer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ServerUrl,
			&i.BearerToken,
			&i.TokenExpiresAt,
			&i.HarnessVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Kind,
			&i.SetupConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPairingProviderSetups = `-- name: ListPairingProviderSetups :many
SELECT computer_id, provider, confirmed_at, skills_json, updated_at FROM pairing_provider_setups WHERE computer_id = ? ORDER BY provider
`

func (q *Queries) ListPairingProviderSetups(ctx context.Context, computerID string) ([]PairingProviderSetup, error) {
	rows, err := q.db.QueryContext(ctx, listPairingProviderSetups, computerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PairingProviderSetup
	for rows.Next() {
		var i PairingProviderSetup
		if err := rows.Scan(
			&i.ComputerID,
			&i.Provider,
			&i.ConfirmedAt,
			&i.SkillsJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePairingComputer = `-- name: SavePairingComputer :exec
INSERT INTO pairing_computers (id, user_id, kind, name, server_url, bearer_token, token_expires_at, harness_version, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind, name = excluded.name, server_url = excluded.server_url, bearer_token = excluded.bearer_token,
  token_expires_at = excluded.token_expires_at, harness_version = excluded.harness_version, updated_at = excluded.updated_at
`

type SavePairingComputerParams struct {
	ID             string
	UserID         string
	Kind           string
	Name           string
	ServerUrl      string
	BearerToken    string
	TokenExpiresAt int64
	HarnessVersion string
	CreatedAt      int64
	UpdatedAt      int64
}

func (q *Queries) SavePairingComputer(ctx context.Context, arg SavePairingComputerParams) error {
	_, err := q.db.ExecContext(ctx, savePairingComputer,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Name,
		arg.ServerUrl,
		arg.BearerToken,
		arg.TokenExpiresAt,
		arg.HarnessVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const savePairingDefaults = `-- name: SavePairingDefaults :exec
INSERT INTO pairing_user_defaults (user_id, default_computer_id, fallback_project_id, provider, model)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
  default_computer_id = excluded.default_computer_id, fallback_project_id = excluded.fallback_project_id,
  provider = excluded.provider, model = excluded.model
`

type SavePairingDefaultsParams struct {
	UserID            string
	DefaultComputerID sql.NullString
	FallbackProjectID string
	Provider          string
	Model             string
}

func (q *Queries) SavePairingDefaults(ctx context.Context, arg SavePairingDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, savePairingDefaults,
		arg.UserID,
		arg.DefaultComputerID,
		arg.FallbackProjectID,
		arg.Provider,
		arg.Model,
	)
	return err
}

const savePairingProjectLink = `-- name: SavePairingProjectLink :exec
INSERT INTO pairing_project_links (project_id, computer_id, harness_project_id, provider, model, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET
  computer_id = excluded.computer_id, harness_project_id = excluded.harness_project_id,
  provider = excluded.provider, model = excluded.model, updated_at = excluded.updated_at
`

type SavePairingProjectLinkParams struct {
	ProjectID        string
	ComputerID       string
	HarnessProjectID string
	Provider         string
	Model            string
	UpdatedAt        int64
}

func (q *Queries) SavePairingProjectLink(ctx context.Context, arg SavePairingProjectLinkParams) error {
	_, err := q.db.ExecContext(ctx, savePairingProjectLink,
		arg.ProjectID,
		arg.ComputerID,
		arg.HarnessProjectID,
		arg.Provider,
		arg.Model,
		arg.UpdatedAt,
	)
	return err
}

const savePairingProviderSetup = `-- name: SavePairingProviderSetup :exec
INSERT INTO pairing_provider_setups (computer_id, provider, confirmed_at, skills_json, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(computer_id, provider) DO UPDATE SET
  confirmed_at = excluded.confirmed_at, skills_json = excluded.skills_json, updated_at = excluded.updated_at
`

type SavePairingProviderSetupParams struct {
	ComputerID  string
	Provider    string
	ConfirmedAt sql.NullInt64
	SkillsJson  string
	UpdatedAt   int64
}

func (q *Queries) SavePairingProviderSetup(ctx context.Context, arg SavePairingProviderSetupParams) error {
	_, err := q.db.ExecContext(ctx, savePairingProviderSetup,
		arg.ComputerID,
		arg.Provider,
		arg.ConfirmedAt,
		arg.SkillsJson,
		arg.UpdatedAt,
	)
	return err
}

const setPairingComputerSetupConfirmedAt = `-- name: SetPairingComputerSetupConfirmedAt :execrows
UPDATE pairing_computers SET setup_confirmed_at = ? WHERE id = ? AND user_id = ?
`

type SetPairingComputerSetupConfirmedAtParams struct {
	SetupConfirmedAt sql.NullInt64
	ID               string
	UserID           string
}

func (q *Queries) SetPairingComputerSetupConfirmedAt(ctx context.Context, arg SetPairingComputerSetupConfirmedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setPairingComputerSetupConfirmedAt, arg.SetupConfirmedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
