// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pats.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPAT = `-- name: CreatePAT :exec
INSERT INTO personal_access_tokens (id, user_id, name, token_hash, prefix, created_at, computer_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePATParams struct {
	ID         string
	UserID     string
	Name       string
	TokenHash  string
	Prefix     string
	CreatedAt  int64
	ComputerID string
}

func (q *Queries) CreatePAT(ctx context.Context, arg CreatePATParams) error {
	_, err := q.db.ExecContext(ctx, createPAT,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.CreatedAt,
		arg.ComputerID,
	)
	return err
}

const getActiveComputerPAT = `-- name: GetActiveComputerPAT :one
SELECT id, user_id, name, token_hash, prefix, created_at, last_used_at, revoked_at, computer_id FROM personal_access_tokens
WHERE user_id = ? AND computer_id = ? AND computer_id != '' AND revoked_at IS NULL
`

type GetActiveComputerPATParams struct {
	UserID     string
	ComputerID string
}

func (q *Queries) GetActiveComputerPAT(ctx context.Context, arg GetActiveComputerPATParams) (PersonalAccessToken, error) {
	row := q.db.QueryRowContext(ctx, getActiveComputerPAT, arg.UserID, arg.ComputerID)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ComputerID,
	)
	return i, err
}

const getPATByHash = `-- name: GetPATByHash :one
SELECT id, user_id, name, token_hash, prefix, created_at, last_used_at, revoked_at, computer_id FROM personal_access_tokens WHERE token_hash = ?
`

func (q *Queries) GetPATByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRowContext(ctx, getPATByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.ComputerID,
	)
	return i, err
}

const listPATsByUser = `-- name: ListPATsByUser :many
SELECT id, user_id, name, token_hash, prefix, created_at, last_used_at, revoked_at, computer_id FROM personal_access_tokens WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPATsByUser(ctx context.Context, userID string) ([]PersonalAccessToken, error) {
	rows, err := q.db.QueryContext(ctx, listPATsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.ComputerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePAT = `-- name: RevokePAT :execrows
UPDATE personal_access_tokens SET revoked_at = ? WHERE id = ? AND user_id = ? AND revoked_at IS NULL
`

type RevokePATParams struct {
	RevokedAt sql.NullInt64
	ID        string
	UserID    string
}

func (q *Queries) RevokePAT(ctx context.Context, arg RevokePATParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePAT, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchPATLastUsed = `-- name: TouchPATLastUsed :exec
UPDATE personal_access_tokens SET last_used_at = ? WHERE id = ? AND revoked_at IS NULL
`

type TouchPATLastUsedParams struct {
	LastUsedAt sql.NullInt64
	ID         string
}

func (q *Queries) TouchPATLastUsed(ctx context.Context, arg TouchPATLastUsedParams) error {
	_, err := q.db.ExecContext(ctx, touchPATLastUsed, arg.LastUsedAt, arg.ID)
	return err
}
