// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_queue.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countActivePlayTrailsByStarter = `-- name: CountActivePlayTrailsByStarter :one
SELECT COUNT(*) FROM play_trails WHERE starter_id = ? AND state IN ('starting', 'running', 'waiting')
`

func (q *Queries) CountActivePlayTrailsByStarter(ctx context.Context, starterID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActivePlayTrailsByStarter, starterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayQueueStarted = `-- name: CountPlayQueueStarted :one
SELECT COUNT(*) AS started, MIN(q.decided_at) AS oldest FROM play_queue q
WHERE q.target_type = ?1 AND q.target_id = ?2 AND q.status = 'started'
  AND q.decided_at >= MAX(?3, COALESCE(
      (SELECT resumed_at FROM play_queue_resumes r WHERE r.target_type = ?1 AND r.target_id = ?2), 0))
`

type CountPlayQueueStartedParams struct {
	TargetType string
	TargetID   string
	Since      interface{}
}

type CountPlayQueueStartedRow struct {
	Started int64
	Oldest  interface{}
}

func (q *Queries) CountPlayQueueStarted(ctx context.Context, arg CountPlayQueueStartedParams) (CountPlayQueueStartedRow, error) {
	row := q.db.QueryRowContext(ctx, countPlayQueueStarted, arg.TargetType, arg.TargetID, arg.Since)
	var i CountPlayQueueStartedRow
	err := row.Scan(&i.Started, &i.Oldest)
	return i, err
}

const getPlayQueueItem = `-- name: GetPlayQueueItem :one
SELECT id, workspace_id, project_id, target_type, target_id, play_id, play_label, auto_play_id, person_id, run_on, moment, via, priority, status, reason, trail_id, queued_at, decided_at, not_before FROM play_queue WHERE id = ?
`

func (q *Queries) GetPlayQueueItem(ctx context.Context, id string) (PlayQueue, error) {
	row := q.db.QueryRowContext(ctx, getPlayQueueItem, id)
	var i PlayQueue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ProjectID,
		&i.TargetType,
		&i.TargetID,
		&i.PlayID,
		&i.PlayLabel,
		&i.AutoPlayID,
		&i.PersonID,
		&i.RunOn,
		&i.Moment,
		&i.Via,
		&i.Priority,
		&i.Status,
		&i.Reason,
		&i.TrailID,
		&i.QueuedAt,
		&i.DecidedAt,
		&i.NotBefore,
	)
	return i, err
}

const insertPlayQueueItem = `-- name: InsertPlayQueueItem :execrows
INSERT INTO play_queue (id, workspace_id, project_id, target_type, target_id, play_id, play_label, auto_play_id, person_id, run_on, moment, via, priority, status, reason, trail_id, queued_at, decided_at, not_before)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type InsertPlayQueueItemParams struct {
	ID          string
	WorkspaceID string
	ProjectID   string
	TargetType  string
	TargetID    string
	PlayID      string
	PlayLabel   string
	AutoPlayID  string
	PersonID    string
	RunOn       string
	Moment      string
	Via         string
	Priority    int64
	Status      string
	Reason      string
	TrailID     string
	QueuedAt    int64
	DecidedAt   sql.NullInt64
	NotBefore   int64
}

func (q *Queries) InsertPlayQueueItem(ctx context.Context, arg InsertPlayQueueItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPlayQueueItem,
		arg.ID,
		arg.WorkspaceID,
		arg.ProjectID,
		arg.TargetType,
		arg.TargetID,
		arg.PlayID,
		arg.PlayLabel,
		arg.AutoPlayID,
		arg.PersonID,
		arg.RunOn,
		arg.Moment,
		arg.Via,
		arg.Priority,
		arg.Status,
		arg.Reason,
		arg.TrailID,
		arg.QueuedAt,
		arg.DecidedAt,
		arg.NotBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDuePlayQueue = `-- name: ListDuePlayQueue :many
SELECT id, workspace_id, project_id, target_type, target_id, play_id, play_label, auto_play_id, person_id, run_on, moment, via, priority, status, reason, trail_id, queued_at, decided_at, not_before FROM play_queue WHERE status = 'queued' AND person_id = ? AND not_before <= ?
ORDER BY priority DESC, queued_at, id
`

type ListDuePlayQueueParams struct {
	PersonID  string
	NotBefore int64
}

func (q *Queries) ListDuePlayQueue(ctx context.Context, arg ListDuePlayQueueParams) ([]PlayQueue, error) {
	rows, err := q.db.QueryContext(ctx, listDuePlayQueue, arg.PersonID, arg.NotBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayQueue
	for rows.Next() {
		var i PlayQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.PlayID,
			&i.PlayLabel,
			&i.AutoPlayID,
			&i.PersonID,
			&i.RunOn,
			&i.Moment,
			&i.Via,
			&i.Priority,
			&i.Status,
			&i.Reason,
			&i.TrailID,
			&i.QueuedAt,
			&i.DecidedAt,
			&i.NotBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayQueueByTarget = `-- name: ListPlayQueueByTarget :many
SELECT id, workspace_id, project_id, target_type, target_id, play_id, play_label, auto_play_id, person_id, run_on, moment, via, priority, status, reason, trail_id, queued_at, decided_at, not_before FROM play_queue WHERE target_type = ? AND target_id = ? ORDER BY queued_at DESC, id DESC
`

type ListPlayQueueByTargetParams struct {
	TargetType string
	TargetID   string
}

func (q *Queries) ListPlayQueueByTarget(ctx context.Context, arg ListPlayQueueByTargetParams) ([]PlayQueue, error) {
	rows, err := q.db.QueryContext(ctx, listPlayQueueByTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayQueue
	for rows.Next() {
		var i PlayQueue
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ProjectID,
			&i.TargetType,
			&i.TargetID,
			&i.PlayID,
			&i.PlayLabel,
			&i.AutoPlayID,
			&i.PersonID,
			&i.RunOn,
			&i.Moment,
			&i.Via,
			&i.Priority,
			&i.Status,
			&i.Reason,
			&i.TrailID,
			&i.QueuedAt,
			&i.DecidedAt,
			&i.NotBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayQueuePeople = `-- name: ListPlayQueuePeople :many
SELECT DISTINCT person_id FROM play_queue WHERE status = 'queued' AND not_before <= ?
`

func (q *Queries) ListPlayQueuePeople(ctx context.Context, notBefore int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlayQueuePeople, notBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var person_id string
		if err := rows.Scan(&person_id); err != nil {
			return nil, err
		}
		items = append(items, person_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPlayQueueNotBefore = `-- name: NextPlayQueueNotBefore :one
SELECT MIN(not_before) FROM play_queue WHERE status = 'queued' AND not_before > ?
`

func (q *Queries) NextPlayQueueNotBefore(ctx context.Context, notBefore int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, nextPlayQueueNotBefore, notBefore)
	var min interface{}
	err := row.Scan(&min)
	return min, err
}

const playQueueQueuedSince = `-- name: PlayQueueQueuedSince :one
SELECT EXISTS (
    SELECT 1 FROM play_queue
    WHERE target_type = ? AND target_id = ? AND queued_at >= ? AND auto_play_id = ? AND status IN ('queued', 'dispatching', 'started')
)
`

type PlayQueueQueuedSinceParams struct {
	TargetType string
	TargetID   string
	QueuedAt   int64
	AutoPlayID string
}

func (q *Queries) PlayQueueQueuedSince(ctx context.Context, arg PlayQueueQueuedSinceParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, playQueueQueuedSince,
		arg.TargetType,
		arg.TargetID,
		arg.QueuedAt,
		arg.AutoPlayID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recoverDispatchingPlayQueue = `-- name: RecoverDispatchingPlayQueue :exec
UPDATE play_queue SET
    status = CASE WHEN EXISTS (SELECT 1 FROM play_trails t WHERE t.id = play_queue.trail_id) THEN 'started' ELSE 'queued' END,
    trail_id = CASE WHEN EXISTS (SELECT 1 FROM play_trails t WHERE t.id = play_queue.trail_id) THEN trail_id ELSE '' END,
    decided_at = CASE WHEN EXISTS (SELECT 1 FROM play_trails t WHERE t.id = play_queue.trail_id) THEN decided_at ELSE NULL END
WHERE status = 'dispatching'
`

func (q *Queries) RecoverDispatchingPlayQueue(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, recoverDispatchingPlayQueue)
	return err
}

const updatePlayQueueItem = `-- name: UpdatePlayQueueItem :execrows
UPDATE play_queue SET status = ?, reason = ?, trail_id = ?, decided_at = ?, not_before = ?
WHERE id = ? AND status = ?7
`

type UpdatePlayQueueItemParams struct {
	Status     string
	Reason     string
	TrailID    string
	DecidedAt  sql.NullInt64
	NotBefore  int64
	ID         string
	FromStatus string
}

func (q *Queries) UpdatePlayQueueItem(ctx context.Context, arg UpdatePlayQueueItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlayQueueItem,
		arg.Status,
		arg.Reason,
		arg.TrailID,
		arg.DecidedAt,
		arg.NotBefore,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPlayQueueResume = `-- name: UpsertPlayQueueResume :exec
INSERT INTO play_queue_resumes (target_type, target_id, resumed_by, resumed_at) VALUES (?, ?, ?, ?)
ON CONFLICT(target_type, target_id) DO UPDATE SET resumed_by = excluded.resumed_by, resumed_at = excluded.resumed_at
`

type UpsertPlayQueueResumeParams struct {
	TargetType string
	TargetID   string
	ResumedBy  string
	ResumedAt  int64
}

func (q *Queries) UpsertPlayQueueResume(ctx context.Context, arg UpsertPlayQueueResumeParams) error {
	_, err := q.db.ExecContext(ctx, upsertPlayQueueResume,
		arg.TargetType,
		arg.TargetID,
		arg.ResumedBy,
		arg.ResumedAt,
	)
	return err
}
