// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plays.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPlay = `-- name: CreatePlay :exec
INSERT INTO plays (id, workspace_id, label, type, description, instructions, enabled, show_when_stage, excluded_project_ids, created_by, created_at, updated_at, builtin_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePlayParams struct {
	ID                 string
	WorkspaceID        string
	Label              string
	Type               string
	Description        string
	Instructions       string
	Enabled            int64
	ShowWhenStage      sql.NullString
	ExcludedProjectIds string
	CreatedBy          string
	CreatedAt          int64
	UpdatedAt          int64
	BuiltinKey         string
}

func (q *Queries) CreatePlay(ctx context.Context, arg CreatePlayParams) error {
	_, err := q.db.ExecContext(ctx, createPlay,
		arg.ID,
		arg.WorkspaceID,
		arg.Label,
		arg.Type,
		arg.Description,
		arg.Instructions,
		arg.Enabled,
		arg.ShowWhenStage,
		arg.ExcludedProjectIds,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.BuiltinKey,
	)
	return err
}

const deletePlay = `-- name: DeletePlay :execrows
DELETE FROM plays WHERE id = ?
`

func (q *Queries) DeletePlay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePlay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getDecisionsCheckEnabled = `-- name: GetDecisionsCheckEnabled :one
SELECT decisions_check_enabled FROM workspaces WHERE id = ?
`

func (q *Queries) GetDecisionsCheckEnabled(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getDecisionsCheckEnabled, id)
	var decisions_check_enabled int64
	err := row.Scan(&decisions_check_enabled)
	return decisions_check_enabled, err
}

const getPlay = `-- name: GetPlay :one
SELECT id, workspace_id, label, type, description, instructions, enabled, show_when_stage, excluded_project_ids, created_by, created_at, updated_at, builtin_key FROM plays WHERE id = ?
`

func (q *Queries) GetPlay(ctx context.Context, id string) (Play, error) {
	row := q.db.QueryRowContext(ctx, getPlay, id)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Label,
		&i.Type,
		&i.Description,
		&i.Instructions,
		&i.Enabled,
		&i.ShowWhenStage,
		&i.ExcludedProjectIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltinKey,
	)
	return i, err
}

const getPlayByLabel = `-- name: GetPlayByLabel :one
SELECT id, workspace_id, label, type, description, instructions, enabled, show_when_stage, excluded_project_ids, created_by, created_at, updated_at, builtin_key FROM plays WHERE workspace_id = ? AND label = ? COLLATE NOCASE
`

type GetPlayByLabelParams struct {
	WorkspaceID string
	Label       string
}

func (q *Queries) GetPlayByLabel(ctx context.Context, arg GetPlayByLabelParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, getPlayByLabel, arg.WorkspaceID, arg.Label)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Label,
		&i.Type,
		&i.Description,
		&i.Instructions,
		&i.Enabled,
		&i.ShowWhenStage,
		&i.ExcludedProjectIds,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BuiltinKey,
	)
	return i, err
}

const listPlays = `-- name: ListPlays :many
SELECT id, workspace_id, label, type, description, instructions, enabled, show_when_stage, excluded_project_ids, created_by, created_at, updated_at, builtin_key FROM plays WHERE workspace_id = ? ORDER BY label
`

func (q *Queries) ListPlays(ctx context.Context, workspaceID string) ([]Play, error) {
	rows, err := q.db.QueryContext(ctx, listPlays, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Label,
			&i.Type,
			&i.Description,
			&i.Instructions,
			&i.Enabled,
			&i.ShowWhenStage,
			&i.ExcludedProjectIds,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BuiltinKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDecisionsCheckEnabled = `-- name: SetDecisionsCheckEnabled :execrows
UPDATE workspaces SET decisions_check_enabled = ? WHERE id = ?
`

type SetDecisionsCheckEnabledParams struct {
	DecisionsCheckEnabled int64
	ID                    string
}

func (q *Queries) SetDecisionsCheckEnabled(ctx context.Context, arg SetDecisionsCheckEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setDecisionsCheckEnabled, arg.DecisionsCheckEnabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePlay = `-- name: UpdatePlay :execrows
UPDATE plays SET label = ?, description = ?, instructions = ?, enabled = ?, show_when_stage = ?, excluded_project_ids = ?, updated_at = ?
WHERE id = ?
`

type UpdatePlayParams struct {
	Label              string
	Description        string
	Instructions       string
	Enabled            int64
	ShowWhenStage      sql.NullString
	ExcludedProjectIds string
	UpdatedAt          int64
	ID                 string
}

func (q *Queries) UpdatePlay(ctx context.Context, arg UpdatePlayParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePlay,
		arg.Label,
		arg.Description,
		arg.Instructions,
		arg.Enabled,
		arg.ShowWhenStage,
		arg.ExcludedProjectIds,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
