// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processed_events.sql

package sqlcgen

import (
	"context"
)

const countProcessedEvent = `-- name: CountProcessedEvent :one
SELECT COUNT(*) FROM processed_events WHERE event_id = ?
`

func (q *Queries) CountProcessedEvent(ctx context.Context, eventID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProcessedEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordProcessedEvent = `-- name: RecordProcessedEvent :exec
INSERT OR IGNORE INTO processed_events (event_id, processed_at) VALUES (?, ?)
`

type RecordProcessedEventParams struct {
	EventID     string
	ProcessedAt int64
}

func (q *Queries) RecordProcessedEvent(ctx context.Context, arg RecordProcessedEventParams) error {
	_, err := q.db.ExecContext(ctx, recordProcessedEvent, arg.EventID, arg.ProcessedAt)
	return err
}
