// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addProjectRepo = `-- name: AddProjectRepo :exec
INSERT INTO project_repos (project_id, owner, name, full_name, connector_id, added_at) VALUES (?, ?, ?, ?, ?, ?)
`

type AddProjectRepoParams struct {
	ProjectID   string
	Owner       string
	Name        string
	FullName    string
	ConnectorID string
	AddedAt     int64
}

func (q *Queries) AddProjectRepo(ctx context.Context, arg AddProjectRepoParams) error {
	_, err := q.db.ExecContext(ctx, addProjectRepo,
		arg.ProjectID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.ConnectorID,
		arg.AddedAt,
	)
	return err
}

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, prefix, position, workspace_id, icon, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID          string
	Name        string
	Prefix      string
	Position    int64
	WorkspaceID string
	Icon        string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.Position,
		arg.WorkspaceID,
		arg.Icon,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, name, prefix, position, workspace_id, created_at, updated_at, icon FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prefix,
		&i.Position,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Icon,
	)
	return i, err
}

const getProjectRepoByOwnerAndName = `-- name: GetProjectRepoByOwnerAndName :one
SELECT owner, name, full_name, connector_id FROM project_repos WHERE owner = ? AND name = ?
`

type GetProjectRepoByOwnerAndNameParams struct {
	Owner string
	Name  string
}

type GetProjectRepoByOwnerAndNameRow struct {
	Owner       string
	Name        string
	FullName    string
	ConnectorID string
}

func (q *Queries) GetProjectRepoByOwnerAndName(ctx context.Context, arg GetProjectRepoByOwnerAndNameParams) (GetProjectRepoByOwnerAndNameRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectRepoByOwnerAndName, arg.Owner, arg.Name)
	var i GetProjectRepoByOwnerAndNameRow
	err := row.Scan(
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.ConnectorID,
	)
	return i, err
}

const listProjectRepos = `-- name: ListProjectRepos :many
SELECT owner, name, full_name, connector_id FROM project_repos WHERE project_id = ? ORDER BY name
`

type ListProjectReposRow struct {
	Owner       string
	Name        string
	FullName    string
	ConnectorID string
}

func (q *Queries) ListProjectRepos(ctx context.Context, projectID string) ([]ListProjectReposRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectRepos, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectReposRow
	for rows.Next() {
		var i ListProjectReposRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.ConnectorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, name, prefix, position, workspace_id, created_at, updated_at, icon FROM projects WHERE workspace_id = ? ORDER BY position, id
`

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Position,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTicketProject = `-- name: MoveTicketProject :execrows
UPDATE tickets SET project_id = ? WHERE id = ?
`

type MoveTicketProjectParams struct {
	ProjectID sql.NullString
	ID        string
}

func (q *Queries) MoveTicketProject(ctx context.Context, arg MoveTicketProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveTicketProject, arg.ProjectID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeProjectRepo = `-- name: RemoveProjectRepo :execrows
DELETE FROM project_repos WHERE owner = ? AND name = ?
`

type RemoveProjectRepoParams struct {
	Owner string
	Name  string
}

func (q *Queries) RemoveProjectRepo(ctx context.Context, arg RemoveProjectRepoParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeProjectRepo, arg.Owner, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reorderProjectPosition = `-- name: ReorderProjectPosition :exec
UPDATE projects SET position = ?, updated_at = ? WHERE id = ?
`

type ReorderProjectPositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) ReorderProjectPosition(ctx context.Context, arg ReorderProjectPositionParams) error {
	_, err := q.db.ExecContext(ctx, reorderProjectPosition, arg.Position, arg.UpdatedAt, arg.ID)
	return err
}

const seedProjectStatus = `-- name: SeedProjectStatus :exec
INSERT INTO statuses (id, project_id, name, position, kind, icon, created_at, updated_at) VALUES (?, ?, ?, ?, ?, '', ?, ?)
`

type SeedProjectStatusParams struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	Kind      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) SeedProjectStatus(ctx context.Context, arg SeedProjectStatusParams) error {
	_, err := q.db.ExecContext(ctx, seedProjectStatus,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const seedProjectTicketType = `-- name: SeedProjectTicketType :exec
INSERT INTO ticket_types (id, project_id, name, position, color, created_at, updated_at) VALUES (?, ?, ?, ?, '', ?, ?)
`

type SeedProjectTicketTypeParams struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) SeedProjectTicketType(ctx context.Context, arg SeedProjectTicketTypeParams) error {
	_, err := q.db.ExecContext(ctx, seedProjectTicketType,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateProject = `-- name: UpdateProject :execrows
UPDATE projects SET name = ?, prefix = ?, icon = ?, updated_at = ? WHERE id = ?
`

type UpdateProjectParams struct {
	Name      string
	Prefix    string
	Icon      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Prefix,
		arg.Icon,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
