// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlcgen

import (
	"context"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (id, workspace_id, name, permissions, is_owner_role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRoleParams struct {
	ID          string
	WorkspaceID string
	Name        string
	Permissions string
	IsOwnerRole int64
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.ExecContext(ctx, createRole,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Permissions,
		arg.IsOwnerRole,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = ?
`

func (q *Queries) DeleteRole(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRole = `-- name: GetRole :one
SELECT id, workspace_id, name, is_owner_role, created_at, updated_at, permissions FROM roles WHERE id = ?
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.IsOwnerRole,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Permissions,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, workspace_id, name, is_owner_role, created_at, updated_at, permissions FROM roles WHERE workspace_id = ? ORDER BY is_owner_role DESC, created_at, id
`

func (q *Queries) ListRoles(ctx context.Context, workspaceID string) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.IsOwnerRole,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :execrows
UPDATE roles SET name = ?, permissions = ?, updated_at = ? WHERE id = ?
`

type UpdateRoleParams struct {
	Name        string
	Permissions string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRole,
		arg.Name,
		arg.Permissions,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
