// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runners.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const consumeRunnerEnrollmentCode = `-- name: ConsumeRunnerEnrollmentCode :execrows
DELETE FROM runner_enrollment_codes WHERE code_hash = ? AND expires_at > ?
`

type ConsumeRunnerEnrollmentCodeParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) ConsumeRunnerEnrollmentCode(ctx context.Context, arg ConsumeRunnerEnrollmentCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, consumeRunnerEnrollmentCode, arg.CodeHash, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createInstanceUpgrade = `-- name: CreateInstanceUpgrade :exec
INSERT INTO instance_upgrades (id, from_version, to_version, status, error, requested_by, runner_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateInstanceUpgradeParams struct {
	ID          string
	FromVersion string
	ToVersion   string
	Status      string
	Error       string
	RequestedBy string
	RunnerID    string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateInstanceUpgrade(ctx context.Context, arg CreateInstanceUpgradeParams) error {
	_, err := q.db.ExecContext(ctx, createInstanceUpgrade,
		arg.ID,
		arg.FromVersion,
		arg.ToVersion,
		arg.Status,
		arg.Error,
		arg.RequestedBy,
		arg.RunnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRunner = `-- name: CreateRunner :exec
INSERT INTO runners (id, name, version, last_seen, connected, created_at, machine_id) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateRunnerParams struct {
	ID        string
	Name      string
	Version   string
	LastSeen  int64
	Connected int64
	CreatedAt int64
	MachineID string
}

func (q *Queries) CreateRunner(ctx context.Context, arg CreateRunnerParams) error {
	_, err := q.db.ExecContext(ctx, createRunner,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.LastSeen,
		arg.Connected,
		arg.CreatedAt,
		arg.MachineID,
	)
	return err
}

const createRunnerCredential = `-- name: CreateRunnerCredential :exec
INSERT INTO runner_credentials (credential_hash, runner_id, runner_name, created_at) VALUES (?, ?, ?, ?)
`

type CreateRunnerCredentialParams struct {
	CredentialHash string
	RunnerID       string
	RunnerName     string
	CreatedAt      int64
}

func (q *Queries) CreateRunnerCredential(ctx context.Context, arg CreateRunnerCredentialParams) error {
	_, err := q.db.ExecContext(ctx, createRunnerCredential,
		arg.CredentialHash,
		arg.RunnerID,
		arg.RunnerName,
		arg.CreatedAt,
	)
	return err
}

const createRunnerEnrollmentCode = `-- name: CreateRunnerEnrollmentCode :exec
INSERT INTO runner_enrollment_codes (code_hash, name, machine, created_at, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateRunnerEnrollmentCodeParams struct {
	CodeHash  string
	Name      string
	Machine   string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateRunnerEnrollmentCode(ctx context.Context, arg CreateRunnerEnrollmentCodeParams) error {
	_, err := q.db.ExecContext(ctx, createRunnerEnrollmentCode,
		arg.CodeHash,
		arg.Name,
		arg.Machine,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteRunner = `-- name: DeleteRunner :execrows
DELETE FROM runners WHERE id = ?
`

func (q *Queries) DeleteRunner(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunner, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getInstanceUpgrade = `-- name: GetInstanceUpgrade :one
SELECT id, from_version, to_version, status, error, requested_by, runner_id, created_at, updated_at FROM instance_upgrades WHERE id = ?
`

func (q *Queries) GetInstanceUpgrade(ctx context.Context, id string) (InstanceUpgrade, error) {
	row := q.db.QueryRowContext(ctx, getInstanceUpgrade, id)
	var i InstanceUpgrade
	err := row.Scan(
		&i.ID,
		&i.FromVersion,
		&i.ToVersion,
		&i.Status,
		&i.Error,
		&i.RequestedBy,
		&i.RunnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestInstanceUpgrade = `-- name: GetLatestInstanceUpgrade :one
SELECT id, from_version, to_version, status, error, requested_by, runner_id, created_at, updated_at FROM instance_upgrades ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestInstanceUpgrade(ctx context.Context) (InstanceUpgrade, error) {
	row := q.db.QueryRowContext(ctx, getLatestInstanceUpgrade)
	var i InstanceUpgrade
	err := row.Scan(
		&i.ID,
		&i.FromVersion,
		&i.ToVersion,
		&i.Status,
		&i.Error,
		&i.RequestedBy,
		&i.RunnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunner = `-- name: GetRunner :one
SELECT id, name, last_seen, connected, created_at, version, machine_id FROM runners WHERE id = ?
`

func (q *Queries) GetRunner(ctx context.Context, id string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunner, id)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastSeen,
		&i.Connected,
		&i.CreatedAt,
		&i.Version,
		&i.MachineID,
	)
	return i, err
}

const getRunnerByName = `-- name: GetRunnerByName :one
SELECT id, name, last_seen, connected, created_at, version, machine_id FROM runners WHERE name = ?
`

func (q *Queries) GetRunnerByName(ctx context.Context, name string) (Runner, error) {
	row := q.db.QueryRowContext(ctx, getRunnerByName, name)
	var i Runner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastSeen,
		&i.Connected,
		&i.CreatedAt,
		&i.Version,
		&i.MachineID,
	)
	return i, err
}

const getRunnerCredential = `-- name: GetRunnerCredential :one
SELECT credential_hash, runner_id, runner_name, created_at, revoked_at FROM runner_credentials WHERE credential_hash = ?
`

func (q *Queries) GetRunnerCredential(ctx context.Context, credentialHash string) (RunnerCredential, error) {
	row := q.db.QueryRowContext(ctx, getRunnerCredential, credentialHash)
	var i RunnerCredential
	err := row.Scan(
		&i.CredentialHash,
		&i.RunnerID,
		&i.RunnerName,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRunnerEnrollmentCode = `-- name: GetRunnerEnrollmentCode :one
SELECT code_hash, name, machine, created_at, expires_at FROM runner_enrollment_codes WHERE code_hash = ? AND expires_at > ?
`

type GetRunnerEnrollmentCodeParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) GetRunnerEnrollmentCode(ctx context.Context, arg GetRunnerEnrollmentCodeParams) (RunnerEnrollmentCode, error) {
	row := q.db.QueryRowContext(ctx, getRunnerEnrollmentCode, arg.CodeHash, arg.ExpiresAt)
	var i RunnerEnrollmentCode
	err := row.Scan(
		&i.CodeHash,
		&i.Name,
		&i.Machine,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listRunners = `-- name: ListRunners :many
SELECT id, name, last_seen, connected, created_at, version, machine_id FROM runners ORDER BY created_at
`

func (q *Queries) ListRunners(ctx context.Context) ([]Runner, error) {
	rows, err := q.db.QueryContext(ctx, listRunners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runner
	for rows.Next() {
		var i Runner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastSeen,
			&i.Connected,
			&i.CreatedAt,
			&i.Version,
			&i.MachineID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedInstanceUpgrades = `-- name: ListUnresolvedInstanceUpgrades :many
SELECT id, from_version, to_version, status, error, requested_by, runner_id, created_at, updated_at FROM instance_upgrades WHERE status IN ('pending', 'started') ORDER BY created_at
`

func (q *Queries) ListUnresolvedInstanceUpgrades(ctx context.Context) ([]InstanceUpgrade, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedInstanceUpgrades)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InstanceUpgrade
	for rows.Next() {
		var i InstanceUpgrade
		if err := rows.Scan(
			&i.ID,
			&i.FromVersion,
			&i.ToVersion,
			&i.Status,
			&i.Error,
			&i.RequestedBy,
			&i.RunnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRunnerEnrollmentCodes = `-- name: PruneRunnerEnrollmentCodes :exec
DELETE FROM runner_enrollment_codes WHERE expires_at <= ?
`

func (q *Queries) PruneRunnerEnrollmentCodes(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, pruneRunnerEnrollmentCodes, expiresAt)
	return err
}

const revokeRunnerCredentials = `-- name: RevokeRunnerCredentials :exec
UPDATE runner_credentials SET revoked_at = ? WHERE runner_id = ? AND revoked_at IS NULL
`

type RevokeRunnerCredentialsParams struct {
	RevokedAt sql.NullInt64
	RunnerID  string
}

func (q *Queries) RevokeRunnerCredentials(ctx context.Context, arg RevokeRunnerCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, revokeRunnerCredentials, arg.RevokedAt, arg.RunnerID)
	return err
}

const setInstanceUpgradeStatus = `-- name: SetInstanceUpgradeStatus :execrows
UPDATE instance_upgrades SET status = ?, error = ?, updated_at = ? WHERE id = ?
`

type SetInstanceUpgradeStatusParams struct {
	Status    string
	Error     string
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetInstanceUpgradeStatus(ctx context.Context, arg SetInstanceUpgradeStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setInstanceUpgradeStatus,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setRunnerVersion = `-- name: SetRunnerVersion :execrows
UPDATE runners SET version = ? WHERE id = ?
`

type SetRunnerVersionParams struct {
	Version string
	ID      string
}

func (q *Queries) SetRunnerVersion(ctx context.Context, arg SetRunnerVersionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setRunnerVersion, arg.Version, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRunnerHeartbeat = `-- name: UpdateRunnerHeartbeat :execrows
UPDATE runners SET last_seen = ?, connected = ? WHERE id = ?
`

type UpdateRunnerHeartbeatParams struct {
	LastSeen  int64
	Connected int64
	ID        string
}

func (q *Queries) UpdateRunnerHeartbeat(ctx context.Context, arg UpdateRunnerHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRunnerHeartbeat, arg.LastSeen, arg.Connected, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
