// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemas_audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendAudit = `-- name: AppendAudit :exec
INSERT INTO audit_log (id, actor_type, actor_id, token_id, action, created_at) VALUES (?, ?, ?, ?, ?, ?)
`

type AppendAuditParams struct {
	ID        string
	ActorType string
	ActorID   string
	TokenID   sql.NullString
	Action    string
	CreatedAt int64
}

func (q *Queries) AppendAudit(ctx context.Context, arg AppendAuditParams) error {
	_, err := q.db.ExecContext(ctx, appendAudit,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.TokenID,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT id, actor_type, actor_id, token_id, "action", created_at FROM audit_log ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListAudit(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.TokenID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemaCatalog = `-- name: ListSchemaCatalog :many
SELECT topic, version, schema, created_at FROM event_schemas ORDER BY topic, version DESC
`

func (q *Queries) ListSchemaCatalog(ctx context.Context) ([]EventSchema, error) {
	rows, err := q.db.QueryContext(ctx, listSchemaCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventSchema
	for rows.Next() {
		var i EventSchema
		if err := rows.Scan(
			&i.Topic,
			&i.Version,
			&i.Schema,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishSchema = `-- name: PublishSchema :exec
INSERT OR IGNORE INTO event_schemas (topic, version, schema, created_at) VALUES (?, ?, ?, ?)
`

type PublishSchemaParams struct {
	Topic     string
	Version   int64
	Schema    string
	CreatedAt int64
}

func (q *Queries) PublishSchema(ctx context.Context, arg PublishSchemaParams) error {
	_, err := q.db.ExecContext(ctx, publishSchema,
		arg.Topic,
		arg.Version,
		arg.Schema,
		arg.CreatedAt,
	)
	return err
}
