// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcgen

import (
	"context"
)

const createContainer = `-- name: CreateContainer :exec
INSERT INTO services (id, stack_id, name, declared, container_name, image, status, networks, ports, observed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContainerParams struct {
	ID            string
	StackID       string
	Name          string
	Declared      string
	ContainerName string
	Image         string
	Status        string
	Networks      string
	Ports         string
	ObservedAt    int64
}

func (q *Queries) CreateContainer(ctx context.Context, arg CreateContainerParams) error {
	_, err := q.db.ExecContext(ctx, createContainer,
		arg.ID,
		arg.StackID,
		arg.Name,
		arg.Declared,
		arg.ContainerName,
		arg.Image,
		arg.Status,
		arg.Networks,
		arg.Ports,
		arg.ObservedAt,
	)
	return err
}

const deleteContainersByStack = `-- name: DeleteContainersByStack :exec
DELETE FROM services WHERE stack_id = ?
`

func (q *Queries) DeleteContainersByStack(ctx context.Context, stackID string) error {
	_, err := q.db.ExecContext(ctx, deleteContainersByStack, stackID)
	return err
}

const getContainer = `-- name: GetContainer :one
SELECT id, stack_id, name, declared, container_name, image, status, networks, ports, observed_at FROM services WHERE id = ?
`

func (q *Queries) GetContainer(ctx context.Context, id string) (Service, error) {
	row := q.db.QueryRowContext(ctx, getContainer, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.StackID,
		&i.Name,
		&i.Declared,
		&i.ContainerName,
		&i.Image,
		&i.Status,
		&i.Networks,
		&i.Ports,
		&i.ObservedAt,
	)
	return i, err
}

const listContainerNamesByMachine = `-- name: ListContainerNamesByMachine :many
SELECT c.container_name FROM services c JOIN stacks s ON s.id = c.stack_id
WHERE s.machine = ? AND c.container_name <> '' ORDER BY c.container_name
`

func (q *Queries) ListContainerNamesByMachine(ctx context.Context, machine string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listContainerNamesByMachine, machine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var container_name string
		if err := rows.Scan(&container_name); err != nil {
			return nil, err
		}
		items = append(items, container_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainersByStack = `-- name: ListContainersByStack :many
SELECT id, stack_id, name, declared, container_name, image, status, networks, ports, observed_at FROM services WHERE stack_id = ? ORDER BY name
`

func (q *Queries) ListContainersByStack(ctx context.Context, stackID string) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listContainersByStack, stackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.StackID,
			&i.Name,
			&i.Declared,
			&i.ContainerName,
			&i.Image,
			&i.Status,
			&i.Networks,
			&i.Ports,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContainer = `-- name: UpsertContainer :exec
INSERT INTO services (id, stack_id, name, declared, container_name, image, status, networks, ports, observed_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (stack_id, name) DO UPDATE SET
    declared = excluded.declared,
    container_name = excluded.container_name,
    image = excluded.image,
    status = excluded.status,
    networks = excluded.networks,
    ports = excluded.ports,
    observed_at = excluded.observed_at
`

type UpsertContainerParams struct {
	ID            string
	StackID       string
	Name          string
	Declared      string
	ContainerName string
	Image         string
	Status        string
	Networks      string
	Ports         string
	ObservedAt    int64
}

func (q *Queries) UpsertContainer(ctx context.Context, arg UpsertContainerParams) error {
	_, err := q.db.ExecContext(ctx, upsertContainer,
		arg.ID,
		arg.StackID,
		arg.Name,
		arg.Declared,
		arg.ContainerName,
		arg.Image,
		arg.Status,
		arg.Networks,
		arg.Ports,
		arg.ObservedAt,
	)
	return err
}
