// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, client, platform, label, ip, created_at, last_active_at, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID           string
	UserID       string
	TokenHash    string
	Client       string
	Platform     string
	Label        string
	Ip           string
	CreatedAt    int64
	LastActiveAt int64
	ExpiresAt    int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Client,
		arg.Platform,
		arg.Label,
		arg.Ip,
		arg.CreatedAt,
		arg.LastActiveAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE user_id = ? AND expires_at <= ?
`

type DeleteExpiredSessionsParams struct {
	UserID    string
	ExpiresAt int64
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE user_id = ? AND id != ?
`

type DeleteOtherSessionsParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteOtherSessions, arg.UserID, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = ? AND user_id = ?
`

type DeleteSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, token_hash, client, platform, label, ip, created_at, last_active_at, expires_at, push_token FROM sessions WHERE token_hash = ?
`

func (q *Queries) GetSessionByHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Client,
		&i.Platform,
		&i.Label,
		&i.Ip,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.PushToken,
	)
	return i, err
}

const listPushTargets = `-- name: ListPushTargets :many
SELECT id, user_id, push_token FROM sessions
WHERE client = 'phone' AND push_token IS NOT NULL AND expires_at > ?1 AND user_id IN (/*SLICE:user_ids*/?)
`

type ListPushTargetsParams struct {
	Now     int64
	UserIds []string
}

type ListPushTargetsRow struct {
	ID        string
	UserID    string
	PushToken sql.NullString
}

func (q *Queries) ListPushTargets(ctx context.Context, arg ListPushTargetsParams) ([]ListPushTargetsRow, error) {
	query := listPushTargets
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Now)
	if len(arg.UserIds) > 0 {
		for _, v := range arg.UserIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(arg.UserIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPushTargetsRow
	for rows.Next() {
		var i ListPushTargetsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.PushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, token_hash, client, platform, label, ip, created_at, last_active_at, expires_at, push_token FROM sessions WHERE user_id = ? ORDER BY last_active_at DESC, id
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.Client,
			&i.Platform,
			&i.Label,
			&i.Ip,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.PushToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionPushToken = `-- name: SetSessionPushToken :execrows
UPDATE sessions SET push_token = ? WHERE id = ? AND user_id = ?
`

type SetSessionPushTokenParams struct {
	PushToken sql.NullString
	ID        string
	UserID    string
}

func (q *Queries) SetSessionPushToken(ctx context.Context, arg SetSessionPushTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setSessionPushToken, arg.PushToken, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_active_at = ?, ip = ?, expires_at = ? WHERE id = ?
`

type TouchSessionParams struct {
	LastActiveAt int64
	Ip           string
	ExpiresAt    int64
	ID           string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession,
		arg.LastActiveAt,
		arg.Ip,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
