// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup_codes.sql

package sqlcgen

import (
	"context"
)

const countLiveSetupCodes = `-- name: CountLiveSetupCodes :one
SELECT COUNT(*) FROM setup_codes WHERE code_hash = ? AND expires_at > ?
`

type CountLiveSetupCodesParams struct {
	CodeHash  string
	ExpiresAt int64
}

func (q *Queries) CountLiveSetupCodes(ctx context.Context, arg CountLiveSetupCodesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLiveSetupCodes, arg.CodeHash, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSetupCode = `-- name: CreateSetupCode :exec
INSERT INTO setup_codes (code_hash, created_at, expires_at) VALUES (?, ?, ?)
`

type CreateSetupCodeParams struct {
	CodeHash  string
	CreatedAt int64
	ExpiresAt int64
}

func (q *Queries) CreateSetupCode(ctx context.Context, arg CreateSetupCodeParams) error {
	_, err := q.db.ExecContext(ctx, createSetupCode, arg.CodeHash, arg.CreatedAt, arg.ExpiresAt)
	return err
}

const deleteSetupCodes = `-- name: DeleteSetupCodes :exec
DELETE FROM setup_codes
`

func (q *Queries) DeleteSetupCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSetupCodes)
	return err
}
