// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package sqlcgen

import (
	"context"
)

const countStatusTickets = `-- name: CountStatusTickets :one
SELECT COUNT(*) FROM tickets WHERE status = ?
`

func (q *Queries) CountStatusTickets(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStatusTickets, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatus = `-- name: CreateStatus :exec
INSERT INTO statuses (id, project_id, name, position, kind, icon, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateStatusParams struct {
	ID        string
	ProjectID string
	Name      string
	Position  int64
	Kind      string
	Icon      string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.Kind,
		arg.Icon,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteStatus = `-- name: DeleteStatus :execrows
DELETE FROM statuses WHERE id = ?
`

func (q *Queries) DeleteStatus(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStatus, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getStatus = `-- name: GetStatus :one
SELECT id, project_id, name, position, kind, icon, created_at, updated_at FROM statuses WHERE id = ?
`

func (q *Queries) GetStatus(ctx context.Context, id string) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.Kind,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStatusesByProject = `-- name: ListStatusesByProject :many
SELECT id, project_id, name, position, kind, icon, created_at, updated_at FROM statuses WHERE project_id = ?
    ORDER BY CASE kind WHEN 'backlog' THEN 0 WHEN 'progress' THEN 1 WHEN 'review' THEN 2 WHEN 'testing' THEN 3 ELSE 4 END, position, id
`

func (q *Queries) ListStatusesByProject(ctx context.Context, projectID string) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, listStatusesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.Kind,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderStatusPosition = `-- name: ReorderStatusPosition :execrows
UPDATE statuses SET position = ?, updated_at = ? WHERE id = ? AND project_id = ?
`

type ReorderStatusPositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
	ProjectID string
}

func (q *Queries) ReorderStatusPosition(ctx context.Context, arg ReorderStatusPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reorderStatusPosition,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const statusExists = `-- name: StatusExists :one
SELECT COUNT(*) FROM statuses WHERE id = ?
`

func (q *Queries) StatusExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, statusExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateStatus = `-- name: UpdateStatus :execrows
UPDATE statuses SET name = ?, kind = ?, icon = ?, updated_at = ? WHERE id = ?
`

type UpdateStatusParams struct {
	Name      string
	Kind      string
	Icon      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateStatus,
		arg.Name,
		arg.Kind,
		arg.Icon,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
