// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions_deliveries.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addIntegrationSubscription = `-- name: AddIntegrationSubscription :exec
INSERT INTO integration_subscriptions (install_id, topic, created_at) VALUES (?, ?, ?)
`

type AddIntegrationSubscriptionParams struct {
	InstallID string
	Topic     string
	CreatedAt int64
}

func (q *Queries) AddIntegrationSubscription(ctx context.Context, arg AddIntegrationSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, addIntegrationSubscription, arg.InstallID, arg.Topic, arg.CreatedAt)
	return err
}

const createIntegrationDelivery = `-- name: CreateIntegrationDelivery :exec
INSERT INTO integration_deliveries (id, install_id, topic, event_id, payload, signature, url, status, attempts, next_attempt_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(install_id, event_id, topic) DO NOTHING
`

type CreateIntegrationDeliveryParams struct {
	ID            string
	InstallID     string
	Topic         string
	EventID       string
	Payload       []byte
	Signature     string
	Url           string
	Status        string
	Attempts      int64
	NextAttemptAt int64
	CreatedAt     int64
}

func (q *Queries) CreateIntegrationDelivery(ctx context.Context, arg CreateIntegrationDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createIntegrationDelivery,
		arg.ID,
		arg.InstallID,
		arg.Topic,
		arg.EventID,
		arg.Payload,
		arg.Signature,
		arg.Url,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const listDueIntegrationDeliveries = `-- name: ListDueIntegrationDeliveries :many
SELECT id, install_id, topic, event_id, payload, signature, url, status, attempts, next_attempt_at, created_at, delivered_at FROM integration_deliveries
WHERE status IN ('pending', 'failed') AND next_attempt_at <= ?
ORDER BY next_attempt_at LIMIT ?
`

type ListDueIntegrationDeliveriesParams struct {
	NextAttemptAt int64
	Limit         int64
}

func (q *Queries) ListDueIntegrationDeliveries(ctx context.Context, arg ListDueIntegrationDeliveriesParams) ([]IntegrationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listDueIntegrationDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationDelivery
	for rows.Next() {
		var i IntegrationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.InstallID,
			&i.Topic,
			&i.EventID,
			&i.Payload,
			&i.Signature,
			&i.Url,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationDeliveriesByInstall = `-- name: ListIntegrationDeliveriesByInstall :many
SELECT id, install_id, topic, event_id, payload, signature, url, status, attempts, next_attempt_at, created_at, delivered_at FROM integration_deliveries WHERE install_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationDeliveriesByInstall(ctx context.Context, installID string) ([]IntegrationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationDeliveriesByInstall, installID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationDelivery
	for rows.Next() {
		var i IntegrationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.InstallID,
			&i.Topic,
			&i.EventID,
			&i.Payload,
			&i.Signature,
			&i.Url,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationSubscriptionsByInstall = `-- name: ListIntegrationSubscriptionsByInstall :many
SELECT install_id, topic, created_at FROM integration_subscriptions WHERE install_id = ? ORDER BY topic
`

func (q *Queries) ListIntegrationSubscriptionsByInstall(ctx context.Context, installID string) ([]IntegrationSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationSubscriptionsByInstall, installID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationSubscription
	for rows.Next() {
		var i IntegrationSubscription
		if err := rows.Scan(&i.InstallID, &i.Topic, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationSubscriptionsByTopic = `-- name: ListIntegrationSubscriptionsByTopic :many
SELECT install_id, topic, created_at FROM integration_subscriptions WHERE topic = ? ORDER BY created_at
`

func (q *Queries) ListIntegrationSubscriptionsByTopic(ctx context.Context, topic string) ([]IntegrationSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listIntegrationSubscriptionsByTopic, topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationSubscription
	for rows.Next() {
		var i IntegrationSubscription
		if err := rows.Scan(&i.InstallID, &i.Topic, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIntegrationDeliveryDead = `-- name: MarkIntegrationDeliveryDead :execrows
UPDATE integration_deliveries SET status = 'dead', attempts = attempts + 1 WHERE id = ?
`

func (q *Queries) MarkIntegrationDeliveryDead(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markIntegrationDeliveryDead, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markIntegrationDeliveryDelivered = `-- name: MarkIntegrationDeliveryDelivered :execrows
UPDATE integration_deliveries SET status = 'delivered', delivered_at = ? WHERE id = ?
`

type MarkIntegrationDeliveryDeliveredParams struct {
	DeliveredAt sql.NullInt64
	ID          string
}

func (q *Queries) MarkIntegrationDeliveryDelivered(ctx context.Context, arg MarkIntegrationDeliveryDeliveredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markIntegrationDeliveryDelivered, arg.DeliveredAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markIntegrationDeliveryFailed = `-- name: MarkIntegrationDeliveryFailed :execrows
UPDATE integration_deliveries SET status = 'failed', attempts = ?, next_attempt_at = ? WHERE id = ?
`

type MarkIntegrationDeliveryFailedParams struct {
	Attempts      int64
	NextAttemptAt int64
	ID            string
}

func (q *Queries) MarkIntegrationDeliveryFailed(ctx context.Context, arg MarkIntegrationDeliveryFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markIntegrationDeliveryFailed, arg.Attempts, arg.NextAttemptAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeIntegrationSubscription = `-- name: RemoveIntegrationSubscription :execrows
DELETE FROM integration_subscriptions WHERE install_id = ? AND topic = ?
`

type RemoveIntegrationSubscriptionParams struct {
	InstallID string
	Topic     string
}

func (q *Queries) RemoveIntegrationSubscription(ctx context.Context, arg RemoveIntegrationSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeIntegrationSubscription, arg.InstallID, arg.Topic)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
