// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy.sql

package sqlcgen

import (
	"context"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :exec
INSERT INTO workspace_members (user_id, workspace_id, role_id, created_at) VALUES (?, ?, ?, ?)
`

type AddWorkspaceMemberParams struct {
	UserID      string
	WorkspaceID string
	RoleID      string
	CreatedAt   int64
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error {
	_, err := q.db.ExecContext(ctx, addWorkspaceMember,
		arg.UserID,
		arg.WorkspaceID,
		arg.RoleID,
		arg.CreatedAt,
	)
	return err
}

const createWorkspace = `-- name: CreateWorkspace :exec
INSERT INTO workspaces (id, name, slug, mention_chip_template, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWorkspaceParams struct {
	ID                  string
	Name                string
	Slug                string
	MentionChipTemplate string
	CreatedAt           int64
	UpdatedAt           int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error {
	_, err := q.db.ExecContext(ctx, createWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.MentionChipTemplate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorkspaceInvite = `-- name: DeleteWorkspaceInvite :exec
DELETE FROM workspace_invites WHERE workspace_id = ? AND login = ?
`

type DeleteWorkspaceInviteParams struct {
	WorkspaceID string
	Login       string
}

func (q *Queries) DeleteWorkspaceInvite(ctx context.Context, arg DeleteWorkspaceInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteWorkspaceInvite, arg.WorkspaceID, arg.Login)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, created_at, updated_at, mention_chip_template, slug FROM workspaces WHERE id = ?
`

func (q *Queries) GetWorkspace(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionChipTemplate,
		&i.Slug,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, name, created_at, updated_at, mention_chip_template, slug FROM workspaces WHERE slug = ?
`

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MentionChipTemplate,
		&i.Slug,
	)
	return i, err
}

const getWorkspaceMemberRole = `-- name: GetWorkspaceMemberRole :one
SELECT role_id FROM workspace_members WHERE workspace_id = ? AND user_id = ?
`

type GetWorkspaceMemberRoleParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) GetWorkspaceMemberRole(ctx context.Context, arg GetWorkspaceMemberRoleParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkspaceMemberRole, arg.WorkspaceID, arg.UserID)
	var role_id string
	err := row.Scan(&role_id)
	return role_id, err
}

const listTeamMemberships = `-- name: ListTeamMemberships :many
SELECT m.user_id, m.workspace_id, w.name AS workspace_name, m.role_id, r.name AS role_name, r.is_owner_role,
       COALESCE(po.allow, '[]') AS allow, COALESCE(po.deny, '[]') AS deny
FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id
JOIN roles r ON r.id = m.role_id
LEFT JOIN permission_overwrites po
  ON po.resource_type = 'workspace'
 AND po.resource_id = m.workspace_id
 AND po.user_id = m.user_id
ORDER BY w.created_at, w.id
`

type ListTeamMembershipsRow struct {
	UserID        string
	WorkspaceID   string
	WorkspaceName string
	RoleID        string
	RoleName      string
	IsOwnerRole   int64
	Allow         string
	Deny          string
}

func (q *Queries) ListTeamMemberships(ctx context.Context) ([]ListTeamMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembershipsRow
	for rows.Next() {
		var i ListTeamMembershipsRow
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.RoleID,
			&i.RoleName,
			&i.IsOwnerRole,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRoles = `-- name: ListTeamRoles :many
SELECT id, workspace_id, name, is_owner_role FROM roles ORDER BY is_owner_role DESC, created_at, id
`

type ListTeamRolesRow struct {
	ID          string
	WorkspaceID string
	Name        string
	IsOwnerRole int64
}

func (q *Queries) ListTeamRoles(ctx context.Context) ([]ListTeamRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamRolesRow
	for rows.Next() {
		var i ListTeamRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.IsOwnerRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamWorkspaces = `-- name: ListTeamWorkspaces :many
SELECT id, name FROM workspaces ORDER BY created_at, id
`

type ListTeamWorkspacesRow struct {
	ID   string
	Name string
}

func (q *Queries) ListTeamWorkspaces(ctx context.Context) ([]ListTeamWorkspacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTeamWorkspaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamWorkspacesRow
	for rows.Next() {
		var i ListTeamWorkspacesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceInvitesByLogin = `-- name: ListWorkspaceInvitesByLogin :many
SELECT workspace_id, login, role_id, invited_by, created_at
FROM workspace_invites WHERE login = ? ORDER BY created_at, workspace_id
`

func (q *Queries) ListWorkspaceInvitesByLogin(ctx context.Context, login string) ([]WorkspaceInvite, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceInvitesByLogin, login)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvite
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Login,
			&i.RoleID,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceInvitesByWorkspace = `-- name: ListWorkspaceInvitesByWorkspace :many
SELECT workspace_id, login, role_id, invited_by, created_at
FROM workspace_invites WHERE workspace_id = ? ORDER BY created_at, login
`

func (q *Queries) ListWorkspaceInvitesByWorkspace(ctx context.Context, workspaceID string) ([]WorkspaceInvite, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceInvitesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceInvite
	for rows.Next() {
		var i WorkspaceInvite
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.Login,
			&i.RoleID,
			&i.InvitedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT user_id, workspace_id, role_id, created_at FROM workspace_members WHERE workspace_id = ? ORDER BY created_at, user_id
`

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]WorkspaceMember, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMember
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.UserID,
			&i.WorkspaceID,
			&i.RoleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesForUser = `-- name: ListWorkspacesForUser :many
SELECT w.id, w.name, w.created_at, w.updated_at, w.mention_chip_template, w.slug
FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = ?
ORDER BY w.created_at, w.id
`

func (q *Queries) ListWorkspacesForUser(ctx context.Context, userID string) ([]Workspace, error) {
	rows, err := q.db.QueryContext(ctx, listWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MentionChipTemplate,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :execrows
DELETE FROM workspace_members WHERE workspace_id = ? AND user_id = ?
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID string
	UserID      string
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setWorkspaceMemberRole = `-- name: SetWorkspaceMemberRole :execrows
UPDATE workspace_members SET role_id = ? WHERE workspace_id = ? AND user_id = ?
`

type SetWorkspaceMemberRoleParams struct {
	RoleID      string
	WorkspaceID string
	UserID      string
}

func (q *Queries) SetWorkspaceMemberRole(ctx context.Context, arg SetWorkspaceMemberRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setWorkspaceMemberRole, arg.RoleID, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateWorkspace = `-- name: UpdateWorkspace :execrows
UPDATE workspaces SET name = ?, slug = ?, mention_chip_template = ?, updated_at = ? WHERE id = ?
`

type UpdateWorkspaceParams struct {
	Name                string
	Slug                string
	MentionChipTemplate string
	UpdatedAt           int64
	ID                  string
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateWorkspace,
		arg.Name,
		arg.Slug,
		arg.MentionChipTemplate,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertWorkspaceInvite = `-- name: UpsertWorkspaceInvite :exec
INSERT INTO workspace_invites (workspace_id, login, role_id, invited_by, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(workspace_id, login) DO UPDATE SET
    role_id = excluded.role_id,
    invited_by = excluded.invited_by,
    created_at = excluded.created_at
`

type UpsertWorkspaceInviteParams struct {
	WorkspaceID string
	Login       string
	RoleID      string
	InvitedBy   string
	CreatedAt   int64
}

func (q *Queries) UpsertWorkspaceInvite(ctx context.Context, arg UpsertWorkspaceInviteParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkspaceInvite,
		arg.WorkspaceID,
		arg.Login,
		arg.RoleID,
		arg.InvitedBy,
		arg.CreatedAt,
	)
	return err
}
