// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_links.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const countProjectWorkspaces = `-- name: CountProjectWorkspaces :one
SELECT COUNT(DISTINCT workspace_id) FROM projects WHERE id IN (?1, ?2)
`

type CountProjectWorkspacesParams struct {
	ProjectA string
	ProjectB string
}

func (q *Queries) CountProjectWorkspaces(ctx context.Context, arg CountProjectWorkspacesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProjectWorkspaces, arg.ProjectA, arg.ProjectB)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTicketBlocker = `-- name: DeleteTicketBlocker :execrows
DELETE FROM ticket_links WHERE ticket_id = ? AND kind = 'blocked_by' AND target_id = ?
`

type DeleteTicketBlockerParams struct {
	TicketID string
	TargetID sql.NullString
}

func (q *Queries) DeleteTicketBlocker(ctx context.Context, arg DeleteTicketBlockerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketBlocker, arg.TicketID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTicketFoundIn = `-- name: DeleteTicketFoundIn :execrows
DELETE FROM ticket_links WHERE ticket_id = ? AND kind = 'found_in'
`

func (q *Queries) DeleteTicketFoundIn(ctx context.Context, ticketID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketFoundIn, ticketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTicketStage = `-- name: GetTicketStage :one
SELECT s.kind AS stage FROM tickets t LEFT JOIN statuses s ON s.id = t.status WHERE t.id = ?
`

func (q *Queries) GetTicketStage(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getTicketStage, id)
	var stage sql.NullString
	err := row.Scan(&stage)
	return stage, err
}

const insertTicketLink = `-- name: InsertTicketLink :exec
INSERT INTO ticket_links (ticket_id, kind, target_id, created_at) VALUES (?, ?, ?, ?)
`

type InsertTicketLinkParams struct {
	TicketID  string
	Kind      string
	TargetID  sql.NullString
	CreatedAt int64
}

func (q *Queries) InsertTicketLink(ctx context.Context, arg InsertTicketLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketLink,
		arg.TicketID,
		arg.Kind,
		arg.TargetID,
		arg.CreatedAt,
	)
	return err
}

const listTicketBlockerIDs = `-- name: ListTicketBlockerIDs :many
SELECT target_id FROM ticket_links WHERE ticket_id = ? AND kind = 'blocked_by' AND target_id IS NOT NULL
`

func (q *Queries) ListTicketBlockerIDs(ctx context.Context, ticketID string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listTicketBlockerIDs, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var target_id sql.NullString
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinksFrom = `-- name: ListTicketLinksFrom :many
SELECT l.kind, l.target_id, t.project_id, t.number, t.title, t.status, p.prefix, s.kind AS stage
FROM ticket_links l
LEFT JOIN tickets t ON t.id = l.target_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.ticket_id = ?
ORDER BY l.created_at, l.target_id
`

type ListTicketLinksFromRow struct {
	Kind      string
	TargetID  sql.NullString
	ProjectID sql.NullString
	Number    sql.NullInt64
	Title     sql.NullString
	Status    sql.NullString
	Prefix    sql.NullString
	Stage     sql.NullString
}

func (q *Queries) ListTicketLinksFrom(ctx context.Context, ticketID string) ([]ListTicketLinksFromRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLinksFrom, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketLinksFromRow
	for rows.Next() {
		var i ListTicketLinksFromRow
		if err := rows.Scan(
			&i.Kind,
			&i.TargetID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinksTo = `-- name: ListTicketLinksTo :many
SELECT l.kind, l.ticket_id, t.project_id, t.number, t.title, t.status, p.prefix, s.kind AS stage
FROM ticket_links l
JOIN tickets t ON t.id = l.ticket_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.target_id = ?
ORDER BY l.created_at, l.ticket_id
`

type ListTicketLinksToRow struct {
	Kind      string
	TicketID  string
	ProjectID sql.NullString
	Number    int64
	Title     string
	Status    string
	Prefix    sql.NullString
	Stage     sql.NullString
}

func (q *Queries) ListTicketLinksTo(ctx context.Context, targetID sql.NullString) ([]ListTicketLinksToRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLinksTo, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketLinksToRow
	for rows.Next() {
		var i ListTicketLinksToRow
		if err := rows.Scan(
			&i.Kind,
			&i.TicketID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsWaitingOnlyOn = `-- name: ListTicketsWaitingOnlyOn :many
SELECT l.ticket_id, t.project_id
FROM ticket_links l
JOIN tickets t ON t.id = l.ticket_id
LEFT JOIN statuses ts ON ts.id = t.status
WHERE l.kind = 'blocked_by' AND l.target_id = ?1 AND COALESCE(ts.kind, '') != 'done'
  AND NOT EXISTS (
    SELECT 1 FROM ticket_links o
    JOIN tickets b ON b.id = o.target_id
    LEFT JOIN statuses s ON s.id = b.status
    WHERE o.ticket_id = l.ticket_id AND o.kind = 'blocked_by' AND o.target_id != ?1
      AND COALESCE(s.kind, '') != 'done'
  )
ORDER BY l.ticket_id
`

type ListTicketsWaitingOnlyOnRow struct {
	TicketID  string
	ProjectID sql.NullString
}

func (q *Queries) ListTicketsWaitingOnlyOn(ctx context.Context, blockerID sql.NullString) ([]ListTicketsWaitingOnlyOnRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsWaitingOnlyOn, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsWaitingOnlyOnRow
	for rows.Next() {
		var i ListTicketsWaitingOnlyOnRow
		if err := rows.Scan(&i.TicketID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclearedTicketBlockers = `-- name: ListUnclearedTicketBlockers :many
SELECT l.ticket_id AS blocked_id, t.id, t.project_id, t.number, t.title, t.status, p.prefix
FROM ticket_links l
JOIN tickets t ON t.id = l.target_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.kind = 'blocked_by' AND COALESCE(s.kind, '') != 'done'
ORDER BY l.ticket_id, l.created_at, t.id
`

type ListUnclearedTicketBlockersRow struct {
	BlockedID string
	ID        string
	ProjectID sql.NullString
	Number    int64
	Title     string
	Status    string
	Prefix    sql.NullString
}

func (q *Queries) ListUnclearedTicketBlockers(ctx context.Context) ([]ListUnclearedTicketBlockersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnclearedTicketBlockers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclearedTicketBlockersRow
	for rows.Next() {
		var i ListUnclearedTicketBlockersRow
		if err := rows.Scan(
			&i.BlockedID,
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclearedTicketBlockersOf = `-- name: ListUnclearedTicketBlockersOf :many
SELECT l.ticket_id AS blocked_id, t.id, t.project_id, t.number, t.title, t.status, p.prefix
FROM ticket_links l
JOIN tickets t ON t.id = l.target_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.kind = 'blocked_by' AND COALESCE(s.kind, '') != 'done' AND l.ticket_id IN (/*SLICE:ids*/?)
ORDER BY l.ticket_id, l.created_at, t.id
`

type ListUnclearedTicketBlockersOfRow struct {
	BlockedID string
	ID        string
	ProjectID sql.NullString
	Number    int64
	Title     string
	Status    string
	Prefix    sql.NullString
}

func (q *Queries) ListUnclearedTicketBlockersOf(ctx context.Context, ids []string) ([]ListUnclearedTicketBlockersOfRow, error) {
	query := listUnclearedTicketBlockersOf
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclearedTicketBlockersOfRow
	for rows.Next() {
		var i ListUnclearedTicketBlockersOfRow
		if err := rows.Scan(
			&i.BlockedID,
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
