// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_types.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countTicketTypeTickets = `-- name: CountTicketTypeTickets :one
SELECT COUNT(*) FROM tickets WHERE type_id = ?
`

func (q *Queries) CountTicketTypeTickets(ctx context.Context, typeID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketTypeTickets, typeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicketType = `-- name: CreateTicketType :exec
INSERT INTO ticket_types (id, project_id, name, position, color, body_template, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTicketTypeParams struct {
	ID           string
	ProjectID    string
	Name         string
	Position     int64
	Color        string
	BodyTemplate string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) error {
	_, err := q.db.ExecContext(ctx, createTicketType,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Position,
		arg.Color,
		arg.BodyTemplate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTicketType = `-- name: DeleteTicketType :execrows
DELETE FROM ticket_types WHERE id = ?
`

func (q *Queries) DeleteTicketType(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketType, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTicketType = `-- name: GetTicketType :one
SELECT id, project_id, name, position, color, created_at, updated_at, body_template FROM ticket_types WHERE id = ?
`

func (q *Queries) GetTicketType(ctx context.Context, id string) (TicketType, error) {
	row := q.db.QueryRowContext(ctx, getTicketType, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodyTemplate,
	)
	return i, err
}

const listTicketTypesByProject = `-- name: ListTicketTypesByProject :many
SELECT id, project_id, name, position, color, created_at, updated_at, body_template FROM ticket_types WHERE project_id = ? ORDER BY position, id
`

func (q *Queries) ListTicketTypesByProject(ctx context.Context, projectID string) ([]TicketType, error) {
	rows, err := q.db.QueryContext(ctx, listTicketTypesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketType
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyTemplate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderTicketTypePosition = `-- name: ReorderTicketTypePosition :execrows
UPDATE ticket_types SET position = ?, updated_at = ? WHERE id = ? AND project_id = ?
`

type ReorderTicketTypePositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
	ProjectID string
}

func (q *Queries) ReorderTicketTypePosition(ctx context.Context, arg ReorderTicketTypePositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reorderTicketTypePosition,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicketTypeMeta = `-- name: UpdateTicketTypeMeta :execrows
UPDATE ticket_types SET name = ?, color = ?, body_template = ?, updated_at = ? WHERE id = ?
`

type UpdateTicketTypeMetaParams struct {
	Name         string
	Color        string
	BodyTemplate string
	UpdatedAt    int64
	ID           string
}

func (q *Queries) UpdateTicketTypeMeta(ctx context.Context, arg UpdateTicketTypeMetaParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTicketTypeMeta,
		arg.Name,
		arg.Color,
		arg.BodyTemplate,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
