// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_links.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteTicketBlocker = `-- name: DeleteTicketBlocker :execrows
DELETE FROM ticket_links WHERE ticket_id = ? AND kind = 'blocked_by' AND target_id = ?
`

type DeleteTicketBlockerParams struct {
	TicketID string
	TargetID sql.NullString
}

func (q *Queries) DeleteTicketBlocker(ctx context.Context, arg DeleteTicketBlockerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketBlocker, arg.TicketID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTicketFoundIn = `-- name: DeleteTicketFoundIn :execrows
DELETE FROM ticket_links WHERE ticket_id = ? AND kind = 'found_in'
`

func (q *Queries) DeleteTicketFoundIn(ctx context.Context, ticketID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicketFoundIn, ticketID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertTicketLink = `-- name: InsertTicketLink :exec
INSERT INTO ticket_links (ticket_id, kind, target_id, created_at) VALUES (?, ?, ?, ?)
`

type InsertTicketLinkParams struct {
	TicketID  string
	Kind      string
	TargetID  sql.NullString
	CreatedAt int64
}

func (q *Queries) InsertTicketLink(ctx context.Context, arg InsertTicketLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertTicketLink,
		arg.TicketID,
		arg.Kind,
		arg.TargetID,
		arg.CreatedAt,
	)
	return err
}

const listTicketBlockerIDs = `-- name: ListTicketBlockerIDs :many
SELECT target_id FROM ticket_links WHERE ticket_id = ? AND kind = 'blocked_by' AND target_id IS NOT NULL
`

func (q *Queries) ListTicketBlockerIDs(ctx context.Context, ticketID string) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listTicketBlockerIDs, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var target_id sql.NullString
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinksFrom = `-- name: ListTicketLinksFrom :many
SELECT l.kind, l.target_id, t.project_id, t.number, t.title, t.status, p.prefix, s.kind AS stage
FROM ticket_links l
LEFT JOIN tickets t ON t.id = l.target_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.ticket_id = ?
ORDER BY l.created_at, l.target_id
`

type ListTicketLinksFromRow struct {
	Kind      string
	TargetID  sql.NullString
	ProjectID sql.NullString
	Number    sql.NullInt64
	Title     sql.NullString
	Status    sql.NullString
	Prefix    sql.NullString
	Stage     sql.NullString
}

func (q *Queries) ListTicketLinksFrom(ctx context.Context, ticketID string) ([]ListTicketLinksFromRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLinksFrom, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketLinksFromRow
	for rows.Next() {
		var i ListTicketLinksFromRow
		if err := rows.Scan(
			&i.Kind,
			&i.TargetID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLinksTo = `-- name: ListTicketLinksTo :many
SELECT l.kind, l.ticket_id, t.project_id, t.number, t.title, t.status, p.prefix, s.kind AS stage
FROM ticket_links l
JOIN tickets t ON t.id = l.ticket_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.target_id = ?
ORDER BY l.created_at, l.ticket_id
`

type ListTicketLinksToRow struct {
	Kind      string
	TicketID  string
	ProjectID sql.NullString
	Number    int64
	Title     string
	Status    string
	Prefix    sql.NullString
	Stage     sql.NullString
}

func (q *Queries) ListTicketLinksTo(ctx context.Context, targetID sql.NullString) ([]ListTicketLinksToRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLinksTo, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketLinksToRow
	for rows.Next() {
		var i ListTicketLinksToRow
		if err := rows.Scan(
			&i.Kind,
			&i.TicketID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
			&i.Stage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnclearedTicketBlockers = `-- name: ListUnclearedTicketBlockers :many
SELECT l.ticket_id AS blocked_id, t.id, t.project_id, t.number, t.title, t.status, p.prefix
FROM ticket_links l
JOIN tickets t ON t.id = l.target_id
LEFT JOIN projects p ON p.id = t.project_id
LEFT JOIN statuses s ON s.id = t.status
WHERE l.kind = 'blocked_by' AND COALESCE(s.kind, '') != 'done'
ORDER BY l.ticket_id, l.created_at, t.id
`

type ListUnclearedTicketBlockersRow struct {
	BlockedID string
	ID        string
	ProjectID sql.NullString
	Number    int64
	Title     string
	Status    string
	Prefix    sql.NullString
}

func (q *Queries) ListUnclearedTicketBlockers(ctx context.Context) ([]ListUnclearedTicketBlockersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnclearedTicketBlockers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnclearedTicketBlockersRow
	for rows.Next() {
		var i ListUnclearedTicketBlockersRow
		if err := rows.Scan(
			&i.BlockedID,
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Prefix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
