// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const addTicketLabel = `-- name: AddTicketLabel :exec
INSERT INTO ticket_labels (ticket_id, label) VALUES (?, ?)
ON CONFLICT(ticket_id, label) DO NOTHING
`

type AddTicketLabelParams struct {
	TicketID string
	Label    string
}

func (q *Queries) AddTicketLabel(ctx context.Context, arg AddTicketLabelParams) error {
	_, err := q.db.ExecContext(ctx, addTicketLabel, arg.TicketID, arg.Label)
	return err
}

const createTicket = `-- name: CreateTicket :exec
INSERT INTO tickets (id, title, body, status, position, number, doc_id, project_id, category_id, type_id, assignee, created_at, updated_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTicketParams struct {
	ID         string
	Title      string
	Body       string
	Status     string
	Position   int64
	Number     int64
	DocID      sql.NullString
	ProjectID  sql.NullString
	CategoryID sql.NullString
	TypeID     sql.NullString
	Assignee   string
	CreatedAt  int64
	UpdatedAt  int64
	FinishedAt sql.NullInt64
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) error {
	_, err := q.db.ExecContext(ctx, createTicket,
		arg.ID,
		arg.Title,
		arg.Body,
		arg.Status,
		arg.Position,
		arg.Number,
		arg.DocID,
		arg.ProjectID,
		arg.CategoryID,
		arg.TypeID,
		arg.Assignee,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteTicket = `-- name: DeleteTicket :execrows
DELETE FROM tickets WHERE id = ?
`

func (q *Queries) DeleteTicket(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTicket, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTicket = `-- name: GetTicket :one
SELECT id, title, body, status, doc_id, assignee, created_at, updated_at, project_id, category_id, type_id, finished_at, position, number FROM tickets WHERE id = ?
`

func (q *Queries) GetTicket(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DocID,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.CategoryID,
		&i.TypeID,
		&i.FinishedAt,
		&i.Position,
		&i.Number,
	)
	return i, err
}

const getTicketByPrefixAndNumber = `-- name: GetTicketByPrefixAndNumber :one
SELECT tickets.id, tickets.title, tickets.body, tickets.status, tickets.doc_id, tickets.assignee, tickets.created_at, tickets.updated_at, tickets.project_id, tickets.category_id, tickets.type_id, tickets.finished_at, tickets.position, tickets.number FROM tickets JOIN projects ON tickets.project_id = projects.id WHERE projects.prefix = ? AND tickets.number = ?
`

type GetTicketByPrefixAndNumberParams struct {
	Prefix string
	Number int64
}

func (q *Queries) GetTicketByPrefixAndNumber(ctx context.Context, arg GetTicketByPrefixAndNumberParams) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByPrefixAndNumber, arg.Prefix, arg.Number)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.DocID,
		&i.Assignee,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.CategoryID,
		&i.TypeID,
		&i.FinishedAt,
		&i.Position,
		&i.Number,
	)
	return i, err
}

const getTicketStatusAndCategory = `-- name: GetTicketStatusAndCategory :one
SELECT status, category_id FROM tickets WHERE id = ?
`

type GetTicketStatusAndCategoryRow struct {
	Status     string
	CategoryID sql.NullString
}

func (q *Queries) GetTicketStatusAndCategory(ctx context.Context, id string) (GetTicketStatusAndCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketStatusAndCategory, id)
	var i GetTicketStatusAndCategoryRow
	err := row.Scan(&i.Status, &i.CategoryID)
	return i, err
}

const linkTicketBranch = `-- name: LinkTicketBranch :exec
INSERT INTO ticket_branch_links (ticket_id, branch_owner, branch_repo, branch_name, linked_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(ticket_id, branch_owner, branch_repo, branch_name) DO NOTHING
`

type LinkTicketBranchParams struct {
	TicketID    string
	BranchOwner string
	BranchRepo  string
	BranchName  string
	LinkedAt    int64
}

func (q *Queries) LinkTicketBranch(ctx context.Context, arg LinkTicketBranchParams) error {
	_, err := q.db.ExecContext(ctx, linkTicketBranch,
		arg.TicketID,
		arg.BranchOwner,
		arg.BranchRepo,
		arg.BranchName,
		arg.LinkedAt,
	)
	return err
}

const linkTicketPR = `-- name: LinkTicketPR :exec
INSERT INTO ticket_pr_links (ticket_id, pr_owner, pr_repo, pr_number, pr_title, pr_sha, pr_state, linked_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticket_id, pr_owner, pr_repo, pr_number) DO NOTHING
`

type LinkTicketPRParams struct {
	TicketID string
	PrOwner  string
	PrRepo   string
	PrNumber int64
	PrTitle  string
	PrSha    string
	PrState  string
	LinkedAt int64
}

func (q *Queries) LinkTicketPR(ctx context.Context, arg LinkTicketPRParams) error {
	_, err := q.db.ExecContext(ctx, linkTicketPR,
		arg.TicketID,
		arg.PrOwner,
		arg.PrRepo,
		arg.PrNumber,
		arg.PrTitle,
		arg.PrSha,
		arg.PrState,
		arg.LinkedAt,
	)
	return err
}

const listAllTicketLabels = `-- name: ListAllTicketLabels :many
SELECT DISTINCT label FROM ticket_labels ORDER BY label
`

func (q *Queries) ListAllTicketLabels(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllTicketLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelColors = `-- name: ListLabelColors :many
SELECT label, color FROM label_colors WHERE project_id = ? AND label IN (/*SLICE:labels*/?)
`

type ListLabelColorsParams struct {
	ProjectID string
	Labels    []string
}

type ListLabelColorsRow struct {
	Label string
	Color string
}

func (q *Queries) ListLabelColors(ctx context.Context, arg ListLabelColorsParams) ([]ListLabelColorsRow, error) {
	query := listLabelColors
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.Labels) > 0 {
		for _, v := range arg.Labels {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:labels*/?", strings.Repeat(",?", len(arg.Labels))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:labels*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelColorsRow
	for rows.Next() {
		var i ListLabelColorsRow
		if err := rows.Scan(&i.Label, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketBranchLinks = `-- name: ListTicketBranchLinks :many
SELECT branch_owner, branch_repo, branch_name FROM ticket_branch_links WHERE ticket_id = ? ORDER BY linked_at
`

type ListTicketBranchLinksRow struct {
	BranchOwner string
	BranchRepo  string
	BranchName  string
}

func (q *Queries) ListTicketBranchLinks(ctx context.Context, ticketID string) ([]ListTicketBranchLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketBranchLinks, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketBranchLinksRow
	for rows.Next() {
		var i ListTicketBranchLinksRow
		if err := rows.Scan(&i.BranchOwner, &i.BranchRepo, &i.BranchName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketIDsByPR = `-- name: ListTicketIDsByPR :many
SELECT ticket_id FROM ticket_pr_links WHERE pr_owner = ? AND pr_repo = ? AND pr_number = ?
`

type ListTicketIDsByPRParams struct {
	PrOwner  string
	PrRepo   string
	PrNumber int64
}

func (q *Queries) ListTicketIDsByPR(ctx context.Context, arg ListTicketIDsByPRParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTicketIDsByPR, arg.PrOwner, arg.PrRepo, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ticket_id string
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLabels = `-- name: ListTicketLabels :many
SELECT label FROM ticket_labels WHERE ticket_id = ? ORDER BY label
`

func (q *Queries) ListTicketLabels(ctx context.Context, ticketID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTicketLabels, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketLabelsForTickets = `-- name: ListTicketLabelsForTickets :many
SELECT ticket_id, label FROM ticket_labels WHERE ticket_id IN (/*SLICE:ids*/?) ORDER BY label
`

func (q *Queries) ListTicketLabelsForTickets(ctx context.Context, ids []string) ([]TicketLabel, error) {
	query := listTicketLabelsForTickets
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketLabel
	for rows.Next() {
		var i TicketLabel
		if err := rows.Scan(&i.TicketID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketPRLinks = `-- name: ListTicketPRLinks :many
SELECT pr_owner, pr_repo, pr_number, pr_title, pr_sha, pr_state FROM ticket_pr_links WHERE ticket_id = ? ORDER BY linked_at
`

type ListTicketPRLinksRow struct {
	PrOwner  string
	PrRepo   string
	PrNumber int64
	PrTitle  string
	PrSha    string
	PrState  string
}

func (q *Queries) ListTicketPRLinks(ctx context.Context, ticketID string) ([]ListTicketPRLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketPRLinks, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketPRLinksRow
	for rows.Next() {
		var i ListTicketPRLinksRow
		if err := rows.Scan(
			&i.PrOwner,
			&i.PrRepo,
			&i.PrNumber,
			&i.PrTitle,
			&i.PrSha,
			&i.PrState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketPRLinksBatch = `-- name: ListTicketPRLinksBatch :many
SELECT ticket_id, pr_owner, pr_repo, pr_number, pr_title, pr_sha, pr_state FROM ticket_pr_links WHERE ticket_id IN (/*SLICE:ids*/?) ORDER BY linked_at
`

type ListTicketPRLinksBatchRow struct {
	TicketID string
	PrOwner  string
	PrRepo   string
	PrNumber int64
	PrTitle  string
	PrSha    string
	PrState  string
}

func (q *Queries) ListTicketPRLinksBatch(ctx context.Context, ids []string) ([]ListTicketPRLinksBatchRow, error) {
	query := listTicketPRLinksBatch
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketPRLinksBatchRow
	for rows.Next() {
		var i ListTicketPRLinksBatchRow
		if err := rows.Scan(
			&i.TicketID,
			&i.PrOwner,
			&i.PrRepo,
			&i.PrNumber,
			&i.PrTitle,
			&i.PrSha,
			&i.PrState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, title, body, status, doc_id, assignee, created_at, updated_at, project_id, category_id, type_id, finished_at, position, number FROM tickets ORDER BY created_at
`

func (q *Queries) ListTickets(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DocID,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.CategoryID,
			&i.TypeID,
			&i.FinishedAt,
			&i.Position,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByDoc = `-- name: ListTicketsByDoc :many
SELECT id, title, body, status, doc_id, assignee, created_at, updated_at, project_id, category_id, type_id, finished_at, position, number FROM tickets WHERE doc_id = ? ORDER BY created_at
`

func (q *Queries) ListTicketsByDoc(ctx context.Context, docID sql.NullString) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByDoc, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DocID,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.CategoryID,
			&i.TypeID,
			&i.FinishedAt,
			&i.Position,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByProject = `-- name: ListTicketsByProject :many
SELECT id, title, body, status, doc_id, assignee, created_at, updated_at, project_id, category_id, type_id, finished_at, position, number FROM tickets WHERE project_id = ? ORDER BY created_at
`

func (q *Queries) ListTicketsByProject(ctx context.Context, projectID sql.NullString) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.DocID,
			&i.Assignee,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectID,
			&i.CategoryID,
			&i.TypeID,
			&i.FinishedAt,
			&i.Position,
			&i.Number,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxTicketNumberInProject = `-- name: MaxTicketNumberInProject :one
SELECT MAX(number) FROM tickets WHERE project_id IS ?
`

func (q *Queries) MaxTicketNumberInProject(ctx context.Context, projectID sql.NullString) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxTicketNumberInProject, projectID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const maxTicketPositionInPair = `-- name: MaxTicketPositionInPair :one
SELECT MAX(position) FROM tickets WHERE status = ? AND category_id IS ?
`

type MaxTicketPositionInPairParams struct {
	Status     string
	CategoryID sql.NullString
}

func (q *Queries) MaxTicketPositionInPair(ctx context.Context, arg MaxTicketPositionInPairParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, maxTicketPositionInPair, arg.Status, arg.CategoryID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const moveTicketCategory = `-- name: MoveTicketCategory :execrows
UPDATE tickets SET category_id = ?, position = ?, updated_at = ? WHERE id = ?
`

type MoveTicketCategoryParams struct {
	CategoryID sql.NullString
	Position   int64
	UpdatedAt  int64
	ID         string
}

func (q *Queries) MoveTicketCategory(ctx context.Context, arg MoveTicketCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveTicketCategory,
		arg.CategoryID,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const removeTicketLabel = `-- name: RemoveTicketLabel :exec
DELETE FROM ticket_labels WHERE ticket_id = ? AND label = ?
`

type RemoveTicketLabelParams struct {
	TicketID string
	Label    string
}

func (q *Queries) RemoveTicketLabel(ctx context.Context, arg RemoveTicketLabelParams) error {
	_, err := q.db.ExecContext(ctx, removeTicketLabel, arg.TicketID, arg.Label)
	return err
}

const setLabelColor = `-- name: SetLabelColor :exec
INSERT INTO label_colors (project_id, label, color, created_at, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(project_id, label) DO UPDATE SET color = excluded.color, updated_at = excluded.updated_at
`

type SetLabelColorParams struct {
	ProjectID string
	Label     string
	Color     string
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) SetLabelColor(ctx context.Context, arg SetLabelColorParams) error {
	_, err := q.db.ExecContext(ctx, setLabelColor,
		arg.ProjectID,
		arg.Label,
		arg.Color,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const setTicketFinishedAt = `-- name: SetTicketFinishedAt :execrows
UPDATE tickets SET finished_at = ? WHERE id = ? AND finished_at IS NULL
`

type SetTicketFinishedAtParams struct {
	FinishedAt sql.NullInt64
	ID         string
}

func (q *Queries) SetTicketFinishedAt(ctx context.Context, arg SetTicketFinishedAtParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTicketFinishedAt, arg.FinishedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTicketPosition = `-- name: SetTicketPosition :execrows
UPDATE tickets SET position = ?, updated_at = ? WHERE id = ?
`

type SetTicketPositionParams struct {
	Position  int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) SetTicketPosition(ctx context.Context, arg SetTicketPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTicketPosition, arg.Position, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicketAssignee = `-- name: UpdateTicketAssignee :execrows
UPDATE tickets SET assignee = ?, updated_at = ? WHERE id = ?
`

type UpdateTicketAssigneeParams struct {
	Assignee  string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateTicketAssignee(ctx context.Context, arg UpdateTicketAssigneeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTicketAssignee, arg.Assignee, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicketPRState = `-- name: UpdateTicketPRState :exec
UPDATE ticket_pr_links SET pr_state = ? WHERE pr_owner = ? AND pr_repo = ? AND pr_number = ?
`

type UpdateTicketPRStateParams struct {
	PrState  string
	PrOwner  string
	PrRepo   string
	PrNumber int64
}

func (q *Queries) UpdateTicketPRState(ctx context.Context, arg UpdateTicketPRStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketPRState,
		arg.PrState,
		arg.PrOwner,
		arg.PrRepo,
		arg.PrNumber,
	)
	return err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :execrows
UPDATE tickets SET status = ?, position = ?, updated_at = ? WHERE id = ?
`

type UpdateTicketStatusParams struct {
	Status    string
	Position  int64
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTicketStatus,
		arg.Status,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicketTitleBody = `-- name: UpdateTicketTitleBody :execrows
UPDATE tickets SET title = ?, body = ?, updated_at = ? WHERE id = ?
`

type UpdateTicketTitleBodyParams struct {
	Title     string
	Body      string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateTicketTitleBody(ctx context.Context, arg UpdateTicketTitleBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTicketTitleBody,
		arg.Title,
		arg.Body,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTicketType = `-- name: UpdateTicketType :execrows
UPDATE tickets SET type_id = ?, updated_at = ? WHERE id = ?
`

type UpdateTicketTypeParams struct {
	TypeID    sql.NullString
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTicketType, arg.TypeID, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
