// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topology.sql

package sqlcgen

import (
	"context"
)

const getTopologyCanvas = `-- name: GetTopologyCanvas :one
SELECT canvas FROM topology WHERE environment = ?
`

func (q *Queries) GetTopologyCanvas(ctx context.Context, environment string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getTopologyCanvas, environment)
	var canvas []byte
	err := row.Scan(&canvas)
	return canvas, err
}

const saveTopology = `-- name: SaveTopology :exec
INSERT INTO topology (environment, schema_version, canvas, updated_at) VALUES (?, ?, ?, ?)
ON CONFLICT(environment) DO UPDATE SET
    schema_version = excluded.schema_version,
    canvas = excluded.canvas,
    updated_at = excluded.updated_at
`

type SaveTopologyParams struct {
	Environment   string
	SchemaVersion int64
	Canvas        []byte
	UpdatedAt     int64
}

func (q *Queries) SaveTopology(ctx context.Context, arg SaveTopologyParams) error {
	_, err := q.db.ExecContext(ctx, saveTopology,
		arg.Environment,
		arg.SchemaVersion,
		arg.Canvas,
		arg.UpdatedAt,
	)
	return err
}
