package eventcatalog

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"maps"
	"os"
	"slices"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/otal-labs/nexul/internal/platform/eventbus"
)

var updateEventSchemas = flag.Bool("update-event-schemas", false, "rewrite the published event contract from the payload types")

// contractFile is the published event contract for reading and diffing; the SDK generates its event types from it.
const contractFile = "schemas.json"

// publishedFile holds the same schemas compact, as the server publishes them, so a boot parses nothing.
const publishedFile = "schemas_gen.go"

// TestSchemas_MatchThePublishedContract fails on a payload change that would break a consumer of the published catalog
// (ADR 0044): a field removed or renamed, a type widened, an enum value dropped, a field no longer always sent. It
// also fails when the file lags an additive change, the way sqlc diff does; make event-schemas brings it level.
func TestSchemas_MatchThePublishedContract(t *testing.T) {
	generated, err := generateSchemas()
	require.NoError(t, err)
	onFile := readContract(t)

	require.Empty(t, breaking(decode(t, onFile), decode(t, generated)),
		"the published event contract only grows; ship a new field or topic beside the old one instead")
	if *updateEventSchemas {
		writeContract(t, generated)
		return
	}
	assert.Empty(t, differing(onFile, generated), "stale; regenerate with make event-schemas")
	assert.Empty(t, differing(Schemas(), generated), "stale; regenerate with make event-schemas")
}

func differing(a, b map[string]string) []string {
	var names []string
	for _, name := range slices.Sorted(maps.Keys(a)) {
		if a[name] != b[name] {
			names = append(names, name)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(b)) {
		if _, ok := a[name]; !ok {
			names = append(names, name)
		}
	}
	return names
}

func readContract(t *testing.T) map[string]string {
	t.Helper()
	raw, err := os.ReadFile(contractFile)
	require.NoError(t, err)
	var schemas map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(raw, &schemas))
	out := make(map[string]string, len(schemas))
	for name, schema := range schemas {
		var text bytes.Buffer
		require.NoError(t, json.Compact(&text, schema))
		out[name] = text.String()
	}
	return out
}

func writeContract(t *testing.T, schemas map[string]string) {
	t.Helper()
	raws := make(map[string]json.RawMessage, len(schemas))
	for name, text := range schemas {
		raws[name] = json.RawMessage(text)
	}
	out, err := json.MarshalIndent(raws, "", "  ")
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(contractFile, append(out, '\n'), 0o644))

	var src bytes.Buffer
	src.WriteString("// Code generated by make event-schemas. DO NOT EDIT.\n\npackage eventcatalog\n\nvar published = map[string]string{\n")
	for _, name := range slices.Sorted(maps.Keys(schemas)) {
		fmt.Fprintf(&src, "\t%q: %q,\n", name, schemas[name])
	}
	src.WriteString("}\n")
	formatted, err := format.Source(src.Bytes())
	require.NoError(t, err)
	require.NoError(t, os.WriteFile(publishedFile, formatted, 0o644))
}

func TestGenerateSchemas_GivesTheSameTextEveryTime(t *testing.T) {
	first, err := generateSchemas()
	require.NoError(t, err)
	for range 5 {
		again, err := generateSchemas()
		require.NoError(t, err)
		assert.Equal(t, first, again)
	}
}

func TestSchemas_CoverEveryRegisteredTopic(t *testing.T) {
	assert.Equal(t, AllTopics(), slices.Sorted(maps.Keys(Schemas())))
}

type orderV1 struct {
	ID     string    `json:"id"`
	Status string    `json:"status" enum:"open,closed"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

type orderAddedField struct {
	ID     string    `json:"id"`
	Status string    `json:"status" enum:"open,closed,archived"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
	Owner  string    `json:"owner,omitempty"`
}

type orderRemovedField struct {
	ID     string `json:"id"`
	Status string `json:"status" enum:"open,closed"`
	Note   string `json:"note,omitempty"`
}

type orderRenamedField struct {
	ID     string    `json:"id"`
	Status string    `json:"status" enum:"open,closed"`
	Remark string    `json:"remark,omitempty"`
	At     time.Time `json:"at"`
}

type orderRetyped struct {
	ID     int       `json:"id"`
	Status string    `json:"status" enum:"open,closed"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

type orderNullableID struct {
	ID     *string   `json:"id"`
	Status string    `json:"status" enum:"open,closed"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

type orderEnumValueDropped struct {
	ID     string    `json:"id"`
	Status string    `json:"status" enum:"open"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

type orderNoLongerAlwaysSent struct {
	ID     string    `json:"id,omitempty"`
	Status string    `json:"status" enum:"open,closed"`
	Note   string    `json:"note,omitempty"`
	At     time.Time `json:"at"`
}

type orderNested struct {
	Order orderV1 `json:"order"`
}

type orderNestedRetyped struct {
	Order orderRetyped `json:"order"`
}

func TestBreaking_OnlyLetsThePublishedContractGrow(t *testing.T) {
	tests := []struct {
		name    string
		from    any
		to      any
		problem string
	}{
		{"an added field and enum value pass", orderV1{}, orderAddedField{}, ""},
		{"an unchanged payload passes", orderV1{}, orderV1{}, ""},
		{"a removed field fails", orderV1{}, orderRemovedField{}, "t.order/at: removed"},
		{"a renamed field fails", orderV1{}, orderRenamedField{}, "t.order/note: removed"},
		{"a type change fails", orderV1{}, orderRetyped{}, "t.order/id: type string became integer"},
		{"dropping null passes", orderNullableID{}, orderV1{}, ""},
		{"adding null fails", orderV1{}, orderNullableID{}, "t.order/id: type string became null|string"},
		{"a dropped enum value fails", orderV1{}, orderEnumValueDropped{}, "t.order/status: enum value closed removed"},
		{"a field no longer always sent fails", orderV1{}, orderNoLongerAlwaysSent{}, "t.order: id no longer required"},
		{"a change inside a nested object fails", orderNested{}, orderNestedRetyped{}, "t.order/order/id: type string became integer"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			problems := breaking(contractOf(t, tt.from), contractOf(t, tt.to))
			if tt.problem == "" {
				assert.Empty(t, problems)
				return
			}
			assert.Contains(t, problems, tt.problem)
		})
	}
}

func TestBreaking_ARemovedTopicFails(t *testing.T) {
	assert.Equal(t, []string{"t.order: topic removed"}, breaking(contractOf(t, orderV1{}), map[string]any{}))
}

// contractOf generates payload's schema as the topic t.order, decoded the way the contract file holds it.
func contractOf(t *testing.T, payload any) map[string]any {
	t.Helper()
	generated, err := generate([]eventbus.Topic{{Name: "t.order", Payload: payload}})
	require.NoError(t, err)
	texts := map[string]string{}
	for name, s := range generated {
		text, err := json.Marshal(s)
		require.NoError(t, err)
		texts[name] = string(text)
	}
	return decode(t, texts)
}

func decode(t *testing.T, texts map[string]string) map[string]any {
	t.Helper()
	out := make(map[string]any, len(texts))
	for name, text := range texts {
		var s any
		require.NoError(t, json.Unmarshal([]byte(text), &s), name)
		out[name] = s
	}
	return out
}

// breaking lists what a consumer of the old contract would lose in the new one: a topic, a field, a type, an enum
// value, or a field it could count on being sent.
func breaking(old, current map[string]any) []string {
	var problems []string
	for _, name := range slices.Sorted(maps.Keys(old)) {
		next, ok := current[name]
		if !ok {
			problems = append(problems, name+": topic removed")
			continue
		}
		problems = append(problems, breakingAt(name, old[name], next)...)
	}
	return problems
}

func breakingAt(path string, oldNode, newNode any) []string {
	o, _ := oldNode.(map[string]any)
	n, _ := newNode.(map[string]any)
	var problems []string
	if a, b := types(o), types(n); !narrows(a, b) {
		problems = append(problems, fmt.Sprintf("%s: type %s became %s", path, typeName(a), typeName(b)))
	}
	if oldEnum, ok := o["enum"].([]any); ok {
		newEnum, _ := n["enum"].([]any)
		for _, v := range oldEnum {
			if !slices.Contains(newEnum, v) {
				problems = append(problems, fmt.Sprintf("%s: enum value %v removed", path, v))
			}
		}
	}
	newRequired, _ := n["required"].([]any)
	if oldRequired, ok := o["required"].([]any); ok {
		for _, name := range oldRequired {
			if !slices.Contains(newRequired, name) {
				problems = append(problems, fmt.Sprintf("%s: %v no longer required", path, name))
			}
		}
	}
	oldProps, _ := o["properties"].(map[string]any)
	newProps, _ := n["properties"].(map[string]any)
	for _, name := range slices.Sorted(maps.Keys(oldProps)) {
		next, ok := newProps[name]
		if !ok {
			problems = append(problems, fmt.Sprintf("%s/%s: removed", path, name))
			continue
		}
		problems = append(problems, breakingAt(path+"/"+name, oldProps[name], next)...)
	}
	for _, key := range []string{"items", "additionalProperties"} {
		if sub, ok := o[key]; ok {
			problems = append(problems, breakingAt(path+"/"+key, sub, n[key])...)
		}
	}
	return problems
}

func types(s map[string]any) []string {
	switch t := s["type"].(type) {
	case string:
		return []string{t}
	case []any:
		out := make([]string, 0, len(t))
		for _, v := range t {
			out = append(out, fmt.Sprint(v))
		}
		slices.Sort(out)
		return out
	}
	return nil
}

// narrows reports whether a field typed next can only carry what one typed was could: dropping null is safe for a
// consumer, a new type or an untyped field is not.
func narrows(was, next []string) bool {
	if len(was) == 0 {
		return true
	}
	return len(next) > 0 && !slices.ContainsFunc(next, func(t string) bool { return !slices.Contains(was, t) })
}

func typeName(ts []string) string {
	if len(ts) == 0 {
		return "any"
	}
	return strings.Join(ts, "|")
}

// TestSchemas_CopyTheGeneratedTexts guards the boot: publishing the catalog parses and generates nothing.
func TestSchemas_CopyTheGeneratedTexts(t *testing.T) {
	assert.LessOrEqual(t, testing.AllocsPerRun(10, func() { _ = Schemas() }), 8.0)
}
